### ISSUE TITLE
Improve parser to able use for hexadecimal format

### ISSUE THREAD

**Issue by ssinprem** [NaturalIntelligence/fast-xml-parser#102]
I have problem when I use for parse hex value in my xml file.
It shown always 0.

![image](https://user-images.githubusercontent.com/25925192/43237984-d24a2f8e-90be-11e8-8635-e52b2b07096d.png)

![image](https://user-images.githubusercontent.com/25925192/43238056-0fab2220-90bf-11e8-9601-d949882b22eb.png)

I try to fix as below.

`src/xmlstr2xmlnode.js` line 139
``` javascript
function parseValue(val, shouldParse) {
    if (shouldParse && typeof val === "string") {
        if (val.trim() === "" || isNaN(val)) {
            val = val === "true" ? true : val === "false" ? false : val;
        } else {
            if(val.indexOf("0x") !== -1){
                val = Number.parseInt(val,16);
            } else if (val.indexOf(".") !== -1) {
                val = Number.parseFloat(val);
            } else {
                val = Number.parseInt(val, 10);
            }
        }
        return val;
```

**Comment by amitguptagwl** [comment]
@ssinprem It seems the correct fix. Can you please raise a PR for this?
