### ISSUE TITLE
failed to compile with React + Webpack

### ISSUE THREAD

**Issue by eugeniosegala** [NaturalIntelligence/fast-xml-parser#106]
Hi,

I have create a React app with React Create App, when i import fast-xml-parser library with:

**const parser = require('fast-xml-parser');** or **import * as parser from 'fast-xml-parser';**

in the build process (for production) webpack says:

**Failed to minify the code from this file: ./node_modules/fast-xml-parser/src/util.js:5** 

Version:
`"webpack": "3.8.1"` specific module for minification: `UglifyJsPlugin`

webpack UglifyJsPlugin minify options doc: https://github.com/mishoo/UglifyJS2/tree/harmony#compress-options

I'm investigating the issue. What do you think of this?

**Comment by amitguptagwl** [comment]
I'm not sure if const declaration in while loop causing it to be failed.

```
while (match) {
        const allmatches = [];
        const len = match.length;
```

> I may not be available for any change, review and other for next 1 week

**Comment by Delagen** [comment]
Uglify does not support Es6, so it need to be precompiled with babel or something else, or try to use uglify-es

**Comment by amitguptagwl** [comment]
@eugeniosegala has your problem solved?

**Comment by amitguptagwl** [comment]
@eugeniosegala feel free to reopen it or to create another issue.
