### ISSUE TITLE
Change in naming conventions

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#107]
Though this can be a breaking change but I feel that naming conventions of end user APIs should be improved. Eg browser bundle can be accessed by *parser* which is so generic and may conflict with other libraries so it can be renamed to fxp or fxparser. 

There are many other cases where the name may confuse end user. Eg j2xParser.

Your thought on the same are welcome.

**Comment by Delagen** [comment]
fxParser I think. With console version of fx-parser

**Comment by amitguptagwl** [comment]
Agree! We can change it.

**Comment by mubaidr** [comment]
Yes, I think its better for consistency and avoiding confusion.

**Comment by amitguptagwl** [comment]
done in v4.0.0-beta.0
