### ISSUE TITLE
Check if rollup is better than webpack for fast-xml-parser

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#110]
As title says

**Comment by Delagen** [comment]
@Zalastax recommend it. But does he using it for a while?
1. RollupJs designed for tree shake ES modules, so plugin need for transform modules to this format, because of project use CommonJs. Or rewrite to ES6 and produce bundle for NodeJs too.
2. I work as a mentor for hobby, and in work project we use Rollup as bundler with very simple config. Debugging in browser make me sad, if your modules has similar top variable names (only vars, not exports) you cannot view it value without switch to bundle code because of sourcemaps seems does not contains var renames

**Comment by Delagen** [comment]
3. Webpack also use some tree shake for now. Overhead is small, but pain in the ass is rare thing

**Comment by Delagen** [comment]
Here config for @Zalastax if he thinks that we use some plugins that add this breaks:
```
 

gulp.task(`scripts`, () => {

return gulp.src(`js/main.js`)

.pipe(plumber())

.pipe(sourcemaps.init())

.pipe(rollup({}, `iife`))

.pipe(sourcemaps.write(``))

.pipe(gulp.dest(`build/js`));

});

```

**Comment by Zalastax** [comment]
I've used rollup in a few projects and always with good results. The commonjs plugin for rollup is a good as a first step but it should be migrated away from fairly quickly in my opinion, i.e. the code should eventually be written using ES modules if you want to use rollup. The nice thing about ES modules is that you don't need separate builds - library consumers can just tree shake away unused code instead.

I've not kept up with webpack so I can't say how much better rollup would be but I know for sure that rollup produces state of the art bundles (small size, fast) when the whole project uses ES modules.

**Comment by Delagen** [comment]
As I can see you don't produce source maps in your builds.

**Comment by Zalastax** [comment]
When you use rollup you should let it handle the source maps by setting `sourcemap: true`, then it should be accurate. If source maps work is there still a need to use multiple bundlers?

> support different module types in base

Can you elaborate on this?
Rollup can emit [several formats](https://rollupjs.org/guide/en#big-list-of-options) and can handle commonjs in the source code. Perhaps you meant something else?

The big reason to use rollup is that [webpack can't emit ES modules](https://github.com/webpack/webpack/issues/2933), so library users don't get tree shaking for fast-xml-parser. Unless there's something blocking us from using it I think it would be worth the effort to do the switch.

**Comment by Delagen** [comment]
I mean webpack can consume different module types. If your code written in ES, you don,t need bundler, simply share source. I use webpack to bundle nodejs and browser bundles
