### ISSUE TITLE
Dose fast-xml-pare support async run for not block main thead

### ISSUE THREAD

**Issue by xushuwei202** [NaturalIntelligence/fast-xml-parser#111]
Dose fast-xml-pare support async run?
I find it will block main thead run  if I parse large size xml to json.

**Comment by amitguptagwl** [comment]
No! There is not much advantage of that as it is not doing any async functionality. However you can always wrap it in some async function.

**Comment by amitguptagwl** [comment]
@xushuwei202 feel free to reopen this for further discussion.
