### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dolanmiu** [NaturalIntelligence/fast-xml-parser#115]
I am getting this error here when doing a simple `npm install`:

https://travis-ci.org/dolanmiu/docx/builds/427328278

It is saying how it cannot find fast-xml-parser/cli.js

```bash
$ npm install
npm WARN The package jszip is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! path /home/travis/build/dolanmiu/docx/node_modules/fast-xml-parser/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/travis/build/dolanmiu/docx/node_modules/fast-xml-parser/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-11T19_49_40_777Z-debug.log
The command "npm install" failed and exited with 254 during .
```

Any ideas?

**Comment by wookiee89** [comment]
Having similar issue .. 

`npm ERR! path /tmp/deployment/application/node_modules/fast-xml-parser/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/deployment/application/node_modules/fast-xml-parser/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
`

**Comment by amitguptagwl** [comment]
Apologies.. last commit raised the issue. Can you please try now?

**Comment by sqlwwx** [comment]
@amitguptagwl 
`internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module '/home/travis/build/sqlwwx/pure-func/node_modules/fast-xml-parser/tasks/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
make: *** [install] Error 1`

**Comment by ravibhavsar** [comment]
Having similar issue

`error \node_modules\fast-xml-parser: Command failed.
Exit code: 1
Command: node tasks/postinstall.js
Arguments:
Directory: \node_modules\fast-xml-parser
Output:
module.js:549
    throw err;
    ^Error: Cannot find module 'node_modules\fast-xml-parser\tasks\postinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)`

**Comment by amitguptagwl** [comment]
Ah! It's embarrassing. I'm able to install package in my local successfully but not from the npm registry. I'm working on this.

**Comment by amitguptagwl** [comment]
fixed. please install 3.12.5

**Comment by Delagen** [comment]
I think better to use .npmignore instead of manually specify files in package.json.

**Comment by wookiee89** [comment]
Running into another simlilar issue. Deploying my code to Azure App Service and deployment fails saying:

`571 verbose stack Error: fast-xml-parser@3.12.0 postinstall: `node tasks/postinstall.js`
571 verbose stack Exit status 1
571 verbose stack     at EventEmitter.<anonymous> (/opt/npm/6.0.1/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
571 verbose stack     at EventEmitter.emit (events.js:182:13)
571 verbose stack     at ChildProcess.<anonymous> (/opt/npm/6.0.1/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
571 verbose stack     at ChildProcess.emit (events.js:182:13)
571 verbose stack     at maybeClose (internal/child_process.js:957:16)
571 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
572 verbose pkgid fast-xml-parser@3.12.0`

**Comment by amitguptagwl** [comment]
@wookiee89 I've removed an unnecessary dependency from the postinstall. Can you please try to install fast-xml-parser from github directly? if it works then I'll publish it.

**Comment by Delagen** [comment]
@amitguptagwl I don't think that problem in this.
@wookiee89 Try to update npm

**Comment by Delagen** [comment]
Some systems modify spawn ability to limit process count. So it may be caused by this restriction

**Comment by amitguptagwl** [comment]
Please reopen or create a new issue
