### ISSUE TITLE
Project contains yarn.lock & package-lock.json ?

### ISSUE THREAD

**Issue by gknapp** [NaturalIntelligence/fast-xml-parser#116]
Do you use both package managers for this project? It looks like yarn has not been used in some months.

**Comment by amitguptagwl** [comment]
Yarn was faster so I started using it. But then npm came up with
package-lock so I completely missed yarn to update. I'll have to check if
it is still beneficial to use yarn. If so then will update it

**Comment by amitguptagwl** [comment]
I've updated yran.lock.
