### ISSUE TITLE
Parse multiple attributes with the same name

### ISSUE THREAD

**Issue by hdodov** [NaturalIntelligence/fast-xml-parser#117]
First of all, excellent package.

I'd like to request a feature for parsing a tag with several attributes that share the same name. I don't think it's valid XML, but it's a real use case and I need to parse this... Currently, the package returns only the last attribute value. It would be great if it returned an array with the values, in the order they appear.

For example:
```js
const xml = '<p foo="bar" foo="baz"></p>';

var fastXmlParser = require("fast-xml-parser");
var parsedXml = fastXmlParser.parse(xml, {
    ignoreAttributes: false
});

console.log(parsedXml);
```

This returns an object containing `@_foo` with value `"baz"`. It would be awesome if it returned `["bar", "baz"]` and simply `"bar"` if only the first attribute is present.

Hope to get some help.
Thank You!

**Comment by amitguptagwl** [comment]
@hdodov If you pass your sample XML from the validator ( you can try it [online](https://naturalintelligence.github.io/fast-xml-parser/)), you'll get following output

```js
{
    "err": {
        "code": "InvalidAttr",
        "msg": "attribute foo is repeated."
    }
}
```

So yes it is not valid XML. Hence not supported. However as you said that it is a real use case, I would be happy to know more about that for my knowledge. We'll also try to your requested feature. I'll appreciate in case you wanna participate.

> Try the new web framework [Munee](https://github.com/node-muneem/muneem). And provide your valuable feedback to improve it.

**Comment by amitguptagwl** [comment]
@hdodov Having any feature means compromising with performance. Though I don't think it'll be much impacting after having this feature. But I was wondering if we should implement the features for individual cases.

For instance, in your case, you can modify the XMLs (I'm assuming they've already generated) using regex. The only reason I'm avoiding the code change as this is one time required feature. You'll not even need this feature once all the generated XMLs are processed.

**Comment by hdodov** [comment]
Yep, you're right. But in my case, I couldn't exactly modify the XML because it's dynamic and served by an API. But I ended up not needing to parse those duplicate attributes, so everything is alright.

So yeah, you can scratch that issue.

**Comment by amitguptagwl** [comment]
ok. So I'm assuming that API owner can't modify their API. I may guide you to form this repo and do necessary changes. However, it'll be an overhead to maintain the separate repo and merging any future change.
