### ISSUE TITLE
Improve validator performance

### ISSUE THREAD

**Issue by loge5** [NaturalIntelligence/fast-xml-parser#12]
Hi,

First the Parser is incredible fast - good job!
For 5.7MB XML (multiple files, parse parallel) it needs ~150ms  (xml2js needs ~2200ms).
But with validation it needs ~14644ms (!sic).

You can reproduce this even on the "try me" page when you copy/paste more person-elements in the xml. While "parse to Json" stays fast, the validation time seems to grow exponentially.

It would be great if you can improve the performance.

**Comment by amitguptagwl** [comment]
Thanks for highlighting. What is the performance of other libraries you compared for validation?

Currently I'm not having any machine . So I'll check that in July for increasing the performance. Sorry for the delay.

**Comment by amitguptagwl** [comment]
Done. Previous performance was 2000 rps, new is 21000 rps. But you'll not get the line number where the issue is.

Please let me know if you find any observation.

**Comment by amitguptagwl** [comment]
I have updated the validator to handle large files as well.
