### ISSUE TITLE
Question: my performance test shows that it is about 2x faster than xml2js, how do I make it even faster ?

### ISSUE THREAD

**Issue by qiulang** [NaturalIntelligence/fast-xml-parser#120]
Hi,
This is a question about the performance so sorry if this is not the right place to raise it.
I have several thousands xml files to parse and I found xml2js is too slow. So I try fast-xml-parse. I attached a sample xml file to let you get an idea what kind of xml file I deal with(change file name to .txt because github won't let me upload .xml). 
[1000_000000b9_918688901135_15000002965_15000002965_2_20180508_100308_100443_95_7353652.txt](https://github.com/NaturalIntelligence/fast-xml-parser/files/2483202/1000_000000b9_918688901135_15000002965_15000002965_2_20180508_100308_100443_95_7353652.txt)

Basically I need to get `<text> at <function value="1-best" ... >` element

With fast-xml-parse I can get 2x faster than xml2js but I can't push it further as your benchmark data shows. So I wonder is there any trick I miss?

```
function parsexml(file) {
    let data = fs.readFileSync(file, 'utf8')
    if (!data) {
        return
    }
    var jsonObj = fparser.parse(data, {
        ignoreAttributes: false,
        parseAttributeValue: false,
        parseNodeValue: false
    })
    try {
        let channel = jsonObj.result.instance.subject.filter(
            subject => subject['@_value'] == 'search'
        )[0].channel
        var user = '',
            agent = ''
        channel.forEach(c => {
            if (c['@_no'] == 'n0') {
                agent = c.function.filter(
                    func => func['@_value'] == '1-best'
                )[0].text
            }
            if (c['@_no'] == 'n1') {
                user = c.function.filter(func => func['@_value'] == '1-best')[0]
                    .text
            }
        })
        user = user.replace(/ /g, '')
        agent = agent.replace(/ /g, '')
        if (agent.length == 0 && user.length == 0) {
            return
        }
        return { user, agent }
    } catch (err) {
        error(`${file} has problem`)
        return
    }
}
```

Compared to xml2js codes

```
async function parsexml2(file) {
    let data = fs.readFileSync(file, 'utf8')
    if (!data) {
        return 
    }
    let xml = await parser.promise(data)
    try {
        let channel = xml.result.instance[0].subject.filter(
            s => s.$.value == 'search'
        )[0].channel
        var user = '',
            agent = ''
        channel.forEach(c => {
            if (c.$.no == 'n0') {
                agent = c.function.filter(f => f.$.value == '1-best')[0].text[0]
            }
            if (c.$.no == 'n1') {
                user = c.function.filter(f => f.$.value == '1-best')[0].text[0]
            }
        })
        user = user.replace(/ /g, '')
        agent = agent.replace(/ /g, '')
        if (agent.length == 0 && user.length == 0) {
            return
        }
        return { user, agent }
    } catch (err) {
        return
    }
}

```

**Comment by amitguptagwl** [comment]
Performance test result can be impacted by machine, input, running processes etc. However, I believe how you are comparing the performance includes the performance of parsing XML and your code to access the particular element. But I compare the performance of parsing XML only.

This is the result for your input XML on a 16gb machine. FXP is around 8-9 times faster.

FXP : 11551.243768244743 requests/second
xml2js  : 1288.1723166028787 requests/second

**Comment by qiulang** [comment]
Hi I am not challenging your result. I was asking if there other ways to boost my performance further. For example does my code to access the particular element is recommended way to do it ? Is there a better way ?
