### ISSUE TITLE
suppressEmptyNode not working

### ISSUE THREAD

**Issue by milesje** [NaturalIntelligence/fast-xml-parser#121]
### Checklist

* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

```
const fxp = require('fast-xml-parser');
const j2xOptions= {
    suppressEmptyNode: true
};
const Parser = fxp.j2xParser;
const j2xParser = new Parser(j2xOptions);
const jsonObj = {
    PASS_ELEMENT: {
            'CASE-PROSECUTOR': "",
            'CASE-JUVENILE-IND': ""
  }};
console.log(j2xParser.parse(jsonObj));
```

Here is the actual out put.
`<PASS_ELEMENT><CASE-PROSECUTOR></CASE-PROSECUTOR><CASE-JUVENILE-IND></CASE-JUVENILE-IND></PASS_ELEMENT>`
I would expect
`<PASS_ELEMENT><CASE-PROSECUTOR/><CASE-JUVENILE-IND/></PASS_ELEMENT>`

**Comment by amitguptagwl** [comment]
Please reopen if you still face this issue.

**Comment by olivierchatry** [comment]
Not sure will work : https://github.com/NaturalIntelligence/fast-xml-parser/blob/8a090d7662221c74221ee30e13acb24263cf06e1/src/json2xml.js#L77 

Seems like the options will always be overidden

**Comment by olivierchatry** [comment]
Nerver mind, I got confused by the naming :)
