### ISSUE TITLE
Null values JSON to XML

### ISSUE THREAD

**Issue by georgehanson** [NaturalIntelligence/fast-xml-parser#123]
I am trying to parse JSON to XML to send it through a SOAP api. I have managed to get empty fields to be self closing using the `supressEmptyNode` option. However, for these fields they also need the attributes: `xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"` and `xsi:nil="true"`. Is there an option that enables these, or a way to format the JSON so that these are added when it is parsed?

**Comment by amitguptagwl** [comment]
Can you please share a sample JSON? So I can understand your query better.

**Comment by georgehanson** [comment]
Sure. Using this:

```json
{
  "ContactId": 123,
  "Title":"Mr",
  "FirstName": "John",
  "LastName":"Doe",
  "DateOfBirth":""
}
```

This is converting to the following in XML:

```xml
<ContactId>123</ContactId>
<Title>Mr</Title>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<DateOfBirth />
```

However, for `DateOfBirth` I need this to have those attributes. So it should look like:

```xml
<ContactId>123</ContactId>
<Title>Mr</Title>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<DateOfBirth xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" />
```

Does that help?

**Comment by amitguptagwl** [comment]
Values which are not present in JSON can't present in XML. However, if you modify your JSON;

```json
{
    "ContactId": 123,
    "Title": "Mr",
    "FirstName": "John",
    "LastName": "Doe",
    "DateOfBirth": {
        "@": {
            "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "xsi:nil": "true"
        }
    }
}
```

and modify JSON to XML parser with relevant configurations (see README for more detail);

```js
var Parser = require("fast-xml-parser").j2xParser;
var defaultOptions = {
    attrNodeName: "@", //default is false
    ignoreAttributes : false,
    supressEmptyNode: false,
};
var parser = new Parser(defaultOptions);
var xml = parser.parse(json_or_js_obj);
```

**Comment by georgehanson** [comment]
Thanks, seems to do the trick
