### ISSUE TITLE
location of validation error

### ISSUE THREAD

**Issue by jzou2000** [NaturalIntelligence/fast-xml-parser#124]
Hi
I think it would be better to give line/column of error when the validation fails. Those information are very useful when the xml file is large. xml2js (and most validators) gives those info.

Currently the err object contains only code and msg. I checked the source code of validate and it seems it is not a config issue.

PS. is it possible to validate while parsing? If I validate then parse, the speed reduce half, if I don't validate, the parser parses silently but gives the wrong result.

Thanks.

**Comment by amitguptagwl** [comment]
If we combine, parsing speed will definitely reduce. As in most of the cases, we need not validate the trusted resources it is important to keep them separate.

Line number can be calculated but in some cases, it can be inaccurate. Let be mark it as a feature request so we can do something helpful. However, I can't commit any timeline to get it done.

**Comment by mubaidr** [comment]
An `validate` option can be added to the method, with defaults set to `false`. For users library will be fast and if someone wants to validate, he/she can set it to true.

**Comment by amitguptagwl** [comment]
@mubaidr though it's a good suggestion, @jzou2000 has the concern about overall throughput when validation and parsing are combined.

**Comment by amitguptagwl** [comment]
@mubaidr , @jzou2000 we have changed the method signature to optionally choose if validation need to be done.

**Comment by NorbertHuethmayr** [comment]
Any news on the initial request to include the line number when validation runs into an error?

**Comment by amitguptagwl** [comment]
No changes done for line number in response yet. However, if someone is interested to raise the PR please visit line number 137 in validator.js
