### ISSUE TITLE
tagValueProcessor used instead of attrValueProcessor 

### ISSUE THREAD

**Issue by atomictag** [NaturalIntelligence/fast-xml-parser#128]
shouldn't the following line 

https://github.com/NaturalIntelligence/fast-xml-parser/blob/a5fe74b77b8d8cd37f3a2abca6ac2f25f01fe246/src/json2xml.js#L137

use `attrValueProcessor` instead of `tagValueProcessor`?

**Comment by amitguptagwl** [comment]
Hmmm... agree.. will have to cross check with the test.
