### ISSUE TITLE
CDATA Parsing Issue

### ISSUE THREAD

**Issue by venkatsep14** [NaturalIntelligence/fast-xml-parser#13]
Hi, Not parsing the CDATA correctly. It is able to parse the CDATA when the elements are formatted like this.
<sql-query id="checkemail"><![CDATA[SELECT * FROM user_tbl WHERE email =? order by id desc]]></sql-query>

if the xml formatted like this - It is failing to get the data.

<sql-query id="checkemail">
   <![CDATA[SELECT * FROM user_tbl WHERE email =? order by id desc]]>
</sql-query>

Instead of depending on the substring logic it should read the whole text between the tags. Please let me know if you have time to fix this issue otherwise will try to look for another solution.

**Comment by amitguptagwl** [comment]
Hi,
Can you plz share the sample XML you are trying with?

**Comment by venkatsep14** [comment]
<sql-queries>
    <sql-query id="testquery">
        <![CDATA[select * from search_urls]]>
    </sql-query>
    <sql-query id="searchInfo">
        <![CDATA[select * from search_urls where search_url=?]]>
    </sql-query>
    <sql-query id="searchurls">
        <![CDATA[select search_url from search_urls ]]>
    </sql-query>
</sql-queries>

**Comment by amitguptagwl** [comment]
Hi,

I'm not sure if the problem is limited to your example only. But it looks
like CDATA is not working at all. However since I don't have machine for
any debugging or fixes. I'll not be able to help you before 8th June
(expected).

Although the problem seems very small, but I'll not be able fix it until I
get some machine. :-(

**Comment by amitguptagwl** [comment]
I got my machine. And I have fixed the issue as well. Will publish soon.

**Comment by amitguptagwl** [comment]
published. Plz use 2.4.3

**Comment by venkatsep14** [comment]
Thank you and I will check on this and will update you.

Thanks
Venkat
