### ISSUE TITLE
SelfClosing tag with boolean attributes will fail on parse

### ISSUE THREAD

**Issue by Takkuz** [NaturalIntelligence/fast-xml-parser#132]
### Checklist
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input
```xml
<widget>
    <selfClosing withAttr="yes" />
    <noAttr />
    <noSpace/>
</widget>
```

### Output
Running on OnLine Tool you can see that, with `Allow Boolean Attributes` flag ON, when there's no space between TagName and closing tag `/` will be identified as boolean attributes.

Bad part is the j2xparser will write every selfclosing tag without space before closing tag `/>` so a second parse will result in an error.

### expected data

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Thanks to reporting an issue. We'll be working on that.

**Comment by amitguptagwl** [comment]
> Bad part is the j2xparser will write every selfclosing tag without space before closing tag /> so a second parse will result in an error.

@Takkuz Do you mean that when you pass parsed XML (which is invalid due to the bug you reported) to the j2xparser then it gives the error?

Please confirm so that I can publish the changes.

**Comment by Takkuz** [comment]
I mean this code will run :

```
const parser = require('fast-xml-parser');

const xmlParserOptions = {
  attributeNamePrefix : '',
  attrNodeName: '$',
  textNodeName : '_',
  ignoreAttributes : false,
  ignoreNameSpace : false,
  allowBooleanAttributes : true,
  parseNodeValue : true,
  parseAttributeValue : true,
  // Options for JSON to XML
  format: true,
  supressEmptyNode: true,
  indentBy: "  ",
}

const dataString = `
  <widget>
    <name>Test</name>
    <selfClosing withAttr="yes" />
    <noAttr />
    <noSpace/>
  </widget>
`;

const parsed = parser.parse(dataString, xmlParserOptions);
console.log(`JSON:\n${JSON.stringify(parsed, null, 2)}\n`);
const parsedConfigXml = (new parser.j2xParser(xmlParserOptions)).parse(parsed);
console.log(`XML:\n${parsedConfigXml}\n`);
const secondParsed = parser.parse(parsedConfigXml, xmlParserOptions);
console.log(`Second JSON:\n${JSON.stringify(secondParsed, null, 2)}\n`);
```

Will show the first time:
```json
"noAttr": "",
"noSpace": {
  "$": {
    "/": true
  }
}
```

Then it will parse back to XML:
```xml
<noAttr/>
<noSpace /="true"/>
```

Then to next JSON:
```json
"noAttr": {
  "$": {
    "/": true
  }
},
"noSpace": {
  "$": {
    "/": true
  }
}
```

**Comment by amitguptagwl** [comment]
ok. So this problem must have been solved now. I'll publish the changes.
