### ISSUE TITLE
It always return a number when a tagvalue is a string. like '000', return '0'

### ISSUE THREAD

**Issue by galaa2011** [NaturalIntelligence/fast-xml-parser#133]
How can I get '000'

**Comment by amitguptagwl** [comment]
what options are you trying with parser?

**Comment by galaa2011** [comment]
Oo, thanks. But I have some confusion with the option value! false to parse string to number and true not!

**Comment by amitguptagwl** [comment]
That makes sense with the option name. '000' is not a true number so one of the contributors decided to have this option.
