### ISSUE TITLE
Exception converting json back to xml

### ISSUE THREAD

**Issue by jinq102030** [NaturalIntelligence/fast-xml-parser#138]
I need to use this module for a project to do some processing on XML --> JSON --> XML. 

Checked out the code today and apply it on the xml from here: https://raw.githubusercontent.com/GovReady/govready/master/prototypes/ssg-rhel6-oval.xml

Got error
```
/Users/jdole/learn/node/node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:48
    xmlData = xmlData.replace(/<!--[\s\S]*?-->/g, "");//Remove  comments
                      ^

TypeError: xmlData.replace is not a function
    at Object.getTraversalObj (/Users/jdole/learn/node/node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:48:23)
    at Object.exports.parse (/Users/jdole/learn/node/node_modules/fast-xml-parser/src/parser.js:10:50)
    at Object.<anonymous> (/Users/jdole/learn/node/xml2js.js:26:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

The code snippet is adopted from your example.
```
var parser = require('fast-xml-parser');
var he = require('he');
var fs=require("fs");

var options = {
    attributeNamePrefix : "@_",
    attrNodeName: "attr", //default is 'false'
    textNodeName : "#text",
    ignoreAttributes : false,
    ignoreNameSpace : false,
    allowBooleanAttributes : false,
    parseNodeValue : true,
    parseAttributeValue : false,
    trimValues: true,
    cdataTagName: "__cdata", //default is 'false'
    cdataPositionChar: "\\c",
    localeRange: "", //To support non english character in tag/attribute values.
    parseTrueNumberOnly: false,
    attrValueProcessor: a => he.decode(a, {isAttributeValue: true}),//default is a=>a
    tagValueProcessor : a => he.decode(a) //default is a=>a
};
xml=fs.readFileSync("ssg-rhel6-oval.xml", "utf8");

var result1;
var jsonObj = parser.parse(xml,options);
console.log(parser.parse(jsonObj))
```

Is this a bug in this module?

**Comment by jinq102030** [comment]
Thanks Amit for taking a quick look.  The URL is indeed valid.  Did you try
```
wget https://raw.githubusercontent.com/GovReady/govready/master/prototypes/ssg-rhel6-oval.xml
```
to download the xml?  it's a 748K file.

**Comment by jinq102030** [comment]
The xml file is downloaded to the local directory (same as the script and I ran it from there).

I was able to parse the xml into a big JSON file (which proves the file is fine). 

Thanks.

**Comment by amitguptagwl** [comment]
I've just tested your file. everything looks fine to me.

```js
const fs = require("fs");
const path = require("path");
const fileNamePath = path.join(__dirname, "./ssg-rhel6-oval.xml");

const xmlData = fs.readFileSync(fileNamePath).toString();

const jsObj = parser.parse(xmlData);
const j2xParser = new parser.j2xParser();
const result = j2xParser.parse(jsObj);
```

**Comment by jinq102030** [comment]
Thanks Amit, it works fine.  But I have another problem, going to report in a new ticket.

**Comment by amitguptagwl** [comment]
So what was the issue?

**Comment by jinq102030** [comment]
Since this issue is closed, I created a new issue.  #139.  Thanks!

**Comment by amitguptagwl** [comment]
I mean what was the problem you were facing problem in this issue?

**Comment by Treverix** [comment]
The problem he faced was, like mine, that he didn't convert the file contents to a string.

This causes the error:
```
xml=fs.readFileSync("ssg-rhel6-oval.xml", "utf8");
```
And this works:
```
xml=fs.readFileSync("ssg-rhel6-oval.xml", "utf8").toString();
```

**Comment by gregorydgarcia** [comment]
Hi @amitguptagwl . Great repo thanks for spending the time on it. The read me does not specify that the xmlData needs to be read to a string prior to importing. This can be very confusing as fs.readFile and most express middlewear libs default to using a buffer. I think it may help others to note that the xmlData input needs to be a string.

**Comment by amitguptagwl** [comment]
@gregorydgarcia good point. Can you raise a PR to add this line in README? I never thought about it before.
