### ISSUE TITLE
XML produced is not valid

### ISSUE THREAD

**Issue by jinq102030** [NaturalIntelligence/fast-xml-parser#139]
Try to convert XML to JSON and to XML.

Download the xml from "https://raw.githubusercontent.com/GovReady/govready/master/prototypes/ssg-rhel6-oval.xml"
and try to run the following code,  it produced a new xml file, but when loading it to Firefox,  it complained that this xml is not valid.
```
XML Parsing Error: prefix not bound to a namespace
Location: file:///Users/jdole/learn/node/delme.xml
Line Number 1, Column 30:<oval_definitions><generator><oval:product_name>python</oval:product_name><oval:product_version>2.6.6</oval:product_version><oval:schema_version>5.1</oval:schema_version><oval:timestamp>
-----------------------------^
```

Here is the code snippet.  
```
var parser = require('fast-xml-parser');
const fs = require("fs");
const path = require("path");
const fileNamePath = path.join(__dirname, "./ssg-rhel6-oval.xml");

const xmlData = fs.readFileSync(fileNamePath).toString();

const jsObj = parser.parse(xmlData);
const j2xParser = new parser.j2xParser();
const result = j2xParser.parse(jsObj);
console.log(result);
```

Any ideas why?  Thanks in advance!

**Comment by amitguptagwl** [comment]
what are you loading in Firefox? XML file? Have you tried to load both original and generated XML file? Have you tried to compare both original and generated files?

I'll really appreciate if you do some original finding.

**Comment by jinq102030** [comment]
I used Firefox to check the validity of the resulted XML file. Wonder if you could help me to fix it.  Thanks.

**Comment by amitguptagwl** [comment]
Can you please answer all the questions I asked?

**Comment by jinq102030** [comment]
Sorry Amit.   I only answered the first question.

Yes,  Firefox is ok with original XML but generate an error on the resulted XML. 

Hope this answers all your questions.

**Comment by jinq102030** [comment]
The generated xml is not well-idented and hence hard to read and compare.  If it were valid in syntax, I could use tools such as Firefox to beautify it.

**Comment by amitguptagwl** [comment]
@jinq102030 Have you checked README to know how to indent the output? I believe not.

I'm sorry to say that I see no issue here. And since there is no effort is being spent by the issue raiser to provide sufficient information to understand the issue, we'll not be able to provide any help on this issue further.
