### ISSUE TITLE
Doesn't support attributes by default.

### ISSUE THREAD

**Issue by mariussmit** [NaturalIntelligence/fast-xml-parser#14]
Great lib. Attribute parsing is off by default. I needed to add the correct options object to make it work.

```javascript
var options = {
    attrPrefix : "@_",
    textNodeName : "#text",
    ignoreNonTextNodeAttr : false,
    ignoreTextNodeAttr : false,
    ignoreNameSpace : false,
    textNodeConversion : true
};
```

**Comment by amitguptagwl** [comment]
Attributes are supported. Tell me what is the configuration you are doing
and what is the issue you are facing.

**Comment by amitguptagwl** [comment]
Perhaps I didn't get your concern. Do you want to make attribute parsing by default?

The reason I made it configurable because many project who convert XML to json don't want to consider attributes.

Please let me know if there is anything I can help.

**Comment by mariussmit** [comment]
Thanks Amit. Yes it was merely because I tried the "Try Me" which didn't parse the attributes as well as scanned the readme too quickly, so didn't spot the section on attributes. Maybe you can add an option or a comment on your "Try Me" page for attributes.

**Comment by amitguptagwl** [comment]
Sure, I'll enhance "try me" page to support most of the options we can do from XML parser.
