### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by jinq102030** [NaturalIntelligence/fast-xml-parser#141]
Tried to get the JSON to xml part working, currently experiencing a problem. Can't find a similar issue in stackoverflow.

Do you have the documentation or you want user to read the code?

**Comment by csvan** [comment]
Why invalid? This library looks good, but without any documentation to go with it is effectively useless as soon as you want to do anything beyond the most basic things. 

For example, I have attributes in my XML which are not ending up in the resulting JSON. The README gives me absolutely no indication of what might be going wrong, and without examples or explanations for the options it is nearly impossible to go further without digging into the source code.

**Comment by amitguptagwl** [comment]
@csvan If you have a look on specs you should get fair idea how to use this library with various example. Documentation is about short description about features and how to use them. E.g.

```js
it("should parse only true numbers", function() {
        const xmlData = `<rootNode>
        <tag>value</tag>
        <boolean>true</boolean>
        <intTag>045</intTag>
        <floatTag>65.340</floatTag>
        <long>420926189200190257681175017717</long>
        </rootNode>`;
        const expected = {
            "rootNode": {
                "tag":      "value",
                "boolean":  true,
                "intTag":   "045",
                "floatTag": 65.34,
                "long": "420926189200190257681175017717"
            }
        };

        const result = parser.parse(xmlData, {
            parseTrueNumberOnly : true
        });
        //console.log(JSON.stringify(result,null,4));
        expect(result).toEqual(expected);
    });
``` 

It is difficult to cover all the combinations in the document. Hence, stackoverflow or github issues can help better. However, if you still feel it can be better covered in documents, I would be happy to see an example. Then we can take it further.

You can create a doc folder on root of the project and raise a PR with sample doc.
