### ISSUE TITLE
[Validator failing] parser.validate failing but XML is valid based on every online tool

### ISSUE THREAD

**Issue by karimcambridge** [NaturalIntelligence/fast-xml-parser#143]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
https://pastebin.com/74F1dCQa < `test.xml`

```
fast-xml-parser@3.12.13 | MIT | deps: 1 | versions: 64
Validate XML or Parse XML to JS/JSON very fast without C/C++ based libraries
https://github.com/NaturalIntelligence/fast-xml-parser#readme
```

### Code
```js
const fs = require('fs');
const xmlParser = require('fast-xml-parser');

const parseXMLtoJson = (fileLocation) => {
	log.fatal(`[parseXMLtoJson]: Reading '${fileLocation}'`);
	fs.readFile(fileLocation, (err, xmlData) => {
		log.fatal(`[parseXMLtoJson]: '${fileLocation}' read. xmlData: ${xmlData.length}`);
		let options = {
			attributeNamePrefix : "",
			attrNodeName: false,
			textNodeName : "#text",
			ignoreAttributes : true,
			ignoreNameSpace : false,
			allowBooleanAttributes : false,
			parseNodeValue : false,
			parseAttributeValue : false,
			trimValues: true,
			cdataTagName: false,
			cdataPositionChar: "\\c",
			localeRange: "", // To support non english character in tag/attribute values.
			parseTrueNumberOnly: false
		};
		 
		if(xmlParser.validate(xmlData) === true) { // optional (it'll return an object in case it's not valid)
			let jsonObj = xmlParser.parse(xmlData, options);
			log.fatal("[parseXMLtoJson]: Json -> ", jsonObj);
		} else {
			log.fatal("[parseXMLtoJson]: Invalid XML.");
		}
	});
	// Intermediate obj
	//var tObj = xmlParser.getTraversalObj(xmlData,options);
	//var jsonObj = xmlParser.convertToJson(tObj,options);
};

parseXMLtoJson('test.xml');
```

### Output
`"[parseXMLtoJson]: Invalid XML."`

### expected data
`"[parseXMLtoJson]: Json -> ", jsonObj`

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

--

Validator is returning false, but it is working online.

**Comment by amitguptagwl** [comment]
@karimcambridge It returns true for the same version of FXP. 

I believe this is because you haven't the file content is a buffer. Can you please recheck along with the file content.

**Comment by karimcambridge** [comment]
I was because I didn't set the encoding to XML on `fs.readFile`. lol...

Fixed it.

**Comment by amitguptagwl** [comment]
Thanks you solved it yourself. However, I'll appreciate asking such questions on Stackoverflow because there you can get the support from many people but here I'm only the active maintainer.
