### ISSUE TITLE
New Feature: XML to YAML

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#145]
Converting an XML to JS object and then to YAML is a slow approach. As we're already parsing the XML into an intermediate object, we can use this object to write YAML. However, we need to know if there are some projects who really feel the need for this direct transformation.

As YAML format can't be used in programming directly, they only use case I feel is the online converter. But we don't need any fast solution for that in my understanding. We can use this library to covert the XML to JS object and then can use YAML parser to converter it further to YAML. 

So if someone can let us know the need for this feature, we can think about its implementation.

**Comment by bhreinb** [comment]
+1 from me for the feature :)

**Comment by amitguptagwl** [comment]
Closing the issue as other users have shown no interest in this feature request. Feel free to reopen.
