### ISSUE TITLE
Double values inside tags

### ISSUE THREAD

**Issue by EricMoIr** [NaturalIntelligence/fast-xml-parser#146]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

The parse function of the default export converts doubles that are "X.0" into "X", which ends up breaking some of my dependencies. Other doubles that end with any number that isn't 0 works correctly

 
### Input

```
<dependencies>
        <dependency>
            <groupId>org.xhtmlrenderer</groupId>
            <artifactId>core-renderer</artifactId>
            <version>8.0</version>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>6.0</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
</dependencies>
```

### Code
```js
const parser = require("fast-xml-parser");
const Parser = parser.j2xParser;
const options = {
    ignoreAttributes : false,
    format: true,
};
const xmlParser = new Parser(options);
const xmlData = fs.readFileSync(path, "utf8");
let json = parser.parse(xmlData, options);
const newXml = xmlParser.parse(json);
fs.writeFileSync(path, newXml);
```

### Output
```
<dependencies>
        <dependency>
            <groupId>org.xhtmlrenderer</groupId>
            <artifactId>core-renderer</artifactId>
            <version>8</version>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>6</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
</dependencies>
```

### expected data

```
<dependencies>
        <dependency>
            <groupId>org.xhtmlrenderer</groupId>
            <artifactId>core-renderer</artifactId>
            <version>8.0</version>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>6.0</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
</dependencies>
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
@EricMoIr In Javascript;

```js
> var a = 9.0
undefined
> a
9
```

Since you're converting the XML first into JS object, you're losing the decimal point. Better to use `parseNodeValue : false`.

**Comment by EricMoIr** [comment]
That's what I needed! Since that option didn't show in the "Options" section of the readme, I didn't realize it existed. Just found it in the .d.ts file. Thank you!

**Comment by amitguptagwl** [comment]
@EricMoIr It is documented in "Options" section as well as in sample snippet on README.

![screenshot from 2019-02-23 06-06-14](https://user-images.githubusercontent.com/7692328/53278765-43af5500-3731-11e9-8e48-c9fc9674619a.png)
