### ISSUE TITLE
JSON message with attribute was not working

### ISSUE THREAD

**Issue by amolpagar** [NaturalIntelligence/fast-xml-parser#147]
Hi Amit, 

It seems JSON to XML with attributes in JSON message is not working properly.
Below function is not getting invoked to check if field is an attribute or not.

function isAttribute(name /*,options*/)  (File Name json2xml.js)

I had to remove this.isAttribute(key) and update isAttribute function as it was not taking options as an argument to check how attribute begins in json and whats its length.

I made local fixes to make it work for me. 

Also, I was not able to use require('fast-xml-parser') because there is no index.js when it package get installed. 
So, I had to load this file again explicitly to access export modules. It would be great if it can be packaged with index.js file.

please excuse , if this problem is only because of something which I did wrong while setting up options.

Thanks!

**Comment by amitguptagwl** [comment]
> I had to remove this.isAttribute(key) and

`isAttribute` is expected t work only if `this.options.ignoreAttributes` is set to `false` or `this.options.attrNodeName` is not set.

> Also, I was not able to use require('fast-xml-parser') because ...

There is a line in package.json '"main": "./src/parser.js",'. Hence it is expected to work. And yes, it is working in the other packages. Please tell me the node.js version.

What are you actually trying to do? You're using this library in your some node.js project or you're doing some changes to this library?

**Comment by amitguptagwl** [comment]
Closing the issue as there is no response. But feel free to reopen or comment.
