### ISSUE TITLE
Consider hiding postinstall support message

### ISSUE THREAD

**Issue by nfantone** [NaturalIntelligence/fast-xml-parser#148]
I love the lib and I 100% get the need for donations and promoting OS stuff. I _do_. But adding a multi line log entry on a `postinstall` script for that purpose seems like a stretch.

- There's no way to silence it. It ignores `--silent` or `--quiet` `npm` flags.
- It floods already hard to trace CI logs with unnecessary text.
- It kind of abuses the original intention of a post install clean up feature with dubious results.
- It tends to induce the exact opposite feedback that the message was intended for when used as promotional spam message that cannot be opted out.

AFAIK, the only way to suppress it is via `--ignore-scripts`. But that disables _all_ scripts for every dependency in the tree.

Ideally, it should honour `npm` log levels. If this cannot be easily done, may I suggest that logging be moved behind an env var (similar to what [`nodemon` does](https://github.com/remy/nodemon/blob/master/bin/postinstall.js#L4))?

Many thanks.

**Comment by amitguptagwl** [comment]
I agree with your points. Will do the changes soon.

**Comment by amitguptagwl** [comment]
I followed the script you suggested and did the changes.

**Comment by nfantone** [comment]
Thanks so much for this! Truly appreciated.
