### ISSUE TITLE
Be able to stop parsing at certain node

### ISSUE THREAD

**Issue by user1020** [NaturalIntelligence/fast-xml-parser#149]
Wonder if if there is an option when doing xml to json conversion, upon encountering a special tag, such as `htmlHere`, it should stop parsing what's in the tag, treat the whole thing (with proper escaping) as a string?

For example xml

```
...
<htmlHere>
    <p>this is line one</p>
   <span>test1</span>
   <p>this is line two</p>
</htmlHere>
```
should be parsed to

```
"htmlHere": "    <p>this is line one</p>\n   <span>test1</span>\n   <p>this is line two</p>"
```
Thanks in advance.

**Comment by amitguptagwl** [comment]
Do you have control on XML? If yes then you can use CDATA for the same.

**Comment by amitguptagwl** [comment]
@jinq102030 what we first need to understand following before implementation

1. the importance of any feature. 
2. can it be achieved without a change in the library
3. what is the impact on the performance.

**Comment by jinq102030** [comment]
Thanks for asking, should have added it earlier.

1. This feature is important in an industry project where we need to extract html code snippet included in xml and render it to user in browser. 
2. Looked at the source code and can't find an existing option that does it.
3. The impact of this when stopNode is not configured is very minimal.  Parsing the 1.6MB xml file with base-line code took about 94ms-96ms (a couple of tries), with the change, the time goes to 97ms-99ms.

**Comment by amitguptagwl** [comment]
@jinq102030 Thanks for your changes. Changes are live now.
