### ISSUE TITLE
Allow attribute name modification by adding attrNameProcessor

### ISSUE THREAD

**Issue by epost** [NaturalIntelligence/fast-xml-parser#151]
### Feature description

Currently, the library recognises the following parameter:
```javascript
    attributeNamePrefix : "@_",
```
I would propose to add the following, more flexible way of generating attribute names:

```javascript
    attrNameProcessor: x => "@_" + x
```

This would work analogously to the existing `attrValueProcessor` parameter.

### Example use case

Rewriting properties like `foo-bar` into `fooBar`.

### Would you like to work on this issue?
- [ ] Yes
- [ ] No
- [x] Perhaps

**Comment by amitguptagwl** [comment]
Hmmm... it sounds good. Feel free to do the changes, if you have some time. Thanks

**Comment by amitguptagwl** [comment]
Closing this as not finding the real use of this. Feel free to reopen it with some real-time example or use case.
