### ISSUE TITLE
Is Lodash really a dependency?

### ISSUE THREAD

**Issue by glenselle** [NaturalIntelligence/fast-xml-parser#157]
Hi, I was looking through the extensive list of dependencies for `fast-xml-parser` 😉 and noticed `lodash` was listed. However, when I did a search of the project I didn't see any uses of `lodash` or `underscore` or `_`. Is this an old dependency listing in `package.json`? It's quite possible I missed something somewhere. It would be awesome if there wasn't a dependency on `lodash` 🎉 .

https://github.com/NaturalIntelligence/fast-xml-parser/blob/5b4487f59be64b17b473ef5476ec94fbf5a8b815/package.json#L90

**Comment by amitguptagwl** [comment]
You're right. It seems unused dependency. We should remove it.
