### ISSUE TITLE
Does not work in IE11 Web Worker due to use of window

### ISSUE THREAD

**Issue by timfish** [NaturalIntelligence/fast-xml-parser#162]
Due to [this code](https://github.com/NaturalIntelligence/fast-xml-parser/blob/65c39beae792e643cd00a6dd866b31178afcf16b/src/xmlstr2xmlnode.js#L13-L19):
```
//polyfill
if (!Number.parseInt && window.parseInt) {
  Number.parseInt = window.parseInt;
}
if (!Number.parseFloat && window.parseFloat) {
  Number.parseFloat = window.parseFloat;
}
```
Would it be better to leave polyfills out completely and direct people to use polyfill.io?

**Comment by amitguptagwl** [comment]
Though it's a good suggestion, our project uses very less browser specific functions as we are the utility not an application. Hence, in my opinion we don't need a complete library at this moment. However, if you feel we can do it better with pollyfill without increasing size of this library then please go ahead.

**Comment by timfish** [comment]
Since this is only [polyfilling these for IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Browser_compatibility) and top level `parseFloat` and `parseInt` have been around forever, it can probably be simplified to:
```
if (!Number.parseInt) {
  Number.parseInt = parseInt;
}
if (!Number.parseFloat) {
  Number.parseFloat = parseFloat;
}
```

**Comment by timfish** [comment]
Alternatively, you can remove the polyfill completely if you just use the top level `parse*` rather than `Number.parse*`:
```
    if (val.trim() === '' || isNaN(val)) {
      parsed = val === 'true' ? true : val === 'false' ? false : val;
    } else {
      if (val.indexOf('0x') !== -1) {
        //support hexa decimal
        parsed = parseInt(val, 16);
      } else if (val.indexOf('.') !== -1) {
        parsed = parseFloat(val);
      } else {
        parsed = parseInt(val, 10);
      }
      if (parseTrueNumberOnly) {
        parsed = String(parsed) === val ? parsed : val;
      }
```

**Comment by amitguptagwl** [comment]
:D `only IE` can't be omitted.
