### ISSUE TITLE
why the Array(1) is translated to a Object ? how can i resolce it ?

### ISSUE THREAD

**Issue by web525** [NaturalIntelligence/fast-xml-parser#166]
Look at the picture below.

![picture](https://s2.ax1x.com/2019/06/17/VHHlQS.png)

**Comment by amitguptagwl** [comment]
FXP parses the XML to JSON based on syntax not on XSD. On first place, it finds repeated elements under the same node. Hence, it converts it into array. On second place, it finds only one occurrence. Hence, object.
