### ISSUE TITLE
Parse attr failed when the attr text has ">"

### ISSUE THREAD

**Issue by heywooooorld** [NaturalIntelligence/fast-xml-parser#167]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
![image](https://user-images.githubusercontent.com/26931962/60268087-2d531900-991e-11e9-9747-7769434094b8.png)

### Code
```js
  let xmlStr = '<P><G ch="aaa>"/><G ch="bb"/></P>';
  let result = fastXmlParser.parse(xmlStr, {
    attrNodeName: '$',
    textNodeName: '#text',
    attributeNamePrefix: '',
    ignoreAttributes: false,
    allowBooleanAttributes: true,
    trimValues: true
  });
  console.log(result);
```

### Output

```
{ P: { G: { '#text': '"/>', '$': [Object], G: [Object] } } }
```
### expected data

```
{ P: { G: [Object, Object] } } }
```
**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Thanks for reporting

**Comment by keith0305** [comment]
I have the same problem. I do a lot of processing with Adobe AEM's .xml files and there were a lot of > in the values of the attrs. Took me some time to realize this was the parser's mistake 😄

**Comment by amitguptagwl** [comment]
The problem has been solved. I'll be publishing the changes soon.

**Comment by amitguptagwl** [comment]
Though the issue was resolved, we observed that this fix impacted the performance badly. We are working on another solution if we find. Otherwise, We'll have to leave this bug open.

**Comment by tigermarques** [comment]
Hi,

Regarding this issue, I understand that it is not yet fixed. However, do you recommend any kind of workaround for the time being? Do you recommend any way of replacing all ">" in attributes for "&gt;"?

Thank you!

**Comment by amitguptagwl** [comment]
Yes, you can use regex to replace all ">" with "&lt;". Eg `=\s*(["']).*?(>).*\1`.

**Comment by amitguptagwl** [comment]
Changes are fixed and published. Please use v3.17.0. Please reopen the issue if any concern is left on the same topic.
