### ISSUE TITLE
Remove configstore dependency

### ISSUE THREAD

**Issue by fabiospampinato** [NaturalIntelligence/fast-xml-parser#169]
Currently configstore is a relatively heavy dependency that's being installed by this library for the only purpose of logging a support message in a postinstall script.

IMHO this dependency is too heavy to be included as a dependency for something that really doesn't have anything to do with how the library work.

Can configstore be removed from the dependencies list?

**Comment by amitguptagwl** [comment]
yes. if you can, please raise the PR. Otherwise will do that on next weekend.

**Comment by fabiospampinato** [comment]
@amitguptagwl I think we can just always show the support message anyway right?

**Comment by amitguptagwl** [comment]
Though I don't see any issue in that, I'll have to check some history. There was some issue raised not to show it to keep their installation log clean. I think 1-2 liner message should not be the issue.

**Comment by amitguptagwl** [comment]
@fabiospampinato done

**Comment by fabiospampinato** [comment]
Thanks a lot!
