### ISSUE TITLE
JS Date Object to XML results in empty tag

### ISSUE THREAD

**Issue by KSDaemon** [NaturalIntelligence/fast-xml-parser#170]
Hi! 

Parsing Date object to XML results in empty tag.

### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input && Code
```js
const j2xParser = require('fast-xml-parser').j2xParser;
let data, parser;

parser = new j2xParser({ format: true });
data = parser.parse({ root: { data: new Date() } });
console.log(data);
```

### Output
```xml
<root>
  <data>
  </data>
</root>
```

### expected data
```xml
<root>
  <data>Tue Jul 16 2019 11:01:29 GMT+0300 (Москва, стандартное время)</data>
</root>
```

I'm in RU locale. So it looks like this. What I mean — expected behavior is to see the output of date.toString()

**Would you like to work on this issue?**
- [ ] Yes
- [ ] No
- [x] Maybe :)

As I looked through the sources. A problem is here: https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/json2xml.js#L96

typeof Date object is `object`
Can be fixed like this:
```js
- } else if (typeof jObj[key] !== 'object') {
+ } else if (typeof jObj[key] !== 'object' || jObj[key] instanceof Date) {
```

I don't know, is it enough or not. It's working, but maybe there are some things I don't know about.

Also, it will be great to have an option to control how tag values are processed. There is `tagValueProcessor` option, but it takes as input string, not an original value, as I see here:

```js
function buildTextValNode(val, key, attrStr, level) {
  return (
    this.indentate(level) +
    '<' +
    key +
    attrStr +
    '>' +
    this.options.tagValueProcessor('' + val) +       //HERE
    '</' +
    key +
    this.tagEndChar
  );
}
```

**Comment by bdbosman** [comment]
I also work with dates, but it converts to XML fine if it has been JSON.strinify()'d first.

**Comment by amitguptagwl** [comment]
@KSDaemon json 2 xml parser comes with a property `tagValueProcessor` where you can set a function to parse your date type of value.

Please free to reopen the card if needed.

**Comment by KSDaemon** [comment]
@amitguptagwl unfortunately, it receives value as `string`, not as the original object.
See: https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/json2xml.js#L113
If it was as you think — i'll be ok with that.

**Comment by amitguptagwl** [comment]
your concern is valid. I've fixed the issue. I'll be publishing them soon.

**Comment by KSDaemon** [comment]
Great! Thnx!
