### ISSUE TITLE
Index position of nodes

### ISSUE THREAD

**Issue by gvillo** [NaturalIntelligence/fast-xml-parser#173]
Hi guys, I was using this great library, but I found something to add to it which is the index of every childNode (and childCount in parent).

I have this particular American football XML (part of it):
```xml
<qtr number="1" text="1st">
   <play hasball="COR" down="1" togo="10" spot="COR40" context="V,1,10,V40" playid="0,1,0" tokens="CMT:Cornell wins the toss and defers"
      text="Cornell wins the toss and defers" newcontext="V,1,10,V40">
   </play>
   <play hasball="COR" down="1" togo="10" spot="COR40" context="V,1,10,V40" playid="0,2,1" tokens="SPOT:V,V40,N"
      text="COR ball on COR40." newcontext="V,1,10,V40">
   </play>
   <play hasball="COR" down="1" togo="10" spot="COR40" context="V,1,10,V40" playid="0,3,2" type="K" tokens="KO:9A,H00 TB:"
      text="Null, Nickolas kickoff 60 yards to the PENN0, touchback." newcontext="H,1,10,H20">
    <p_ko vh="V" name="Blabla" gain="60" result="T"></p_ko>
   </play>
   <drivestart poss="H,H20,15:00" vh="H" spot="H20" clock="15:00" driveindex="1,2"></drivestart>
   <play hasball="PENN" down="1" togo="10" spot="PENN20" context="H,1,10,H20" playid="1,1,3" tokens="SPOT:H,H20,Y"
      text="PENN ball on PENN20." newcontext="H,1,10,H20">
   </play>
</qtr>
```

So, for this sport the actual order of plays and drivestart nodes is key. While I am parsing this XML and converting into a JSON, I loose the order, so that's why I added 2 options `appendIndexInNodes` (boolean, false by default) and `indexInNodesName` (string, '#index' by default) to set up this feature.

The result appending index in every node will be:

```javascript
{
    "childCount": 1,
    "qtr": {
        "@_number": "1",
        "@_text": "1st",
        "#index": 0,
        "childCount": 5,
        "play": [
            {
                "@_hasball": "COR",
                "@_down": "1",
                "@_togo": "10",
                "@_spot": "COR40",
                "@_context": "V,1,10,V40",
                "@_playid": "0,1,0",
                "@_tokens": "CMT:Cornell wins the toss and defers",
                "@_text": "Cornell wins the toss and defers",
                "@_newcontext": "V,1,10,V40",
                "#index": 0
            },
            {
                "@_hasball": "COR",
                "@_down": "1",
                "@_togo": "10",
                "@_spot": "COR40",
                "@_context": "V,1,10,V40",
                "@_playid": "0,2,1",
                "@_tokens": "SPOT:V,V40,N",
                "@_text": "COR ball on COR40.",
                "@_newcontext": "V,1,10,V40",
                "#index": 1
            },
            {
                "@_hasball": "COR",
                "@_down": "1",
                "@_togo": "10",
                "@_spot": "COR40",
                "@_context": "V,1,10,V40",
                "@_playid": "0,3,2",
                "@_type": "K",
                "@_tokens": "KO:9A,H00 TB:",
                "@_text": "Null, Nickolas kickoff 60 yards to the PENN0, touchback.",
                "@_newcontext": "H,1,10,H20",
                "#index": 2,
                "childCount": 1,
                "p_ko": {
                    "@_vh": "V",
                    "@_name": "Blabla",
                    "@_gain": "60",
                    "@_result": "T",
                    "#index": 0
                }
            },
            {
                "@_hasball": "PENN",
                "@_down": "1",
                "@_togo": "10",
                "@_spot": "PENN20",
                "@_context": "H,1,10,H20",
                "@_playid": "1,1,3",
                "@_tokens": "SPOT:H,H20,Y",
                "@_text": "PENN ball on PENN20.",
                "@_newcontext": "H,1,10,H20",
                "#index": 4
            }
        ],
        "drivestart": {
            "@_poss": "H,H20,15:00",
            "@_vh": "H",
            "@_spot": "H20",
            "@_clock": "15:00",
            "@_driveindex": "1,2",
            "#index": 3
        }
    }
}
```

I made all code changes and tests under PR #172, I will wait for your comments!

Feel free to ask me anything. Thanks!

**Comment by amitguptagwl** [comment]
our main concern is to maintain index of array items or object as well?

**Comment by gvillo** [comment]
Hi!, yeah I know the main purpose of this library is not to keep index of arrays/objects of source xml, but this would be very useful for complex XML like my example (also to re build to JSON from complex a XML, we could add support to JSON to XML parser later). 

Of course, the idea is to enable this feature using a boolean option (like I did on my PR, if you don't like the prop names that I set, changing names is fine for me). 

I've added PerfTest with this feature enabled to measure it, the performance drop is like 10%, not bad. 

WDYT?

**Comment by amitguptagwl** [comment]
The reason I asked is that the order can be maintained in an array. So if we don't want to aim objects, we probably don't need index property.

**Comment by gvillo** [comment]
It's not possible to maintain the order in a array for an football xml, let me try to explain it with a better example, this is a extended qtr of an XML (I removed all attributes to avoid confusions)

```xml
<qtr number="1" text="1st">
   <play ...></play>
   <play ...></play>
   <play ...>
     <p_ko ...></p_ko>
   </play>
   <drivestart ....></drivestart>
   <play ...></play>
   <play ...></play>
   <score ...></score>
   <drivesum></drivesum>
   <play ...></play>
   <drivestart ...></drivestart>
   <play ...></play>
   <play ...></play>
   <score ...></score>
   <drivesum ...></drivesum>
   <play ...></play>
</qtr>
```

So, inside of a `qtr` node there are 4 diff tags (`play`, `drivestart`, `drivesum` and `score), when you parse this xml, this will create a qtr obj, with 4 prop arrays inside of it. it's impossible to maintain the order (if you look at my example on my first post, the drivestart has #index: 3, because it's the 4th childnode of qtr.

So parsed JSON will be like this:

```json
{
    "childCount": 1,
    "qtr": {
        "#index": 0,
        "childCount": 5,
        "play": [
            {
                "#index": 0
            },
            {
                "#index": 1
            },
            {
                "#index": 2,
                "childCount": 1,
                "p_ko": {
                    "#index": 0
                }
            },
            {
                "#index": 4
            },
            {
                "#index": 5
            },
            {
                "#index": 7
            },
            {
                "#index": 8
            },
            {
                "#index": 10
            },
            {
                "#index": 11
            },
            {
                "#index": 14
            }
        ],
        "drivestart": [{
            "#index": 3
        },
        {
            "#index": 9
        }],
        "drivesum": [{
            "#index": 7
        },
        {
            "#index": 13
        }],
        "score": [{
            "#index": 6
        },
        {
            "#index": 12
        }]
    }
}
```
 
Using those indexes I can understand what happened on the game, otherwise, I just have 4 (nonsense/unsorted) arrays inside of a quarter.

But I missed a prop in the library can do something like this (or keep all childnodes in the same array to maintain order) or you figure out a better approach to do this, it would be great! This was the best solution I could find.

Thanks for taking time to look at this.

**Comment by amitguptagwl** [comment]
hmm.. I understand your concern now. Let me go through your implementation. Tell me, when did you practically need it?

**Comment by gvillo** [comment]
Great!, mmm I need this particularly on this qtr array, but I couldn't find a way to restrict appending `childCount` and `index` to others nodes. Anyway since you have to explicit enable this feature doesn't matter to me, it's ok to have childCount and index in all nodes. The only way to append those props (to keep the original -xml- index order) is when the library is going thru (sequentially) every node and counting, that's what I did.

Also I need this for self tags, so I added those changes to my PR #172. 

Probably naming options are kinda confusing, feel free to suggest different naming, I am a native spanish speaker, my 2nd language is english.

**Comment by domborys** [comment]
Hi,
I have encountered the same issue while parsing some GML files. This is the problematic part:

```xml
<gml:Curve>
	<gml:segments>
		<gml:LineStringSegment>
			<gml:pos>8.72475070598000E+0005 2.27947125583450E+0005</gml:pos>
			<gml:pos>8.72474827387390E+0005 2.27920615627330E+0005</gml:pos>
		</gml:LineStringSegment>
		<gml:ArcString>
			<gml:pos>8.72474827387390E+0005 2.27920615627330E+0005</gml:pos>
			<gml:pos>8.72468488023918E+0005 2.27916040807065E+0005</gml:pos>
			<gml:pos>8.72462626321960E+0005 2.27921213520070E+0005</gml:pos>
		</gml:ArcString>
		<gml:LineStringSegment>
			<gml:pos>8.72462626321960E+0005 2.27921213520070E+0005</gml:pos>
			<gml:pos>8.72463133010730E+0005 2.27946547958260E+0005</gml:pos>
		</gml:LineStringSegment>
		<gml:ArcString>
			<gml:pos>8.72463133010730E+0005 2.27946547958260E+0005</gml:pos>
			<gml:pos>8.72468883023631E+0005 2.27951358239362E+0005</gml:pos>
			<gml:pos>8.72475070598000E+0005 2.27947125583450E+0005</gml:pos>
		</gml:ArcString>
	</gml:segments>
</gml:Curve>
```

This code represents a curve in a shape of a running track. The gml:LineStringSegment elements represent parts of the curve which are line segments. The gml:ArcString elements represent parts which are arcs. The coordinates of the endpoints are inside the gml:pos elements.

The order of the gml:LineStringSegment and gml:ArcString elements is meaningful - first there is a straight line, followed by an arc, followed by another straight line, followed by another arc.

I want to draw this shape, so I need to know the order of these elements as they appear in the XML document. However, when I use Fast XML Parser this information is lost:

```javascript
{
    "gml:Curve": {
        "gml:segments": {
            "gml:LineStringSegment": [
                {
                    "gml:pos": [
                        "8.72475070598000E+0005 2.27947125583450E+0005",
                        "8.72474827387390E+0005 2.27920615627330E+0005"
                    ]
                },
                {
                    "gml:pos": [
                        "8.72462626321960E+0005 2.27921213520070E+0005",
                        "8.72463133010730E+0005 2.27946547958260E+0005"
                    ]
                }
            ],
            "gml:ArcString": [
                {
                    "gml:pos": [
                        "8.72474827387390E+0005 2.27920615627330E+0005",
                        "8.72468488023918E+0005 2.27916040807065E+0005",
                        "8.72462626321960E+0005 2.27921213520070E+0005"
                    ]
                },
                {
                    "gml:pos": [
                        "8.72463133010730E+0005 2.27946547958260E+0005",
                        "8.72468883023631E+0005 2.27951358239362E+0005",
                        "8.72475070598000E+0005 2.27947125583450E+0005"
                    ]
                }
            ]
        }
    }
}
```

In this JSON all the LineStringSegments end up in one array and the ArcStrings in another one.

It would be wonderful if a feature such as proposed by gvillo was added.

**Comment by gvillo** [comment]
I made a PR #172, let me know if it's ok, I will solve conflicts later.

**Comment by amitguptagwl** [comment]
@gvillo Thanks a lot for your effort. I have started a separate thread to come up with a planned structure so that any change in output structure can be avoided in the future.

**Comment by gvillo** [comment]
Nice @amitguptagwl this is the main issue now #244

**Comment by amitguptagwl** [comment]
check v4 with `preserveOrder` option. Please create a new issue if that doesn't fulfill the purpose,
