### ISSUE TITLE
 react native access value 

### ISSUE THREAD

**Issue by iamir4g** [NaturalIntelligence/fast-xml-parser#174]
hi i'm new in react and react native pls help me i post request with axios and get xml respons 
i use this library to pars XML to JSON 
this is may code :
 ```
if( parser.validate(res.data) === true) { //optional (it'll return an object in case it's not valid)
                var jsonObj = parser.parse(res.data,options);
                var bb = JSON.stringify(jsonObj)
                console.log(`aaaa : ${bb}`)
            }
```
and this is my respose after convert : 
`aaaa : {"soap:Envelope":{"soap:Body":{"AuthenticateUserResponse":{"AuthenticateUserResult":false,"Token":""}}}}`  
now i want to access 'AuthenticateUserResult' and if is true have token access 'Token'
how to access value of attribute??

and one more question 
how to convert for example strips the xml namespace prefix. E.g <foo:Bar/> will become 'Bar' ??

thank !

**Comment by amitguptagwl** [comment]
Don't be confused with how should it work in react. Just think how should it work in vanilla js.

```js
aaaa["soap:Envelope"]["soap:Body"]["AuthenticateUserResponse"]["AuthenticateUserResult"]
```
