### ISSUE TITLE
Attributes are not correctly parsed back to json

### ISSUE THREAD

**Issue by mlapeyre3** [NaturalIntelligence/fast-xml-parser#177]
### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Hello, I do not understand why my attributes (identified with @_) are not convert back to attributes when moving back to .json :(
See the sample below.
Thank you very much for your help!

### Input
```
<?xml version="1.0" encoding="UTF-8"?>
<Test attributeA="this is a test for attribute A" attributeB="this is a test for attribute B">
  <Author type="test">
    <Name>John Doe</Name>
    <LangID required="false">en</LangID>
  </Author>
</Test>
```

### Code
```js
const options = {
  attributeNamePrefix : "@_",
  attrNodeName: false,
  textNodeName : "#text",
  ignoreAttributes : false,
  parseNodeValue : true,
  parseAttributeValue : true,
};

const jsonOptions = {
  attributeNamePrefix : "@_",
  attrNodeName: false,
  textNodeName : "#text",
  ignoreAttributes : false,
  format: true,
  indentBy: "  ",
  supressEmptyNode: false,
};

const json  = parserXml.parse(xmlInput, options);
const xmlOutput  = parserJson.parse(json, jsonOptions);
```

### Output
```
<Test><@_attributeA>this is a test for attribute A</@_attributeA><@_attributeB>this is a test for attribute B</@_attributeB><Author><@_type>test</@_type><Name>John Doe</Name><LangID>en<@_required>false</@_required></LangID></Author></Test>
```

### expected data
```
<?xml version="1.0" encoding="UTF-8"?>
<Test attributeA="this is a test for attribute A" attributeB="this is a test for attribute B">
  <Author type="test">
    <Name>John Doe</Name>
    <LangID required="false">en</LangID>
  </Author>
</Test>
```
**Would you like to work on this issue?**
- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
I'll check it on weekend.

**Comment by mlapeyre3** [comment]
Hello @amitguptagwl,
Any news on this issue? Have you been able to reproduce the error?
Thanks!

**Comment by amitguptagwl** [comment]
nope.. sorry I couldn't give the time to this yet. Will update you.

**Comment by amitguptagwl** [comment]
I found that you're passing the `jsonOptions` at the time of parsing the js object. You should pass it at the time of building the parser instance.

```js
<Test attributeA="this is a test for attribute A" attributeB="this is a test for attribute B">
  <Author type="test">
    <Name>John Doe</Name>
    <LangID required="false">en</LangID>
  </Author>
</Test>
```

**Comment by mlapeyre3** [comment]
Thanks I did not see the difference with the xml parser!

**Comment by amitguptagwl** [comment]
XML parser, currently, is just a function. You don't build its object. Hence, you need to pass the options, every time you call it. However, in the future, we're planning to convert it into a class as js2xml parser which can boost its performance.
