### ISSUE TITLE
Regression in tagValueProcessor introduced in 3.12.19

### ISSUE THREAD

**Issue by jagregory** [NaturalIntelligence/fast-xml-parser#178]
### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Code
```js
const fxp = require("fast-xml-parser");
const p = new fxp.j2xParser({ tagValueProcessor: v => v.replace('a', 'b') });
p.parse({ "value": 123 });
```

### Output

3.12.18
```xml
<value>123</value>
```

3.12.19
```
TypeError: v.replace is not a function
```

### expected data
```xml
<value>123</value>
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by jagregory** [comment]
I just noticed the comment in the readme `(broken: tagValueProcessor will receive the original value instead of string always)`. If this is a known issue, the release shouldn't have been a patch version increase, as it includes breaking changes which any consumers with a `^` version (npm's default) will receive.

**Comment by amitguptagwl** [comment]
Apologies for the breaking change and wrong place update in version number. I believe nothing can be done at this moment but I'll keep that in mind for any future release.

On the other side, I'm thinking to handle it gracefully so that date and string both cases can be handled without explicit check in `tagValueProcessor` which looks ugly. However, I have no idea what would be the better approach so will try that on the weekend.

**Comment by amitguptagwl** [comment]
working on the approach of avoiding to check/convert the value passed to `tagValueProcessor`. I was thinking if the default type should be string only. So the date would be passed in string format by default. However, if `parseNodeValue : true` is set then the value will be in its original type.

Let me know how would it be useful for your package.
