### ISSUE TITLE
Regression in xmlstr2xmlnode.js version 3.12.19

### ISSUE THREAD

**Issue by maleetz** [NaturalIntelligence/fast-xml-parser#179]
Likely a result of https://github.com/NaturalIntelligence/fast-xml-parser/commit/b46db1bd5f5d404374cecaf721c66364e2483a98, fast-xml-parser can hang depending on the xml input.

### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Code
```js
const xmlParser = require( 'fast-xml-parser')
xmlParser.parse('<elem longattributename="1" long_attribute_name = "0" />');
```

### Output

Process hangs on the regexp parsing here: https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/xmlstr2xmlnode.js#L81
### expected data

Version 3.12.16 returns:
`{ elem: '' }`

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Thanks for reporting. I'll check the issue on this weekend.

**Comment by amitguptagwl** [comment]
Yes. There was an approx 8-10% performance degradation after the mentioned commit. and it impacted badly in case of long attributes. I'm reverting the mentioned commit until I find some better solution for that.

**Comment by maleetz** [comment]
Sounds great. Thank you!

**Comment by amitguptagwl** [comment]
done
