### ISSUE TITLE
Self-closing tag is a non-text node whereas empty tag is a text node

### ISSUE THREAD

**Issue by gxa** [NaturalIntelligence/fast-xml-parser#18]
`<tag id="foo"/>` and `<tag id="foo"></tag>` are treated differently. To parse the attributes in the first case you need to specify `ignoreNonTextAttr: false` and for the second case `ignoreTextAttr:false`. Also, the second tag will have a `#text` field and the first one won’t. I think this behaviour doesn’t match [the XML spec](https://www.w3.org/TR/REC-xml/#sec-starttags), as the two should be equivalent:
>Empty-element tags may be used for any element which has no content, whether or not it is declared using the keyword EMPTY. For interoperability, the empty-element tag SHOULD be used, and SHOULD only be used, for elements which are declared EMPTY.
>
>Examples of empty elements:
>
> `<IMG align="left"`
> `src="http://www.w3.org/Icons/WWW/w3c_home" />`
> `<br></br>`
> `<br/>`
>

**Comment by amitguptagwl** [comment]
I'll be back to code from coming Monday. So will check the issue in few
days.

Thanks for raising the issue.

**Comment by amitguptagwl** [comment]
@gxa Though the both tags should be treated equally, in the parser user can decide weather he wants to ignore attributes of one type or of both type. So if many users of parser library feel that I should make it one, I'll do that.

`#text` is the field when you don't ignore attributes and want to parse the tag with attribute as well as tag value. Eg `<tag attr="val">textval</tag>`. 

Let me know if you have any other doubt.

**Comment by amitguptagwl** [comment]
Please raise the other issue if you still have any doubt.
