### ISSUE TITLE
Remove nimnjs dependency

### ISSUE THREAD

**Issue by fabiospampinato** [NaturalIntelligence/fast-xml-parser#183]
It looks like `nimnjs` is only imported in tests, [here](https://github.com/NaturalIntelligence/fast-xml-parser/blob/668f75b11fefc7cc9f7f7f79bd3bf200231b7e7b/spec/nimndata_spec.js#L2), but it is not a _dev_ dependency, so can it be defined as a dev dependency rather than regular dependency?

**Comment by amitguptagwl** [comment]
sure, let me check.

**Comment by fabiospampinato** [comment]
Thanks!
