### ISSUE TITLE
feat(xml-export) The xml export should add the xml-declaration. (optional)

### ISSUE THREAD

**Issue by Domvel** [NaturalIntelligence/fast-xml-parser#184]
Currently the xml-export does not add the first line xml-declaration (header) like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

or

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

It's not hard for me to add this string before writing the xml file.
But I would prefer an official way.

Suggestion for the option props (default values): 

```js
{
  declarationXmlHeader: false,
  standaloneXmlHeader: false
}
```

But I'm not the xml pro. I'm sure you have the better idea.

`fast-xml-parser` version: `3.12.20`

**Comment by amitguptagwl** [comment]
There can be various attributes of XML-declaration. and their value may depend, like encoding. You may want to save the XML with different char encoding. Hence it is suggested if you prepend it to the parser output.

**Comment by Domvel** [comment]
The parser could just read the header if present and stores it in the json (maybe optional). For the first step this is only a simple string parsing and key-value assignment, like it already works today. Nothing special. No interpretation of the encoding etc. (note this in the docs.)

The header declaration in the json can be edited by the user manually. And the xml export just build the header by the header attribute from the json. Simple `'<?xml key=value ?>'`. 

Options: 

```js
{
  declarationXmlHeader: false
}
```
Default: false to keep the current behavior. If this is true, the parse included it into the json and the xml serializer handles it.

```json
"?xml": {
  "version": "1.0",
  "encoding": "utf-8"
}
```
Or just `?` or set by the user.

| Attribute | Description |
| --- | --- |
| version | Required! Default `1.0` is there another version? Who cares, the user can modify it. |
| encoding | Default: `UTF-8` |
| standalone | Default: unset (not exported). Values: `'no'`, `'yes'` |

Workaround:
I just add the header as string.
```js
xml = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n${xml}`;
```

Just a suggestion, be free to close.

**Comment by amitguptagwl** [comment]
A user need to add header information as js object or as string. So I don't see much significance to add it to the parser.

**Comment by amitguptagwl** [comment]
closing the issue. please feel free to reopen it. We can do more brainstorming on this.

**Comment by udivankin** [comment]
@amitguptagwl imagine a use case when you need to parse, change something in the object, then build an XML and save in a way that minimizes the diff between original and new file. 
Correctly parsing and building declarations are super helpful with this scenario.

**Comment by amitguptagwl** [comment]
@udivankin with the recent version, you can parse XML into js object with XML declaration, do the changes in the object and get back the XML declaration. Even if you create the object yourself, you can add necessary info to add the declaration.
