### ISSUE TITLE
feat(xml-parser) Option for, do not unwrap single values. Keep arrays.

### ISSUE THREAD

**Issue by Domvel** [NaturalIntelligence/fast-xml-parser#185]
fast-xml-parser parses the xml in an intelligent way. This is awesome. See these examples:

---

XML with **multiple** values:
```xml
<complies>
  <standard>STD1</standard>
  <standard>STD2</standard>
</complies>
```
in json:
```json
{
    "complies": {
        "standard": [
            "STD1",
            "STD2"
        ]
    }
}
```

---

XML with **single** value:
```xml
<complies>
  <standard>STD1</standard>
</complies>
```

in json:
```json
{
    "complies": {
        "standard": "STD1"
    }
}
```

---

My feature-request is to add an option to force keeping the array also for single values to normalize the whole xml. An option with the default value `false` to keep the current behavior as prefered behavior. 

The new option could be named `doNotUnwrapSingleValue` or something like this. The export for single values should result in this xml:

```json
{
    "complies": {
        "standard": ["STD1"]
    }
}
```

Why?
Because every node has the same structure.

Note:
This does not affect the root node. The root node never have multiple values.

What do you think about my suggestion?

`fast-xml-parser` version: `3.12.20`

**Comment by Domvel** [comment]
I close it, because it's not important at this moment. I like the current behavior. 
But feel free to re-open this issue if you want this feature.

**Comment by amitguptagwl** [comment]
I believe its a good idea. Need to cross validate it against previously raised requirements

#181 #135
