### ISSUE TITLE
Should parse long number string as string instead of number

### ISSUE THREAD

**Issue by ShinyChang** [NaturalIntelligence/fast-xml-parser#187]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Root>
  <LongNumberString>420926189200190257681175017717</LongNumberString>
</Root>

```
### Code
```js
const { getTraversalObj, convertToJson } = require('fast-xml-parser');

const options = { attributeNamePrefix: '$', ignoreAttributes: false };

const x2j = xml => convertToJson(getTraversalObj(xml, options), options);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<Root>
  <LongNumberString>420926189200190257681175017717</LongNumberString>
</Root>
`;

const json = x2j(xml);

console.log(json);

```

### Output

```
{ Root: { LongNumberString: 4.209261892001902e+29 } }
```
### expected data

```
{ Root: { LongNumberString: "420926189200190257681175017717" } }
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

### Description

I can help to enhance the [parser](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/xmlstr2xmlnode.js#L186-L198) if you think this is correct. 
IMO, the scientific notation can not represent the value in the XML. The type should be **string** if the number string is too long (more than `Number.MAX_SAFE_INTEGER`).

**Comment by amitguptagwl** [comment]
Thanks for the suggestion. Will implement it in a future version.

**Comment by amitguptagwl** [comment]
@ShinyChang please use option `parseTrueNumberOnly : true`

**Comment by JKounter** [comment]
> ```js
> 420926189200190257681175017717
> ```

i am seeing a different response locally vs in dev environment (linux).   Any idea why this would happen?

**Comment by JKounter** [comment]
> @ShinyChang please use option `parseTrueNumberOnly : true`

any idea why a 21 digit string of numbers would parse correctly as a string in windows but into scientific notation as a number in linux while using this?

**Comment by amitguptagwl** [comment]
This library is not using a separate package strnum. So please test your application with latest version and reopen the issue if exist.

**Comment by JoaoXistoLorenz** [comment]
Hello @amitguptagwl! This issue is occurring again. Is there any workaround?

**Comment by amitguptagwl** [comment]
@czarkom I've corrected the typo. @JoaoXistoLorenz Please post the sample code with config and library version.

**Comment by czarkom** [comment]
Thanks for clarification @amitguptagwl! Thing is that this `eNotation` option is not available in `strnumOptions`, so it's not possible to set it while using `X2jOptions` type.
```
type strnumOptions = {
  hex: boolean;
  leadingZeros: boolean,
  skipLike?: RegExp
}
```
I think `eNotation` option should be added there to make it work

**Comment by JoaoXistoLorenz** [comment]
Thanks for answering me @amitguptagwl , my version is 4.0.13!!
![image](https://user-images.githubusercontent.com/80301739/212093074-51116760-5c4e-49ac-8317-991924161769.png)

**Comment by amitguptagwl** [comment]
got you, `eNotation` is missing from the typing. Let me fix that.

**Comment by JoaoXistoLorenz** [comment]
Hello @amitguptagwl , do you have an estimate of when the fix will be released?

**Comment by amitguptagwl** [comment]
I've on health issue right now. So as soon as I recovered. It's a very small change. But ..

**Comment by amitguptagwl** [comment]
Please test with new version now

**Comment by JoaoXistoLorenz** [comment]
Hello @amitguptagwl, still having the problem, my version is 4.0.14

![image](https://user-images.githubusercontent.com/80301739/214054395-44225be3-dfed-429c-9302-0d24b4aeb06d.png)

**Comment by JoaoXistoLorenz** [comment]
Now it's working properly, thank you very much @amitguptagwl !

**Comment by oktawia-kata-dv** [comment]
Thanks for fixing this issue @amitguptagwl , will it be available in a new patch version anytime soon?
