### ISSUE TITLE
Considers closing tag to be valid without closing bracket

### ISSUE THREAD

**Issue by cliffhall** [NaturalIntelligence/fast-xml-parser#188]
In its default configuration (and on your online tool), fast-xml-parser considers `<test></test` to be valid XML. 

### Checklist

* [x] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
input data(one character at a time): `<test></test`

### Code
```js
validateXML(xml) {
   if (!!xml) console.log(xml, parser.validate(xml));
}
```

### Output

```
< {err: {…}}
<t {err: {…}}
<te {err: {…}}
<tes {err: {…}}
<test {err: {…}}
<test> {err: {…}}
<test>< {err: {…}}
<test></ {err: {…}}
<test></t {err: {…}}
<test></te {err: {…}}
<test></tes {err: {…}}
<test></test true
```
### expected data

```
.
.
.
<test></test {err: {…}}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by cliffhall** [comment]
Output from my console as I run text through `parser.validate()`
![Screen Shot 2019-09-17 at 3 18 01 PM](https://user-images.githubusercontent.com/871933/65072649-50aac480-d95f-11e9-87f7-743533a37683.png)

Your online validator showing the same result: 
![Screen Shot 2019-09-17 at 3 09 08 PM](https://user-images.githubusercontent.com/871933/65072648-50aac480-d95f-11e9-902b-b533581411df.png)

**Comment by cliffhall** [comment]
For anyone running into this issue, here is the workaround I came up with for now:

`const valid = !!xml && xml.trim().endsWith('>') && (parser.validate(xml) === true);`

**Comment by amitguptagwl** [comment]
@cliffhall it is already mentioned that the validator and XML parser both are separator to achieve higher performance. If the XML is not provided from trusted source then it must be validate first.

**Comment by cliffhall** [comment]
What are you saying? It reports invalid xml as being valid. Performance is no excuse for that! You see that a simple open and close tag with missing closing angle bracket causes the parser to report valid, as well as the online tool. That fails it’s basic purpose. If there is some other approach I am supposed to take to validate the xml please explain. But e parser and validated do not appear to be separated - I literally used the method parser.validate().

**Comment by amitguptagwl** [comment]
@cliffhall I'm not saying that you should not use the validator but you should use it when you need. If in your case it is always required, create a wrapper. You can publish that as a separate library, or create a PR and add it to https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/parser.js

**Comment by cliffhall** [comment]
Look, I do need it, it is always required, and it is broken. I’ve posted a workaround for any other poor souls who find themselves washed up in this island, but ultimately you just need to fix the bug. An xml parser that calls invalid xml valid is useless. Closing this bug and ignoring the problem won’t make it go away it will only serve to show others that you do not care about the quality of your code.

**Comment by amitguptagwl** [comment]
there were some misunderstandings in our conversation. Apologies not to understand it in the first place. However, I have fixed the bug you reported. Thanks for reporting
