### ISSUE TITLE
Parse <![CDATA[0]]> to ""

### ISSUE THREAD

**Issue by vlasovigora** [NaturalIntelligence/fast-xml-parser#19]
Hello.
I get the error that this xml tag
<section><![CDATA[0]]></section>
is parsed to 
section=""
Supposed to be 
section=0
![image 11](https://user-images.githubusercontent.com/9316087/28584688-46af8b4e-7176-11e7-9e83-8e90ac9230db.png)
![image 12](https://user-images.githubusercontent.com/9316087/28584689-46b07022-7176-11e7-99f4-bda11c63f634.png)

**Comment by amitguptagwl** [comment]
I'm sorry. I'm not able to understand your concern. Do you mean to say that you are facing while parsing XML with CDATA?
Please let me know if you have already checked that it valid XML.

**Comment by vlasovigora** [comment]
Hello. Thank you for your fast reply.
I created gist with problematic xml https://gist.github.com/vlasovigora/33362483b645d7066c64c9f933419e01
I also tried to validate it by several online xml validators and it is ok.
also this code fastXmlParser.validate(stringWithThisXML) returns true.

In the debugger I see this https://snag.gy/QeOW98.jpg
And after parsing I see this https://snag.gy/L5qcZB.jpg

I think that 'section' property shoub be 0, but it is "".

**Comment by amitguptagwl** [comment]
This is not the issue with CDATA. try a tag with value 0. You'll get the same result. Try with `textNodeConversion : false ` and update me. I may require to fix it otherwise.

**Comment by amitguptagwl** [comment]
I have fixed the bug. Test with latest.

**Comment by vlasovigora** [comment]
It works good. Thank you for quick fix.

**Comment by Lelo2000** [comment]
Hello,
I think I have the same error again or I oversaw an option. But when I try to parse:
`const xmlData = "
    <a>
        <![CDATA[0]]>
    </a>";`
   with this options:
   `ignoreAttributes: false,
  attributeNamePrefix: "@@",
  cdataPropName: "##cdata",
  commentPropName: "#comment",
  allowBooleanAttributes: true,
  parseAttributeValue: true,
  format: true,
  textNodeConversion: false,
  indentBy: "\t",`
  
I get the following:
`
{ a: { '##cdata': '' } }
`
But I would expect something like this:
`{ a: { '##cdata': '0' } }`

I saw that the issue should been solved. I am on Version 4.0.0-beta.2 of the npm package.

**Comment by amitguptagwl** [comment]
The value of CDATA should not parsed. I have fixed the bug. And will publish it soon.

**Comment by amitguptagwl** [comment]
Please check with v4.0.0-beta.3
