### ISSUE TITLE
Streams support

### ISSUE THREAD

**Issue by bulion121** [NaturalIntelligence/fast-xml-parser#193]
Does this package supports streams? My case is that I download large xml file to my server and then I need to translate it to JSON it would be awesome if I could just pipe response to parser and have my json file. If package supports streams can you give me some examples? It's hard for me to find any

**Comment by amitguptagwl** [comment]
Unfortunately no. As this package use regex which are applied on prebuilt string, it doesn't support streams. However, it is in plan. But can't promise any date right now.

**Comment by bulion121** [comment]
Ok thanks for your answer
