### ISSUE TITLE
Parse true numbers sometimes ignore float number

### ISSUE THREAD

**Issue by xiaoyu-tamu** [NaturalIntelligence/fast-xml-parser#196]
### Checklist

* [ x] Have you asked your question on Stackoverflow or similar forum?
* [ x] Are you running the latest version?
* [ x] Have you included sample input, output, error, and expected output? 
* [ x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input

https://github.com/NaturalIntelligence/fast-xml-parser/blob/ea25808a7aef39e51f2439dd73934d54ac49d3b7/src/xmlstr2xmlnode.js#L189-L199

if the node value is "1278.90", javascript praseFloat will return 1278.9 which cause parseTrueNumberOnly check fail since "1278.9" !== "1278.90". 

### Code
```ts
Include the code being used for parsing
const XML_OPTIONS: xml.X2jOptions = {
  attrValueProcessor: identity,
  tagValueProcessor: identity,
  allowBooleanAttributes: true,
  arrayMode: true,
  attrNodeName: false,
  attributeNamePrefix: "",
  cdataPositionChar: "\\c",
  cdataTagName: false,
  stopNodes: [],
  parseTrueNumberOnly: true,
  ignoreAttributes: false,
  ignoreNameSpace: true,
  localeRange: "",
  parseAttributeValue: true,
  parseNodeValue: true,
  textNodeName: "Value",
  trimValues: true
};
```

### Output

return string "1278.90"
### expected data

return number 1278.9 
**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Fixed. Not published to npm yet.
