### ISSUE TITLE
Unexpected empty array elements added

### ISSUE THREAD

**Issue by dorev** [NaturalIntelligence/fast-xml-parser#199]
Working on a project using the MusicXML format, I am parsing the `xmlFile` provided below and unexpected empty elements appeared in the resulting object. 
[Here's a link to the repository of this project](https://github.com/dorev/dryad/blob/master/src/_main.ts)

![image](https://user-images.githubusercontent.com/49461612/68265496-36659c80-001a-11ea-83fe-a0238b76f138.png)

I guess there might be something I'm missing in the options but I've tried a lot of things and I'm currently stuck. The parsing is done with the following options : 

    const optionsXmlToJson = {
      attributeNamePrefix : "",
      attrNodeName: "attr",
      textNodeName : "#text",
      ignoreAttributes : false,
      allowBooleanAttributes : true,
      parseNodeValue : true,
      parseAttributeValue : true,
      trimValues: true,
      arrayMode: false,
    };

    const xmlFile: string = `<score-partwise version="3.1">
    <part-list>
      <score-part id="P1">
        <part-name>Music</part-name>
      </score-part>
    </part-list>
    <part id="P1">
      <measure number="1">
        <attributes>
          <divisions>1</divisions>
          <key>
            <fifths>0</fifths>
          </key>
          <time>
            <beats>4</beats>
            <beat-type>4</beat-type>
          </time>
          <clef>
            <sign>G</sign>
            <line>2</line>
          </clef>
        </attributes>
        <note>
          <pitch>
            <step>C</step>
            <octave>4</octave>
          </pitch>
          <duration>1</duration>
          <type>quarter</type>
        </note>
        <note>
          <pitch>
            <step>C</step>
            <octave>4</octave>
          </pitch>
          <duration>1</duration>
          <type>quarter</type>
        </note>
      </measure>
    </part>
    </score-partwise>`;

**Comment by amitguptagwl** [comment]
When I parse your XML using the online demo tool I get following result;

```json
{
    "score-partwise": {
        "part-list": {
            "score-part": {
                "part-name": "Music"
            }
        },
        "part": {
            "measure": {
                "attributes": {
                    "divisions": "1",
                    "key": {
                        "fifths": "0"
                    },
                    "time": {
                        "beats": "4",
                        "beat-type": "4"
                    },
                    "clef": {
                        "sign": "G",
                        "line": "2"
                    }
                },
                "note": [
                    {
                        "pitch": {
                            "step": "C",
                            "octave": "4"
                        },
                        "duration": "1",
                        "type": "quarter"
                    },
                    {
                        "pitch": {
                            "step": "C",
                            "octave": "4"
                        },
                        "duration": "1",
                        "type": "quarter"
                    }
                ]
            }
        }
    }
}
```

It doesn't have any empty value. So can you please re-confirm?

**Comment by dorev** [comment]
I did retry a few times and it boils down to this : whenever I have two identical elements in the xml, it adds 3 more empty ones
![image](https://user-images.githubusercontent.com/49461612/68506116-dc8dee00-0236-11ea-95f1-a6154516c342.png)
![image](https://user-images.githubusercontent.com/49461612/68506125-e0ba0b80-0236-11ea-8ba3-884e585874f4.png)

Maybe something gets mixed up when I run it through webpack.
Maybe I got the options wrong in a conflicting way. What are the options of the demo? All default?

**Comment by amitguptagwl** [comment]
```js
            function buildParsingConfig(){
                var config = {
                    attributeNamePrefix : "@_",
                    attrNodeName: $("#attrNodeName").prop("checked") ? "@" : false,
                    textNodeName : "#text",
                    ignoreAttributes : $("#ignoreAttributes").prop("checked"),
                    ignoreNameSpace : $("#ignoreNameSpace").prop("checked"),
                    parseNodeValue : $("#parseNodeValue").prop("checked"),
                    parseAttributeValue : $("#parseAttributeValue").prop("checked"),
                    allowBooleanAttributes: $("#allowBooleanAttributes").prop("checked"),
                    trimValues: $('#trimValues').prop("checked"), //Trim string values of tag and attributes
                    decodeHTMLchar: false,
                    cdataTagName: $("#cdataTagName").val() === "" ? false : $("#cdataTagName").val(),
                    cdataPositionChar: "\\c",
                    localeRange : $("#localeRange_v").val(),
                    //arrayMode : $("#arrayMode").prop("checked")
                };
                return config;
            }
```

**Comment by mbrucher** [comment]
I noticed the same when parsing data from http://overpass-api.de/api/interpreter?data=%5Bbbox%5D;node%5B%22amenity%22~%22pub%7Crestaurant%7Cbar%22%5D;out;&bbox=7.0,50.6,7.3,50.8
The xml nasically, anything below nodes gives empty strings with the default options and the options given in the main page.

**Comment by amitguptagwl** [comment]
@dorev any update?

**Comment by dorev** [comment]
No sorry, I haven't found anything yet.
Just working around it for the moment.

**Comment by amitguptagwl** [comment]
Please ensure that you're using the latest version of the library. I'm closing this issue. But you can reopen it if you find something wrong.
