### ISSUE TITLE
Incorrect value parsing

### ISSUE THREAD

**Issue by hazaart** [NaturalIntelligence/fast-xml-parser#200]
In my XML I have a value "34100000000000000001". After parsing the value is 34100000000000000000 of datatype number.

    const json = convertToJson(getTraversalObj(data), { parseNodeValue: false, });

Notice that I'm already passing parseNodeValue 'false' but the library is ignoring it. Regardless of the datatype now the value is being changed by the library.

I am officially switching to x2js library after many issues with this one.

**Comment by amitguptagwl** [comment]
@hazaart thanks for reporting this issue. I'll check this on this weekend and fix it. We'll be glad if you can tell us what other issues you're facing. It'll give us the chance for improvement.

Please check the performance and output of other library before switching. Many libraries give wrong parsing output in case of big XML input. Choice is yours.

**Comment by amitguptagwl** [comment]
@hazaart as the number you have given is out of safe range, you're supposed to use `parseTrueNumberOnly: true`. It is not a bug but right options are not set.
