### ISSUE TITLE
Option to ignore tag pairing

### ISSUE THREAD

**Issue by shasank** [NaturalIntelligence/fast-xml-parser#206]
I would like to use fast-xml-parser for html validation. But it enforces stringent XHTML rules like tags pairing for `<input> and <br>` tags.
Is there a way I can skip the pairing part and use for HTML validation?

Thanks!

**Comment by amitguptagwl** [comment]
If your HTML has strictly self-closing tags and no void/empty tags then you can use this library. The reason not to support void/empty tags is that this library is generic. However, we can think to provide the list of void/empty tags for HTML validation

```js
options.voidTags=[ "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr" ];
```

**Comment by amitguptagwl** [comment]
done. please check v4.0.0-beta.2

**Comment by queejie** [comment]
Thanks for this software!  I'm using v4.0.7 (@latest) to validate HTML as a user enters it, as a "linter" in CodeMirror 6.  It flags img tags without closing slashes as errors.   Unfortunately, the slash is removed by HTML tidy formatting on the server side.

I've provided the voidTags list:
````
const { XMLValidator } = require('fast-xml-parser');
...
const options = {
	allowBooleanAttributes: true,
	voidTags: ['br', 'embed', 'hr', 'img', 'input', 'source', 'track']
	};
const result: true | ValidationError = XMLValidator.validate(content, options);
````

**Comment by queejie** [comment]
Oh, I see from issue #406 that it is not voidTags, but **unpairedTags**, and possibly **supressEmptyNode** is also required.
````
const options = {
	allowBooleanAttributes: true,
	supressEmptyNode: true,
	unpairedTags: ['br', 'embed', 'hr', 'img', 'input', 'source', 'track']
	};
````
