### ISSUE TITLE
Multiple root elements validate successfully

### ISSUE THREAD

**Issue by NorbertHuethmayr** [NaturalIntelligence/fast-xml-parser#207]
### Checklist

* [x] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
XML structures must always have a single root element. If there are multiple, it is not valid. The validator class does not detect this problem.

### Expected data
I would expect a descriptive error message when an XML with multiple root-nodes is validated.

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by NorbertHuethmayr** [comment]
Hi Amit,

if you give me a hint on where to start, I could get going.

**Comment by amitguptagwl** [comment]
Probably, you can maintain a stack. push when a tag is found, pop when matching closing tag is found. If the size of the stack reaches to 0 and you still have more tags, it means there are more than 1 root element.
