### ISSUE TITLE
TypeError: Cannot read property 'addChild' of undefined when unvalidated

### ISSUE THREAD

**Issue by rsclarke-vgw** [NaturalIntelligence/fast-xml-parser#208]
### Summary

Given the basic example in the code section below, a `TypeError` is thrown when validation is not performed.

To be robust against malformed input there needs to be a defined contract that either validation will be performed (the `.validate` function internally or default to `true` in the third argument to `parse`).  Or a given API specific exception will be thrown.  Additionally it might need to be explicitly clear that you must validate before calling `.parse` and the documentation reflects this.

The issue occurs when `currentNode` becomes `undefined` at; https://github.com/NaturalIntelligence/fast-xml-parser/blob/42601123b5ef77fe5bcca01e2e0bb12599120e28/src/xmlstr2xmlnode.js#L94  On the next iteration of the loop it falls into the `else` branch for the opening tag and thus attempts to call `addChild` on `currentNode` https://github.com/NaturalIntelligence/fast-xml-parser/blob/42601123b5ef77fe5bcca01e2e0bb12599120e28/src/xmlstr2xmlnode.js#L132

### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Code
```js
const parser = require('fast-xml-parser');
parser.parse("</person><last>e</last>");
```

### Output
```
node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:132
      currentNode.addChild(childNode);
                  ^

TypeError: Cannot read property 'addChild' of undefined
    at Object.getTraversalObj (node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:132:19)
    at Object.exports.parse (node_modules/fast-xml-parser/src/parser.js:19:48)
    at Object.<anonymous> (test.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
I believe the example given on README indicate the need of validation;
```js
if( parser.validate(xmlData) === true) { //optional (it'll return an object in case it's not valid)
    var jsonObj = parser.parse(xmlData,options);
}
```
If it is confusing, we can eloborate more it in documentation.

**Comment by rsclarke-vgw** [comment]
I don't think it's cleat at all, the comment even states it is optional.  There are a number of examples in the README which don't wrap the call to `parse` with validation.

May I ask if there is need for validation why isn't it just the default function as part of `parse`?

**Comment by amitguptagwl** [comment]
Many people don't need validation when they're working on XML provided from trusted resources. There're very fewer users of this library who actually use the validator. Hence, it is optional. Since it impacts performance, it is external.

Being a developer the above code is pretty clear to me. However, I'll add a line in the documentation to clear any confusion.

**Comment by amitguptagwl** [comment]
@rsclarke-vgw I have added the detail on README. So closing this issue. If you fee that the added detail is not sufficient or not clear, fee free to raise a PR to improve it reopen this issue to notify.
