### ISSUE TITLE
attributes not showing up

### ISSUE THREAD

**Issue by chovy** [NaturalIntelligence/fast-xml-parser#211]
`<media:content url="https://thedailyshitter.com/content/images/2019/11/paypal.jpg" medium="image"/>`

I just get `media:content: ""`

This is from an RSS feed.

**Comment by chovy** [comment]
Nevermind. Needed `  ignoreAttributes : false,`

**Comment by dscape** [comment]
This is actually a good issue. Same happened to me. Without any examples it's not obvious, I almost went back to xml2js
