### ISSUE TITLE
how to change the attribute tag name

### ISSUE THREAD

**Issue by cckowin** [NaturalIntelligence/fast-xml-parser#212]
is there any way to change the attribute tag name using this module like xml2js
eg.
`
<test attribute-name="test"></test>
`
to produce a result like this
`
test: {
  attributeName: "test",
}
`

**Comment by amitguptagwl** [comment]
@cckowin we can currently do the alteration in values only. We can think about to change it for both value and names. Or probably a separate name processor. Thanks

**Comment by Tiim** [comment]
A processor for tag and attribute names would also allow for case insensitive xml files, just by using 
`(name) => name.toLowerCase()`.

**Comment by amitguptagwl** [comment]
We can probably reuse `attributeValueProcessor` to return an object where the key represents attribute name. However, in this case, user will lose the feature of parsing attribute value to some object.

**Comment by amitguptagwl** [comment]
https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#transformattributename
