### ISSUE TITLE
Funding for fast-xml-parser

### ISSUE THREAD

**Issue by chrisvxd** [NaturalIntelligence/fast-xml-parser#213]
Hey @amitguptagwl! 👋

Just wanted to reach out about funding your work on `fast-xml-parser`.

@transitive-bullshit and I are both open source maintainers, and we're exploring new ways to make OSS funding a viable source of income.

We're currently looking at building SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

I think `fast-xml-parser` would be a great fit, and I'd love to build a SaaS API on top of it. We'd handle dev, auth, billing and support so you wouldn't have to do anything.

Looking forward to hearing your thoughts! 🙏

**Comment by amitguptagwl** [comment]
Thanks @chrisvxd . I think I need to understand it more. Can you please drop me an email at contact@amitkumargupta.work?

**Comment by chrisvxd** [comment]
Responded via email :)

**Comment by amitguptagwl** [comment]
Sorry, @chrisvxd I have not received any mail yet.

**Comment by chrisvxd** [comment]
Hey @amitguptagwl, have just forwarded again - perhaps it ended up in your junk?

**Comment by amitguptagwl** [comment]
@chrisvxd thanks. Closing this thread as will communicate on direct channel.
