### ISSUE TITLE
Validation of unescaped ampersand

### ISSUE THREAD

**Issue by yoshigev** [NaturalIntelligence/fast-xml-parser#214]
### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input
"<a>x & y</a>"

### Code
```js
xmlParser.validate("<a>x & y</a>")
```
### Output
true (valid XML)

### Expected output
false (invalid XML)

**Would you like to work on this issue?**
- [ ] Yes
- [x] No (sorry...)

## Details
I'm trying to validate a given input string, to check if it is a valid XML.
I've found that if a text node contains an unescaped ampersand, the xmlparser validate it as valid although other XML parser libraries treat it as invalid.

I also tried using the tagValueProcessor parameter as appears in the examples, but the "he" package also treats the ampersand as valid (I guess that in HTML unambiguous ampersands are valid).

Also note that the output is the same regardless of the spaces around the ampersand (i.e., even if the ampersand is ambiguous).

**Comment by amitguptagwl** [comment]
@yoshigev Currently, what causing issue in parsing is being validated by the validator. However, we can check for this. Thanks for reporting.

**Comment by amitguptagwl** [comment]
The change would be published next week.
