### ISSUE TITLE
Grouped attributes with a prefix don't get renamed

### ISSUE THREAD

**Issue by Jasperrr91** [NaturalIntelligence/fast-xml-parser#217]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [X] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input

```xml
<scriptedContentFragments>
	<scriptedContentFragment name="${resource:Achievements_AchievementList_Name}" version="11.1.0.9731">
	</scriptedContentFragment>
</scriptedContentFragments>
```

### Code
_\Note: parserOptions.xml and parserOptions.json are equal to the sample configurations_
```js
const tObj = xmlParser.getTraversalObj(xmlData, parserOptions.xml);
const jsonObj = xmlParser.convertToJson(tObj, parserOptions.xml);
const jsonToXml = new jsonParser(parserOptions.json);
const parsedXml = jsonToXml.parse(jsonObj);
```

### Output

```xml
<scriptedContentFragments>
	<scriptedContentFragment @_name="${resource:Achievements_AchievementList_Name}" @_version="11.1.0.9731">
	</scriptedContentFragment>
</scriptedContentFragments>
```

### expected data

```xml
<scriptedContentFragments>
	<scriptedContentFragment name="${resource:Achievements_AchievementList_Name}" version="11.1.0.9731">
	</scriptedContentFragment>
</scriptedContentFragments>
```

The issues seems to be that if `this.options.attrNodeName` is set (which it is, because the attributes are grouped under the default `attr` key) the entire prefix gets ignored.

**Would you like to work on this issue?**

- [X] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
This works fine for me
```js
const XMLdata = `
      <car>
        <color alpha="7">purple</color>
        <type>minivan</type>
        <registration>2020-02-03</registration>
        <capacity>7</capacity>
      </car>`;

      const options = {
        ignoreAttributes: false,
        attributeNamePrefix: "",
        attributesGroupName:        "@@",
        format: true
      };
      const parser = new XMLParser(options);
      let result = parser.parse(XMLdata);
      console.log(JSON.stringify(result, null,4));

      const builder = new XMLBuilder(options);
      const output = builder.build(result);
      console.log(output);
```

Please reopen the issue if still exists
