### ISSUE TITLE
CDATA parsing error with regular expression as content

### ISSUE THREAD

**Issue by rahulghorpade23** [NaturalIntelligence/fast-xml-parser#22]
Hello, 

I am facing issue while parsing CDATA containing regular expressions as a value. Normal CDATA is parsing correctly but while using regular expressions as a value it returns blank string.  
here is a sample XML for it 

`<?xml version="1.0" encoding="UTF-8"?><sample><![CDATA[test]]></sample><firstchar><![CDATA[^[ ].*$]]></firstchar>`

could you please help to sort it out?

Thanks

**Comment by amitguptagwl** [comment]
I believe the issue is happening because of square bracket. let me check that. thanks to raise it.

**Comment by amitguptagwl** [comment]
Fixed. Please use latest version.

**Comment by rahulghorpade23** [comment]
Thanks for the Fix.
