### ISSUE TITLE
Missing object property "line" in ValidationError type in parser.d.ts

### ISSUE THREAD

**Issue by calebeno** [NaturalIntelligence/fast-xml-parser#221]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
In your `parser.d.ts` file it reads:
```
type ValidationError = {
  err: { code: string; msg: string };
};
```
But since you've added line numbers it should have:
```
type ValidationError = {
  err: { code: string; msg: string, line: number };
};
```
Noticed it because my IDE didn't seem to know it was there.

### Code
```js
Include the code being used for parsing
```

### expected data

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

If you need me to do a MR for it I can do that but figured it was such a small thing you can probably add it to your workflow pretty easily.

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Thanks, @calebeno . I have updated the file. However, feel free to raise PR for a small change even.
