### ISSUE TITLE
value of "0.0" is incorrectly parsed whilst parseNodeValue: true

### ISSUE THREAD

**Issue by izidan** [NaturalIntelligence/fast-xml-parser#228]
test:
`<xml><anything>0.0</anything></xml>` 

expect:
`{"anything": 0}`

current:
`{"anything": "0."}`

**Comment by amitguptagwl** [comment]
@izidan can you please share the list of options you're passing to the parser. Probably `parseTrueNumberOnly: true` should solve your problem.

**Comment by amitguptagwl** [comment]
Closing the issue. Please re-open it if you find it unresolved.

**Comment by izidan** [comment]
here is a test that shows where it fails; please run with jest or jasmine.

> const xml = require('fast-xml-parser');
> const x2jOptions = {
>    attrNodeName: false, attributeNamePrefix: "@", textNodeName: "@", cdataTagName: false,
>    trimValues: true, parseAttributeValue: false, parseNodeValue: true, parseTrueNumberOnly: true,
>    arrayMode: false, ignoreAttributes: false, ignoreNameSpace: false, allowBooleanAttributes: true,
>};
>describe('xml parser', () => {
>    it('correctly parse "0.0" as a number 0', () => {
>        expect(xml.parse("<number>0.0</number>", x2jOptions)).toEqual({ number: 0 });
>    });


> ● xml parser › correctly parse "0.0" as a number 0
> expect(received).toEqual(expected) // deep equality
>    \- Expected  - 1
>    \+ Received  + 1
>      Object {
>    \-   "number": 0,
>    \+   "number": "0.",
>      }
