### ISSUE TITLE
Possibility to parse attributes as array

### ISSUE THREAD

**Issue by Delagen** [NaturalIntelligence/fast-xml-parser#23]
```xml
<a:a attr="2">1</a:a>
```
to
```json
{
"a":{
"@":{
"attr":"2"
},
"#text":"1"
}
}
```
for simple migration from xml2js or others

**Comment by Delagen** [comment]
Also parser hang with large xml files, where sax based gives more predictable result

**Comment by amitguptagwl** [comment]
Thanks for your contribution. 
Regarding performance issue. Can you please tell me what exact behavior you experienced? What was the size of XML? And whether it was error out or took a long time to convert it into JSON? if it was error out then what was the error it thrown?

It can help me or others to tweak it.

**Comment by Delagen** [comment]
With small data this library faster up to 10-15 times
At xml 10M up to 1.5 times
At 100M it hang and terminates with allocation memory error
xml2js parse it at 14 seconds

**Comment by amitguptagwl** [comment]
thanks for this data. I never tested this for big XML yet. I think I know where I can tweak it. I'll do it as soon as I find some free time. Once again thanks for your time to do this comparison.

**Comment by winston01** [comment]
@amitguptagwl 

Can you give any hint on the point to "tweak" to improve the performance on large XML files?

**Comment by amitguptagwl** [comment]
I tested for validator and I got to know that there are 2 reasons of failure.

1. RangeError: Maximum call stack size exceeded.
2. JS RegExp Very Long String

As I'm relying on RE heavily and JS RE engine is not able to parse a very long string (in MBs), it crashes. So either I'll have to change the implementation to read the string char-by-char and put many if conditions or I'll have to use some other 3rd party library or OS specific commands to parse it.

**Comment by Delagen** [comment]
I think this issue can be closed? Performance issues is not the subject of this.

**Comment by amitguptagwl** [comment]
@Delagen I have updated the validator to handle large files as well.

**Comment by Delagen** [comment]
@amitguptagwl Thanks for work.    Have you any performance comparison for large files?

**Comment by amitguptagwl** [comment]
I didn't check the exact time. But I guess it is few seconds for 98mb long file. There was total 21s for 66  tests. including large and small files

**Comment by Delagen** [comment]
@amitguptagwl  with {ignoreNameSpace: true} out of memory with 50М
