### ISSUE TITLE
Can't use library with IE 11

### ISSUE THREAD

**Issue by barisbikmaz** [NaturalIntelligence/fast-xml-parser#238]
### Input
Validator.js is using template strings which are not supported in ES 5.

### Code
In our angular app we import fast-xml-parser like that:
```
import { parse } from 'fast-xml-parser';
```
This is now breaking our app in IE11 as validator.js uses template strings.

**Would you like to work on this issue?**

- [ x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by brianbento** [comment]
Having the same issue.

**Comment by priyaainfo** [comment]
Facing the same issue

**Comment by amitguptagwl** [comment]
I'm expecting that the transformed code should not have template strings. Can you please highlight the code having issue? And check in [parser.js](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/lib/parser.js) if it exists.

**Comment by barisbikmaz** [comment]
I don't have a /lib folder in my node_modules/fast-xml-parser folder. I also don't wont to use the whole bundle.

My node_modules folder:
![image](https://user-images.githubusercontent.com/6338132/78251706-04d1fe00-74f2-11ea-91b4-67a0aa242567.png)

My node_modules/src folder
![image](https://user-images.githubusercontent.com/6338132/78250094-a441c180-74ef-11ea-9caf-4e5bf78a1e12.png)

validator.js in /src folder:
![image](https://user-images.githubusercontent.com/6338132/78250209-d05d4280-74ef-11ea-93ff-84629f64ffb2.png)

"version": "3.16.0"
Error on IE 11: **SCRIPT1014: invalid character**
![image](https://user-images.githubusercontent.com/6338132/78251038-06e78d00-74f1-11ea-810f-afca702d5700.png)

**Comment by brianbento** [comment]
It's in `validator.js` in several places: https://github.com/NaturalIntelligence/fast-xml-parser/blob/74b55867d00149988e3f60eb6aac8330b0669934/src/validator.js#L149

**Comment by amitguptagwl** [comment]
I'm still not understanding how are you generating the bundle to use in the browser. The code written in any src folder can use any version of node js but the transpiler transform it to be used by most of the browsers. So, for example, 

```js
msg = `Tag '${tagName}' is an invalid name.`;
```
converts to

```js
msg="Tag '"+tagName+"' is an invalid name.";
```
in bundle file.

I'm using webpack with bable for this. Please let me know how you're using this library in your code to be used in browser finally.

**Comment by brianbento** [comment]
In the `package.json` you're not serving the transpiled file, your serving it from `src`.

https://github.com/NaturalIntelligence/fast-xml-parser/blob/ea5d544f9a4631a7de88cfe1e8f9b12f48df6ec8/package.json#L5

You should be using `lib/parser.js`.

**Comment by amitguptagwl** [comment]
It was decided a way back to support code intelligence in editors and other reasons. My question is, when you're using this library in your project, are you not transpiler like webpack to create browser bundle?

**Comment by barisbikmaz** [comment]
I'm using angular with angular-cli which I think only transpiles typescript files (no babel). So I would need ES5 version of the src files. For example, Angular or React are distributed with several packages, ES5, ES6 etc. Then, in the package.json of the library there are options to tell the packager (usually webpack) what version to use, depending on the target use for TypeScript.

**Comment by amitguptagwl** [comment]
I believe it is a common problem as there can be multiple libraries who are written in ES6. But the choice should be at user's side where they can use the libraries as it is and then can transpile in ES5 or ES6 version as per their need.

**Comment by barisbikmaz** [comment]
Just as a side note: If your src files were in typescript it would also solve my problem, because angular uses typescript and the typescript compiler can transpile into ES5.

**Comment by heino126** [comment]
> Faced the same issue. It is working in IE after downgraded to 3.12.20 version

@priyaainfo 

When I downgrade to version 3.12.20 I am still facing the same issue. Can you confirm for me that version 3.12.20 is the version you are using? Thanks in advance.

**Comment by amitguptagwl** [comment]
I still need to publish the changes. But I have so many uncommitted changes on my local. Will publish the changes day after tomorrow.

**Comment by amitguptagwl** [comment]
I have published the changes. Please recheck your issue with v3.17.0. Feel free to reopen this issue.
