### ISSUE TITLE
int64 parse error

### ISSUE THREAD

**Issue by renjuncn** [NaturalIntelligence/fast-xml-parser#242]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Code
```js
    parsed = Number.parseInt(4862004940240205515, 10);
```

### Output

486200494024020600000
### expected data

4862004940240205515
**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by renjuncn** [comment]
> I'm glad you find this repository helpful. I'll try to address your issue ASAP. You can watch the repo for new changes or star it.

thanks a lot

**Comment by amitguptagwl** [comment]
Have you tried it with `parseTrueNumberOnly: true`?

**Comment by amitguptagwl** [comment]
@renjuncn I'm closing this issue as it is not answered from a long time. Feel free to reopen the issue if the problem exist.
