### ISSUE TITLE
PreserveOrder vs ArrayMode

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#244]
I was just wondering if these 2 options are serving the same purpose. So let's understand the need first;

### input
```xml
<store>
    <location>
        <![CDATA[locates in]]>
        <region>US</region>
        <![CDATA[and]]>
        <region>JAPAN</region>
        --finish--
    </location>
    <type>
        <size>
            <![CDATA[Small]]>alpha
        </size>
        <function>24x7</function>
    </type>
</store>
```

## preserveOrder
As its name suggests. So let's directly jump on the example.

Expected output
```js
[{
    store: [
        { location : [
            { "__#cdata" : "locates in"},
            { "region" : "US" }
            { "__#cdata" : "and"},
            { "region" : "JAPAN" }
            { "__#text" : "--finish--"},
        ]},
        { type: [
            { size:[
                { "__#cdata" : "locates in"},
                { "__#text" : "alpha"},
            ] },
            { function : "alpha"},
        ]}
    ]
}]
```
This is not something I like in a JS object. But this is the only solution I see.

## arrayMode
Easy looping through generated JS objects without putting conditions explicitly to check the type of element. So for the same input XML;

Expected output
```js
[{
    store: [{ 
            location : [{ 
                "__#cdata" : ["locates in", "and"],
                "region" : [ "US",  "JAPAN" ],
                "__#text" : "--finish--"
            }],
            type: [{ 
                size:[{
                    "__#cdata" : "locates in",
                    "__#text" : "alpha",
                }],
                function : "alpha"
            }]
    }]
}]
```
In `strict` mode, all the properties will either have **array of object(s)** or **array of string(s)**. So it doesn't avoid condition completely, in my opinion. It maintains the order but only in the leaf node.

## Better solution
If we keep both options it'll be so confusing to the users. So I was wondering if we should combine both options and rename `preserveOrder` to `arrayMode`. In this case, a property can have either **array of object(s)** or **string**.

I'm also thinking about the other solution where we can directly embed function in generated JS object to loop through its properties.

Your suggestions will be helpful to come out with a better solution.

**Comment by amitguptagwl** [comment]
Please share your thoughts

@MaartenX @schoste @ajmar @johnsusek @dorev @janch32 @gvillo @Kaarel @gknapp @hazaart @DazChong @jamieYou @iduchy @chovy @jinq102030

**Comment by amitguptagwl** [comment]
This is an example of looping the output of preserveOrder;

```js
function print(jsObj, JsonString){
    JsonString += '[';
    for(let i=0; i < jsObj.length; i++ ){
        JsonString += '{';
        const obj = jsObj[i];
        const keyName = Object.keys(obj)[0];
        if(Array.isArray(obj[keyName])){
            JsonString += `${keyName} : `;
            JsonString = print(obj[keyName], JsonString);
        }else if(typeof obj[keyName] === 'string'){
            JsonString += `${keyName} : '${obj[keyName]}'`;
        }else{
            JsonString += `${keyName} : ${obj[keyName]}`;
        }
        JsonString += '},';
    }
    JsonString += '\b';
    JsonString += '],';
    return JsonString;
}
```

Definetely, it needs improvement for better formatting. But this is just an example and it is 3 times faster than JSON stringify as it has limited scope.

**Comment by amitguptagwl** [comment]
And here is an example of looping through `arrayMode: 'strict'`.

```js
function print(jsArr, JsonString = ""){
    JsonString += '[';
    if(typeof jsArr[0] === 'object'){ //object
        JsonString += '{';
        const obj = jsArr[0];
        const keys = Object.keys(obj);
        for(let i=0; i < keys.length; i++ ){
            const keyName = keys[i];
            const valArr = obj[keyName];
            JsonString += `${keyName} : `;
            JsonString = print(valArr, JsonString);
        }
        JsonString += '}';
    }else if(typeof jsArr[0] === 'string'){
        for(let i=0; i < jsArr.length; i++ ){
            JsonString += `'${jsArr[i]}',`
        }
        JsonString += "\b";
    }else{
        for(let i=0; i < jsArr.length; i++ ){
            JsonString += `${jsArr[i]},`
        }
        JsonString += "\b";
    }
    JsonString += ']';
    return JsonString;
}
```

**Comment by amitguptagwl** [comment]
I was thinking to replace `arrayMode` with [xml rule file](https://github.com/NaturalIntelligence/detailed-xml-validator).

:+1: 
* Repeatable items will always be parsed into array

:-1: 
* Users need to create a XSD like rule file

**Comment by johnsusek** [comment]
@amitguptagwl So I've done some brainstorming on an ideal data structure that:

* Maintains the order of XML elements
* Minimizes the verbosity of JSON output
* Keeps the JSON as readable as possible


Here is what I've come up with:

### Node Definition

A node is an array.

This array can contain 4 types of items:
  - An *object*
    - where key of object is `__#cdata` (value is cdata string value), otherwise
    - key of object is a tag name (value is attrs object)
  - A *string* (text)
  - An *array* (node)

The type of the item in the array dictates the type of xml node (object = tag|cdata, string = text, array = node). 

### Example node children

- A tag
```
{ "store": { "id": "233" } }
```

- cdata
```
{ "__#cdata": "locates in" }
```

- text
```
"US"
```

- a node

```
[...]
```

## Example XML

```xml
<store id="233">
    <location>
        <![CDATA[locates in]]>
        <region iso="9551">US</region>
        <![CDATA[and]]>
        <region iso="42" fk="sh">JAPAN</region>
        --finish--
    </location>
    <type>
        <size>
            <![CDATA[Small]]>alpha
        </size>
        <function>24x7</function>
    </type>
</store>
```

## Example JSON Result

```json
[
  { "store": { "id": "233" } },
  [
    { "location": {} },
    { "__#cdata": "locates in" },
    [
      { "region": { "iso": "9551" } },
      "US"
    ],
    { "__#cdata": "and" },
    [
      { "region": { "iso": "42", "fk": "sh" } },
      "JAPAN"
    ],
    "finish",
  ],
  [
    { "type": {} },
    [
      { "size": {} },
      [
        { "__#cdata": "Small" },
        "alpha"
      ]
    ],
    [
      { "function": {} },
      "24x7"
    ]
  ]
]
```

This should maintain order across all nodes, and also allows for multiple root nodes. 

Thoughts/feedback?

**Comment by amitguptagwl** [comment]
done in v4
