### ISSUE TITLE
How to parse attribute's value to a primitive type?

### ISSUE THREAD

**Issue by Enado95** [NaturalIntelligence/fast-xml-parser#247]
I'm trying to see how i would parse a value to a specific type.

For example, the xml dates are represented as `01092018`. 
I could do `parseTrueNumberOnly: true` but that wouldn't work for a date like `15042018`.

I want to keep it standard so they are represented as `"15092018"`

**Comment by amitguptagwl** [comment]
Have you tried value processors?

**Comment by Enado95** [comment]
@amitguptagwl i was hoping for a working example. Also, can that same option select what key value pairs are return after the XML is converted to JSON ?

**Comment by amitguptagwl** [comment]
:)
@Enado95 I have tried to explain all the options on README which in my understanding should cover your situation. Hence I wanted to confirm if you have already tried that option before I go in detail.

However, this is an example from README
```js
tagValueProcessor: a=> he.encode(a, { useNamedReferences: true}),// default is a=>a
```
that can be probably modifed to 
```js
tagValueProcessor: (val,name)=> { if(name==='date') return new Date(val); else val; }
```

Believe me, I'm even suggesting you after reading README. Let me know if it answers your question

**Comment by Enado95** [comment]
@amitguptagwl  So tired the below like 
 
`tagValueProcessor: (val, tagName) => { if(tagName === 'StartDate') return val.toString(); else val; }`

In an attempt to convert the value to string. But the value is deeply nested. See example below.
I want convert to string as well rename multiple fields at the same time. 

```
<MGResponse
    xmlns="urn:crif-messsage:2006-08-23">
    <RI_Req_Output
        xmlns="">
        <CreditHistory>
            <Contract>
                <Instalments>
                    <GrantedContract>
                        <CommonData>
                            <FICode>Micro-Finance 0002</FICode>
                            <FIContractCode />
                            <CBContractCode>K01772698</CBContractCode>
                            <ContractType>35</ContractType>
                            <Phase>LV</Phase>
                            <StartDate>04052018</StartDate>
                            <LastUpdateDate>30112019</LastUpdateDate>
                            <Currency>JMD</Currency>
                            <CreditCurrency>JMD</CreditCurrency>
                            <Role>A</Role>
                        </CommonData>
                        <FlgReorg></FlgReorg>
                        <PaymentMethod>BOE</PaymentMethod>
                        <Amount>56328</Amount>
                        <History>
                            <Year>2019</Year>
                            <Month>11</Month>
                            <DueInstallNum>0</DueInstallNum>
                            <PastDueDaysNum></PastDueDaysNum>
                            <Status></Status>
                        </History>
                    </GrantedContract>
                </Instalments>
            </Contract>
        </CreditHistory>
    </RI_Req_Output>
</MGResponse>
```

**Comment by amitguptagwl** [comment]
Do you mean renaming tag's name? It is not supported currently.

**Comment by Enado95** [comment]
What about changing the type a deeply nested value like StartDate in the example provided

**Comment by amitguptagwl** [comment]
The way FXP works is
1. first it call the value processor where you can parse it to Date object probably
2. then if the value is string then try to parse it. Since you must have already parse it to Date object, FXP must not change it.
