### ISSUE TITLE
Odd behaviour when parsing sitemaps 

### ISSUE THREAD

**Issue by jarodium** [NaturalIntelligence/fast-xml-parser#249]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When trying to parse a google sitemap.xml for two different websites, there is a difference in behaviour.
Assume website A has only one entry and website B has two or more entries.

When parsing A, I need to loop over **parsed.urlset** to get the loc node. When parsin B, I need to loop over **parsed.urlset.url** to get the loc node

### Input
**Sitemap A**

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://example.com/</loc>
    <lastmod>2020-05-11</lastmod>
  </url>
</urlset>

```
**Sitemap B**

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://example.com/</loc>
    <lastmod>2020-05-11</lastmod>
  </url>
<url>
    <loc>https://example.com/about.html</loc>
    <lastmod>2020-05-11</lastmod>
  </url>
<url>
    <loc>https://example.com/contacts.html</loc>
    <lastmod>2020-05-11</lastmod>
  </url>
</urlset>
```

### Code
```js
 var parser = require('fast-xml-parser');
 var he = require('he');
 var options = {
      attributeNamePrefix : "@_",
      attrNodeName: "attr", //default is 'false'
      textNodeName : "#text",
      ignoreAttributes : true,
      ignoreNameSpace : false,
      allowBooleanAttributes : false,
      parseNodeValue : true,
      parseAttributeValue : false,
      trimValues: true,
      cdataTagName: "__cdata", //default is 'false'
      cdataPositionChar: "\\c",
      parseTrueNumberOnly: false,
      arrayMode: false, //"strict"
      attrValueProcessor: (val, attrName) => he.decode(val, {isAttributeValue: true}),//default is a=>a
      tagValueProcessor : (val, tagName) => he.decode(val), //default is a=>a                
  };     
  try{
        var jsonObj = parser.parse(data,options, true);                                          
        $.each(jsonObj.urlset.url,function(i,v) {                    
            let t = new URL(v.loc);
            let x = TEMPLATE1;
             x = x.replace('{URL}',v.loc).replace('{PAGE}',t.pathname);
            $("#sitemap ul").append(x);
         });                             
    }catch(error){              
              console.log(error.message)
    }    
```

### Output

Output on Sample A raises exception that the URL from v.loc is invalid. Output is an array :
`[https://example.com/,2020-05-11]`

### expected data

Output on Sample B loops and processes properly. Output is a JSON object has expected :
`{loc:https://example.com/,lastmod:2020-05-11}`

### Workaround attempts
Properly checking for length in the parsed data will solve this, but the resulting object should be JSON at all times.

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
You need to enable arrayMode.

**Comment by jarodium** [comment]
Hi. 
Thank you.

It works in arrayMode on, and could parse with.
