### ISSUE TITLE
Parse error when attribute value contains `->`

### ISSUE THREAD

**Issue by kevinprotoss** [NaturalIntelligence/fast-xml-parser#250]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Parse error occurs when attribute value contains `->`. All attributes after this character can not be correctly parsed. They are parsed as a text tag.

### Input
```xml
<? xml version = "1.0" encoding = "UTF - 8" ?>
<testStep type="restrequest" name="test step name (bankId -> Error)" id="90e453d3-30cd-4958-a3be-61ecfe7a7cbe">
      <settings/>
      <encoding>UTF-8</encoding>
</testStep>
```

### Code
```js
const parser = require("fast-xml-parser");

const options = {
  attributeNamePrefix: "@",
  textNodeName: "#",
  cdataTagName: "__cdata",
  ignoreAttributes: false,
  ignoreNameSpace: false,
};

const jsonObj = parser.parse(xmlData,options);
console.log(jsonObj);
```

### Output
```js
{
  testStep: {
    '#': 'Error)" id="90e453d3-30cd-4958-a3be-61ecfe7a7cbe">',
    '@type': 'restrequest',
    settings: '',
    encoding: 'UTF-8'
  }
}
```

### expected data
```js
{
  testStep: {
    '@id": '90e453d3-30cd-4958-a3be-61ecfe7a7cbe',
    '@name': 'test step name (bankId -> Error)',
    '@type': 'restrequest',
    settings: '',
    encoding: 'UTF-8'
  }
}
```

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
Please check #167 & #186

**Comment by kevinprotoss** [comment]
Hi, 

Thanks for your reply, however I prefer the workaround not completely. Of course, the performance is a great point for this module. Correct parse is also important for me as a user. I found xml2js can parse this situation correctly, therefore maybe I'll try to change to that completely. 

Best regards,
Kevin

**Comment by amitguptagwl** [comment]
This library is currently based on regex only which can't handle this situation. However, I'm planning to implement the workaround in the library itself. I'll try that out today if it goes as expected.

**Comment by amitguptagwl** [comment]
**UPDATE**: I have re-wrote a lot of parsing logic. I need to fix some value parsing. Then I'll test performance. But I'm hopping that there is no impact on the performance.

**Comment by amitguptagwl** [comment]
Changes are fixed and published. Please use v3.17.0. Please reopen the issue if any concern is left on the same topic.
