### ISSUE TITLE
Parsing issue in 3.17.0

### ISSUE THREAD

**Issue by Delagen** [NaturalIntelligence/fast-xml-parser#251]

**Comment by Delagen** [comment]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by amitguptagwl** [comment]
Hi @Delagen , seen you after a long time. Let me check what is the issue.

**Comment by amitguptagwl** [comment]
This issue has been fixed. v3.17.1
