### ISSUE TITLE
3.17.1: '\n' after xml tag name not ignored

### ISSUE THREAD

**Issue by sverweij** [NaturalIntelligence/fast-xml-parser#256]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

In 3.17.1, when an xml tag name is followed immediately by a newline ('\n') that newline character is taken as part of the xml tag name.

In 3.16.0 this still worked as expected (see below)

### Input

```xml
<?xml version="1.0" encoding="UTF-8"?>
<scxml
  xmlns="http://www.w3.org/2005/07/scxml">
</scxml>
```

### Code

```js
const lSCXMLString = `<?xml version="1.0" encoding="UTF-8"?>
<scxml
  xmlns="http://www.w3.org/2005/07/scxml">
</scxml>
`;
console.dir(
  fastxml.parse(lSCXMLString, {
    ignoreAttributes: false,
    trimValues: false // setting this to true merely removes the #text attribute - the tag name remains scxml\n
  }),
  { depth: 99 }
);
```

### Output

```json
{
    "scxml\n": {
        "#text": "\n",
        "@_xmlns": "http://www.w3.org/2005/07/scxml"
    }
}
```

### expected data

```json
{
    "scxml": {
        "#text": "\n",
        "@_xmlns": "http://www.w3.org/2005/07/scxml"
    }
}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Changes are fixed and pushed to github. I'll publish them to npm tomorrow to cover any more change.

**Comment by amitguptagwl** [comment]
published

**Comment by sverweij** [comment]
Thanks for the quick fix @amitguptagwl!
