### ISSUE TITLE
Please continue to support it on IE 11

### ISSUE THREAD

**Issue by wanmifam** [NaturalIntelligence/fast-xml-parser#258]
Hello team,

Please continue to support it on IE 11.

The code below causes IE 11 to fail:

https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/parser.js#L47

=> proposed change to: `Object.keys(xmlNode.child).forEach( function(key) { ... }`

https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/parser.js#L52
=>proposed change to: `node.forEach( function(item,index)  {...}`

Best regards!

**Comment by amitguptagwl** [comment]
I would appreciate it if you raise the PR. I'm planning to provide babilify version in future.

**Comment by wanmifam** [comment]
> I would appreciate it if you raise the PR. I'm planning to provide babilify version in future.

Hello @amitguptagwl ,
Please see PR follow link: https://github.com/NaturalIntelligence/fast-xml-parser/pull/259

**Comment by amitguptagwl** [comment]
Thanks @wanmifam for your effort and time. I have merged the PR.
