### ISSUE TITLE
XML with tabs is not parsed correctly

### ISSUE THREAD

**Issue by dalebel** [NaturalIntelligence/fast-xml-parser#260]
* [x] Are you running the latest version?
yes (3.17.2)
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Parsing of xml with tabs, is not parsed to json fields.
and output has has many /t/n fields.
It was working in version 3.16.0
 
### Input
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<MPD
	availabilityStartTime=\"2020-02-16T10:52:03.119Z
	xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance
	<Period
		id="1578477220">
	</Period>
</MPD>
```
### Code
Include the code being used for parsing
```js
const parser = require('fast-xml-parser');
const xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
    "<MPD\n" +
    "\tavailabilityStartTime=\"2020-02-16T10:52:03.119Z\"\n" +
    "\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
    "\t<Period\n" +
    "\t\tid=\"1578477220\">\n" +
    "\t</Period>\n" +
    "</MPD>";

const parserOptions ={arrayMode:true, ignoreAttributes:false, attrNodeName:"$", attributeNamePrefix : "", textNodeName: ""};
const metadata = parser.parse(xml, parserOptions);
console.log(JSON.stringify(metadata," ", 2));
```
### Output

``` json
{
  "MPD\n\tavailabilityStartTime=\"2020-02-16T10:52:03.119Z\"\n\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t<Period\n\t\tid=\"1578477220\"": ""
}
```
### expected data

``` json
{
  "MPD": [
    {
      "$": {
        "availabilityStartTime": "2020-02-16T10:52:03.119Z",
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "id": "1578477220"
      }
    }
  ]
}
```
**Would you like to work on this issue?**

- [ ] Yes
- [X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
fixed. Please refer v3.17.3. Reopen the issue if still exists.

**Comment by dalebel** [comment]
Thanks for the promt fix !

‫בתאריך יום ד׳, 27 במאי 2020 ב-6:17 מאת ‪Amit K Gupta‬‏ <‪
notifications@github.com‬‏>:‬
