### ISSUE TITLE
bad xml causes out of memory

### ISSUE THREAD

**Issue by dalebel** [NaturalIntelligence/fast-xml-parser#261]
* [x] Are you running the latest version?
yes (3.17.2)
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
parsing of bad xml is causing out of memory in node js.
Was working on 3.16.0
### Input
``` xml
<!-- bad xml --->
<?xml version="1.0"
```
### Code
Include the code being used for parsing
```js
const parser = require('fast-xml-parser');
const xml="<!-- bad xml --->\n" +
    "<?xml version=\"1.0\"";
const parserOptions ={arrayMode:true, ignoreAttributes:false, attrNodeName:"$", attributeNamePrefix : "", textNodeName: ""};
const metadata = parser.parse(xml, parserOptions);
console.log(JSON.stringify(metadata," ", 2));
```
### Output

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory ...
### expected data

``` json
""
```
**Would you like to work on this issue?**

- [ ] Yes
- [X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Ideally, an untrusted XML should be validated first or you can just pass `true` as 3rd argument to the parser `parser.parse(xmlData, {} , true);`. However, I've fixed the issue in the parser as well. Please refer v3.17.3. Reopen the issue if still exists.

**Comment by dalebel** [comment]
thanks for the promt fix!

‫בתאריך יום ד׳, 27 במאי 2020 ב-6:16 מאת ‪Amit K Gupta‬‏ <‪
notifications@github.com‬‏>:‬
