### ISSUE TITLE
attrValueProcessor sees <![CDATA[undefined]]> as empty string

### ISSUE THREAD

**Issue by jamaica474** [NaturalIntelligence/fast-xml-parser#262]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
My xml is generated from template literal, and sometimes it receives "undefined" as tag value. These are the values I'm trying to filter out.
### Input
<tag><![CDATA[undefined]]></tag>

### Code
```js
parse('<tag><![CDATA[undefined]]></tag>, {
            cdataTagName: '__cdata',
            attrValueProcessor: (val) => {
               console.log(val === '');
               return val;
              }, 
          })
```

### Output
true

### expected data
undefined

**Would you like to work on this issue?**

- [ ] Yes
- [x ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
This is working fine for me. Probably because I fixed an issue which is not published yet. Please refer to v3.17.3 now. Reopen the issue if still exists.

**Comment by jamaica474** [comment]
Issue persist for me
