### ISSUE TITLE
Inconsistent JSON for elements with text data

### ISSUE THREAD

**Issue by kk-08** [NaturalIntelligence/fast-xml-parser#263]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When a node does not have any child element or attribute, the text data is returned as:

```
{ ....
"elementName": "textData"
.... }
```
instead of
```
{ ....
"elementName": {
   "#text": "textData"
}
.... }
```

However, when the element has attributes or children elements, the text data is returned under "#text".

This causes inconsistency in the expected output when converting an XML to JSON.

### Input
```
        <elementWith attr="value">
        	Address1
        </elementWith>
        <elementWithout>
            Address2
        </elementWithout>
```

### Code
Using only the `ignoreAttributes: false`

### Output
```
{
    "elementWith": {
        "#text": "Address1",
        "@_attr": "value"
    },
    "elementWithout": "Address2"
}
```

### expected data
```
{
    "elementWith": {
        "#text": "Address1",
        "@_attr": "value"
    },
    "elementWithout": {
        "#text": "Address2"
    }
}
```

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by amitguptagwl** [comment]
It is expected behavior. When a tag is leaf node then the value should be assigned directly otherwise as a text node.

**Comment by kk-08** [comment]
I get that. But are we willing to change this in favor of a consistent output every time? This would reduce validation/parsing efforts at the client's end.

**Comment by amitguptagwl** [comment]
I can understand your ask. We can introduce a flag to render the leaf node with `#text` only. But I'm not sure if anyone really need it. I have already started some relevant threads but no one has shown their interests. So let's wait until more people express their need. People generally use `arrayMode: 'strict'`.

**Comment by perevernihata** [comment]
I have same issue, even with arrayMode: 'strict', it is really hard to work with data parsed inconsistently when it comes to leaf text node.
Having some property like `forceTextNode: true` would make life much easier. How much effort is to introduce something like this?

**Comment by amitguptagwl** [comment]
You can check #244 that I started for the discussion. You can also check for the v4 branch for implementation.

**Comment by perevernihata** [comment]
I checked the v4 branch and it is way out of sync given the number of changes (and stalled - updated 11 months ago). I thought we could introduce a new field that will default to the current behaviour but also can enable consistent output. Since it is not a breaking change - it would be ok to release it as a minor version under v3

**Comment by perevernihata** [comment]
I created initial PR: https://github.com/NaturalIntelligence/fast-xml-parser/pull/351 if you are generally happy with it - I can add more tests or refactor according to your comments

**Comment by amitguptagwl** [comment]
Yes, v4 still has pending work to finish. But array mode doesn't give desire response in all the cases on v3. So it'll mesh it up more by having array mode specific feature on v3. I feel that I'll be able to resume changes in v4 from next week.

Moreover, `forceTextNode` seems confusing. I'm wondering if there is more appropriate name for this property. Let's think that as well.

**Comment by amitguptagwl** [comment]
Please use `alwaysCreateTextNode` option for consistent behavior.
