### ISSUE TITLE
Feature approval: ignoreFirstLineComment

### ISSUE THREAD

**Issue by beliaev-maksim** [NaturalIntelligence/fast-xml-parser#264]
Hello,
there are some cases when **XML data has a comment as first line**. I know that this is wrong input data however sometimes we do not have control on data we receive.
For example following command line produces XML in Windows with that wrong behaviour
```shell
schtasks /query /xml
```

I think it might be possible to handle if first line in comment with option and some code modifications that I may try to implement in case if you say that such feature could be implemented and not violates any rules

```js
{ ignoreFirstLineComment: true }
```
### Output of schtasks
```shell
<!-- \Microsoft\XblGameSave\XblGameSaveTask -->
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>Microsoft</Author>
    <Description>XblGameSave Standby Task</Description>
    <URI>\Microsoft\XblGameSave\XblGameSaveTask</URI>
  </RegistrationInfo>
  <Principals>
    <Principal id="LocalSystem">
      <UserId>S-1-5-18</UserId>
    </Principal>
  </Principals>
  <Settings>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <ExecutionTimeLimit>PT2H</ExecutionTimeLimit>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <RunOnlyIfIdle>true</RunOnlyIfIdle>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
  </Settings>
  <Triggers>
    <IdleTrigger id="XblGameSave Check on CS Entry">
      <Enabled>false</Enabled>
    </IdleTrigger>
  </Triggers>
  <Actions Context="LocalSystem">
    <Exec>
      <Command>%windir%\System32\XblGameSaveTask.exe</Command>
      <Arguments>standby</Arguments>
    </Exec>
  </Actions>
</Task>
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by amitguptagwl** [comment]
Let's think some generic approach as this library is being used by many users we can't consider particular cases. Eg `removeCommentsFirst` or something else.

**Comment by beliaev-maksim** [comment]
agree, makes sense. 

However can we ignore comments in any case, even if it is first line?

**Comment by amitguptagwl** [comment]
I believe we're already doing that in parser. We first remove the comments and newline chars then process ahead

**Comment by beliaev-maksim** [comment]
@amitguptagwl 
so checker will complain on "first line comment" and parser will not, is that correct?

**Comment by amitguptagwl** [comment]
This is expected. Test it and let me know if you see the issue.

**Comment by amitguptagwl** [comment]
Please reopen if any concern is left to assit.
