### ISSUE TITLE
empty string added in json array due to custom Array prototype

### ISSUE THREAD

**Issue by Shana-AE** [NaturalIntelligence/fast-xml-parser#267]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

hi, guys, I met the bug of unexpected tailing empty string in array when converting xml to json today, after debug, I found [this line](https://github.com/NaturalIntelligence/fast-xml-parser/blob/057a2d31f112ba9e7bb4afa5bec5c8675f86c36e/src/node2json.js#L31)
enumerated the Array custom prototype and cause the empty string pending, maybe we should exam whether `tag` is `node.child[tagname]` own property?

### Input

just use the online tool, and add custom Array prototype member using the devtools, then the bug would show up.

### Code

```js
Array.prototype.test = 'test';
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

I'm not sure it's appropriate to check with `hasOwnProperty` to check the member in every for...in loop

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Sorry for the lost conversation. Can you please give an example, in what case it fails?

I tried with following input which works fine;
```xml
<node>
<repeat/>
<repeat/>
<test>some</test>
<test>some</test>
<tag>sdf</tag>
<tag>sdf</tag>
</node>
```

**Comment by Shana-AE** [comment]
@amitguptagwl Sure, you can use the [online tool](https://naturalintelligence.github.io/fast-xml-parser/) for testing.

Normally you get the result blow

```json
{
    "node": {
        "repeat": [
            "",
            ""
        ],
        "test": [
            "some",
            "some"
        ],
        "tag": [
            "sdf",
            "sdf"
        ]
    }
}
```

But open up the dev tools and type in `Array.prototype.test='test'` (just add anything to the prototype of Array or Object) then you get:

```json
{
    "node": {
        "repeat": [
            "",
            "",
            ""
        ],
        "test": [
            "some",
            "some",
            ""
        ],
        "tag": [
            "sdf",
            "sdf",
            ""
        ]
    }
}
```

**Comment by amitguptagwl** [comment]
hmm, I got your point.

**Comment by eacaps** [comment]
I've run into this issue as well. Ember modifies the prototype of `Array` to include `_super`. This causes empty strings to be added as @Shana-AE describes. I think `hasOwnProperty` would be a fine solution, alternatively I think this should be using a `for( var ... of ...)` rather than a `for( var ... in ...)`: https://stackoverflow.com/questions/29285897/what-is-the-difference-between-for-in-and-for-of-statements-in-jav#:~:text=Both%20for..in%20and%20for,values%20of%20an%20iterable%20object.
