### ISSUE TITLE
Ignore property/key when value is undefined

### ISSUE THREAD

**Issue by jose-pr** [NaturalIntelligence/fast-xml-parser#269]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Is there any way to tell the serializer when converting from jsonObject to xml, to ignored undefined tags.
### Code
```js
var xml = require("fast-xml-parser")

const XMLParserOptions = {
    attributeNamePrefix: "@_",
    textNodeName: "#text",
    ignoreAttributes: false,
};

const toXml = new xml.j2xParser(XMLParserOptions);
const XMLSerializer = {
    serialize(obj) {
        return toXml.parse(obj);
    },
    deserialize(str) {
        return parse(str, XMLParserOptions);
    }
}
const test = XMLSerializer.serialize({
    test2:undefined,
    test3:'1a'
});

```

### Output
```
"<test2>undefined</test2><test3>1a</test3>"
```
### expected data
```
"<test3>1a</test3>"
```

**Would you like to work on this issue?**

- [x] Yes, if pointed to the right location and not above my skill.
- [] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
This is working fine for me. Check this example

```js
const jObj = {
    a: {
        b: [
            undefined,
            "val1",
            {
                c: "val2",
                d: undefined,
                e: "val3"
            }
        ]
    }
};
const parser = new Parser({
    attributeNamePrefix: "@_",
    textNodeName: "#text",
    ignoreAttributes: false,
});
const result = parser.parse(jObj);
const expected = "<a><b>val1</b><b><c>val2</c><e>val3</e></b></a>";
expect(result).toEqual(expected);
```

**Comment by jose-pr** [comment]
It looks to be working when i tested it on my computer. 
My problem is I was using https://runkit.com/embed/ok7nxctybzyh to test it before using it. And runkit returns it as undefined plus it also says  require("fast-xml-parser") version 3.2.0 so that may also have something to do with it.

**Comment by amitguptagwl** [comment]
NP. Hence, I have introduced the eckeclist in Issue template.
