### ISSUE TITLE
Error IE11 : Object doesn't support property or method 'trimRight'

### ISSUE THREAD

**Issue by rajsh612** [NaturalIntelligence/fast-xml-parser#271]
* [x]  Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Hi, I met the bug of unexpected error in xlstr2xmlnode.js file. after investigation, I found that line No 257 
tagName = tagExp.substr(0, separatorIndex).trimRight(); in xmlstr2xmlnode.js has issue.

trimRight() method is not supported in IE11 browser?

### Input

just use package, and try to parse https://www.amazon.in/[text](https://www.amazon.in/) line.

### Code

`service.validate = function(str) {
        try {
            var json = parser.parse(str);
        }
        catch (err) {
            return err;
        }
        return str;
    };`

### Output
TypeError: Object doesn't support property or method 'trimRight'

### expected data
should no display any error

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
fixed. changes are available on github

**Comment by Amazing-Mansi** [comment]
Hi @amitguptagwl ,

 I don't see a PR linked to this bug. Is this bug fixed in the NPM version 3.1.7.4?

**Comment by amitguptagwl** [comment]
I fixed multiple issues in a single commit. So I cant say exactly. But when I just do a simple search on this repo, I got a commit against it, please check

https://github.com/NaturalIntelligence/fast-xml-parser/commit/c6659544fbb5d7ae670b27ceaaa58f1cae138034

**Comment by amitguptagwl** [comment]
@Amazing-Mansi , I'm closing this issue. Please reopen if it is still there
