### ISSUE TITLE
Leading zero results in type change and lost value

### ISSUE THREAD

**Issue by Berger92** [NaturalIntelligence/fast-xml-parser#273]
* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
If the value starts with 0, then it it becomes 0.
### Input
```<code>0E68</code>```

### Output
`{ code: 0 }`

### Expected data
`{ code: '0E68' }`

**Comment by amitguptagwl** [comment]
I believe you need to set parseTrueNumberOnly flag to `true`. Check README

**Comment by Berger92** [comment]
Yes, it did work. Thanks. My bad. I did have a look at the reamde, but it didn't occur to me it had anything to do with it.

**Comment by stevenmhunt** [comment]
I find it surprising that you have to "opt out" of behaviors like this. I personally just experienced a similar issue with this library and went searching to see if anyone else was experiencing the same issue. This project should consider changing the default settings to an "opt in" model for a better developer experience when the next major version release happens.

**Comment by amitguptagwl** [comment]
@stevenmhunt this is very old issue. config has been changed. please check the new one
