### ISSUE TITLE
Converting json which includes a number field to xml, fails with a string.replace is not a function from (suggested) he library

### ISSUE THREAD

**Issue by ycheapopo** [NaturalIntelligence/fast-xml-parser#274]
* [ Y] Are you running the latest version?
* [ Y] Have you included sample input, output, error, and expected output? 
* [ Y] Have you checked if you are using correct configuration?
* [ N] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When a json includes a number, and running the code example appearing in fast-xml-parser site, causes 
issue (with the suggested he library)
Although this is not a problem with fast-xml-parser per se, I am not sure what is the best way to fix this issue
(apart from sprinkling toString on integers which seems a bit stupid).
Others probably would stumble upon this too, 
so perhaps a documentation of how to handle this common case would be welcome
(e.g. defaultOptions.attrValueProcessor should verify it is a string before calling he.encode. But not sure performance hit so maybe there are better solutions)
### Input
{age: 100}
### Code
```js
var he = require('he')
var json_or_js_obj = {age: 100}
var Parser = require("fast-xml-parser").j2xParser;
//default options need not to set
var defaultOptions = {
    attributeNamePrefix : "@_",
    attrNodeName: "@", //default is false
    textNodeName : "#text",
    ignoreAttributes : true,
    cdataTagName: "__cdata", //default is false
    cdataPositionChar: "\\c",
    format: false,
    indentBy: "  ",
    supressEmptyNode: false,
    tagValueProcessor: a=> he.encode(a, { useNamedReferences: true}),// default is a=>a
    attrValueProcessor: a=> he.encode(a, {isAttributeValue: isAttribute, useNamedReferences: true})// default is a=>a
};
var parser = new Parser(defaultOptions);
var xml = parser.parse(json_or_js_obj);

```

### Output

string.replace is not a function
    at Object.encode (node_modules/he/he.js:202:20)
### expected data

<age>100</age>
**Would you like to work on this issue?**

- [ ] Yes
- [ X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by daadetka** [comment]
Just comment out the tagValueProcessor line in defaultOptions
