### ISSUE TITLE
Parse empty tags as self-closing tags 

### ISSUE THREAD

**Issue by lcnvdl** [NaturalIntelligence/fast-xml-parser#276]
* [Yes] Are you running the latest version?
* [Yes ] Have you included sample input, output, error, and expected output? 
* [Yes ] Have you checked if you are using correct configuration?
* [Nope ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Hi! I'm trying to generate an Android Manifest using a JSON. It is working pretty fine, but I'm having the next problem:

Tags like 
```xml
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
Is being parsed as
```xml
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>
```

Is there any option (or anything else) to solve this?

### Code
Settings that I'm using
```js
const settings = {
    ignoreAttributes: false,
    format: true
};
```

**Would you like to work on this issue?**

- [ ] Yes
- [x ] No

**Comment by amitguptagwl** [comment]
Try `supressEmptyNode: false`

**Comment by lcnvdl** [comment]
> Try `supressEmptyNode: false`

Hi! I've tried it but it didn't work. Anyway, thanks for your answer.

**Comment by amitguptagwl** [comment]
input:
```js
const jObj = {
            a: {
                b: [
                    "",
                    {c: "val2"}
                ]
            }
        };
        const parser = new Parser({
            supressEmptyNode: false
        });
        const result = parser.parse(jObj);
        console.log(result);
```
```xml
<a><b></b><b><c>val2</c></b></a>
```
This is working fine to me.

**Comment by lcnvdl** [comment]
Hi! Maybe you are not understanding me.

I'm trying to doing this:

input:
```javascript
const jObj = {
            a: {
                b: [
                    "",
                    {c: "val2"}
                ]
            }
        };
        const parser = new Parser({
            supressEmptyNode: false
        });
        const result = parser.parse(jObj);
        console.log(result);
```
```html
FInal output
<a><b /><b><c>val2</c></b></a>
```

**Comment by amitguptagwl** [comment]
This is a fair possibility to misunderstand the expectations. Hence sample code in issue is always recommended. But as you have raised another issue. Let's discuss it there.
