### ISSUE TITLE
Adding the ability to avoid parsing the value of certain attribute names

### ISSUE THREAD

**Issue by balance80** [NaturalIntelligence/fast-xml-parser#278]
I need a way to avoid parsing the value of certain attribute names while still using parseAttributeValue. I have attributes that can have a list of numbers that should always be a string, but when the list only has a single number it is parsed from a string into a number. I still want regular numbers and booleans to be parsed, and the attrValueProcessor is run before the parseValue function so I cannot just force it to a string in the attrValueProcessor.

My suggestion is implementing something along the lines of stopNodes, but for attributes. In my branch I have added doNotParseAttributeNames as an array, just like stopNodes. Then I just check that before running parseValue on the attribute value.

Suggestion:
```
if (options.doNotParseAttributeNames.length && options.doNotParseAttributeNames.includes(attrName)) {
        attrs[options.attributeNamePrefix + attrName] = matches[i][4];
    } else {
        attrs[options.attributeNamePrefix + attrName] = parseValue(
        matches[i][4],
        options.parseAttributeValue,
        options.parseTrueNumberOnly
    );
}
```

My changes can be seen here: https://github.com/NaturalIntelligence/fast-xml-parser/compare/master...balance80:master

Would this be something to add into the main repo?

**Would you like to work on this issue?**
- [x ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
stopNode is an entirely different concept. We'll have to think about how we can skip attributes from parsing either when indicated in processor or some other way.

Eg we can skip calling value parser when the processor is called. However, value parser can be passed as parameter the method so that anyone can still parse the value or so on.

**Comment by amitguptagwl** [comment]
v4 `attributeValueParser` can be used to avoid parsing for certain cases. Please check if it fulfill your purpose.

**Comment by amitguptagwl** [comment]
feel free to reopen the issue if problem exists
