### ISSUE TITLE
Unwanted parse to number for strings or changed strings

### ISSUE THREAD

**Issue by swaterkamp** [NaturalIntelligence/fast-xml-parser#279]
* [X] Are you running the latest version? 3.17.4
* [X] Have you included sample input, output, error, and expected output? (Summarized in "Examples" for better readability)
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When parsing specific tag values we need those to be a simple string. Instead, fast-xml-parser transforms those to a number, or, if it keeps it as string, still removes some characters from that string.

Our settings are:
```js
const PARSER_OPTIONS = {
  attributeNamePrefix: '_',
  ignoreAttributes: false,
  ignoreNameSpace: true,
  textNodeName: '__text',
  parseTrueNumberOnly: true,
  attrValueProcessor: attr => parseXmlEncodedString(attr),
  tagValueProcessor: value => parseXmlEncodedString(value)
  },
};
```
where parseXmlEncodedString() simply unescapes some characters from the parsed result.

The line that breaks the parsing for us is https://github.com/NaturalIntelligence/fast-xml-parser/blob/827d7c4fa69813d27aabb80adfb81dae867e93ea/src/xmlstr2xmlnode.js#L110

If this was simply removed, all our needs would be met, but I guess it would break something for other users.

Here are some examples of what we receive as output given a specific input:
 
### Examples
"212.130" -> 212.13
"212.000" -> 212
"212." -> "212."
"000.000" -> "000"
".0" -> ""
"003.10" -> "003.1"
"0123.0" -> "0123"

In all cases we would just like to have the original string.

**Would you like to work on this issue?**

- [x] Yes, if you could kindly list us what needs to be done in your opinion
- [ ] No

Thank you for providing this parser, it is an essential part for our software and we would be happy to help improve it :)

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
You can use the option parse if true number only. Please check README

**Comment by swaterkamp** [comment]
Hi @amitguptagwl ,
thank you for your reply. We use that option already (I posted the whole option block above), but it doesn't work as expected. The examples above are taken from the parsed responses with `parseTrueNumberOnly: true` enabled.

**Comment by swaterkamp** [comment]
Hi @amitguptagwl,
I'm bringing this up again in order to kindly ask if you have any further suggestions or info on this matter.

**Comment by amitguptagwl** [comment]
Sorry I missed your last msg.

```
"212.130" -> 212.13
"212.000" -> 212
"212." -> "212."
"000.000" -> "000"
".0" -> ""
"003.10" -> "003.1"
"0123.0" -> "0123"
```

As per the current expectations from the code, following seems correct;
```
"212.130" -> 212.13
"212.000" -> 212
"212." -> "212."
```
I feel code need to be fixed for following;
```
"000.000" -> "000"
".0" -> ""
"003.10" -> "003.1"
"0123.0" -> "0123"
```

However, I feel that definition of `parseTrueNumberOnly` is confusing so probably I can provide something more accurate to the demand
```js
parseValue: {
   attribute : true,
   tag : true,
   validNumbersOnly : true, //skip 2. , 034, but will parse 2.1300
   parseOnlyIfSameResult : true, //skip 2.1300
}
```

For your solution, you can set `parseNodeValue: false` and use tag value processor for your custom logic.

**Comment by swaterkamp** [comment]
Thank you for your answer.
The tag value processor is of no help, as long as I can't tell it _which_ tag needs which rules. If I switch off `parseNodeValue: false` all node values are ignored and that causes actual numbers to be regarded as strings in cases where we don't want that to happen. It'd be nice if we had the chance to tell the parser something along the line "If the tag is named 'xyz' regard it's value as string, independent of whether it looks like a number".

**Comment by amitguptagwl** [comment]
I've recently published [strnum](https://github.com/NaturalIntelligence/strnum) to handle parsing part externally. Please check and let me know if it handles your expectations. I'm planning to use it in FXP in few days.

Handling on tag level is pending.

**Comment by amitguptagwl** [comment]
@swaterkamp Please update to FXP v3.20.0. Use following code as a fix

```js
const result = parser.parse(xmlData, {
    ignoreAttributes: false,
    parseAttributeValue: true,
    numParseOptions: {
        leadingZeros: true,
        skipLike: /\.[0-9]*0/
    }
});
```

**Comment by cigaretterevived** [comment]
@amitguptagwl https://ream579.github.io/4GIXp02R0DfMWJA3qHZUKMExhZ4YpGk/
