### ISSUE TITLE
IE ParseInt Error

### ISSUE THREAD

**Issue by d1d2r31** [NaturalIntelligence/fast-xml-parser#28]
IE not Support Number.parseInt()

Chrome  Support

Number.parseInt -> parseInt() 

change plz... have a nice day~

![screenshot_2](https://user-images.githubusercontent.com/11750163/33537707-569b11ee-d900-11e7-8f66-aad26d480ff3.png)

![screenshot_1](https://user-images.githubusercontent.com/11750163/33537680-2d3fd7e4-d900-11e7-8603-2428021561db.png)

**Comment by amitguptagwl** [comment]
Oh...Ah!! fixed

**Comment by barisbikmaz** [comment]
@amitguptagwl This issue is still not fixed. Can't use the library on IE.

You can use parseInt directly or do polyfill sth like
```
if (!Number.parseInt) {
   Number.parseInt = window.parseInt
}
if (!Number.parseFloat) {
   Number.parseFloat= window.parseFloat
}
```

**Comment by amitguptagwl** [comment]
done. plz check
