### ISSUE TITLE
Option to ignore root element?

### ISSUE THREAD

**Issue by Qrzy** [NaturalIntelligence/fast-xml-parser#282]
I saw in the source, that either it's been considered or it was removed:
https://github.com/NaturalIntelligence/fast-xml-parser/blob/827d7c4fa69813d27aabb80adfb81dae867e93ea/src/xmlstr2xmlnode.js#L28

Root element in the parsing result is often irrelevant. Would it be possible to add that option (back)?

### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

**Comment by amitguptagwl** [comment]
I'll have a look

**Comment by Qrzy** [comment]
Hi @amitguptagwl, did you have any chance to take a look at this?

**Comment by Qrzy** [comment]
Hi @amitguptagwl 
I had some spare time and after looking at the code I came to the solution introduced in #292. 
What do you think?

**Comment by amitguptagwl** [comment]
This was present in old version and purposefully removed. I didn't remember the exact reason. So I'll check if we should include it again. However, as it is not a bug but a good to have feature, I'll prefer to publish it with v4 if we plant to have it.

**Comment by Qrzy** [comment]
Oh, knowing what was the reason to remove this feature would be really helpful!
Yes, it's a nice-to-have feature request, for now I've added this logic to my app where parser is used, just thought it would be more convenient to pass on additional option and have it already done by parser. No pressure.

**Comment by amitguptagwl** [comment]
If you're using parser with `preserveOrder:true` then it can be easily achieve. Can you please check and confirm if it meets your need.

**Comment by liudonghua123** [comment]
Is there any updates about this option? `ignoreRootElement` seems to be a good configuration.
