### ISSUE TITLE
Converting back to XML from JSON (XML->JSON->XML) gives incorrect result

### ISSUE THREAD

**Issue by Ysgorg** [NaturalIntelligence/fast-xml-parser#284]
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

I have some XML, which I convert to JSON. I then convert it back to XML. For both operations I use fxp with the same options, where I set `ignoreAttributes: false`. The JSON I obtain from the first operation is as expected. However when I feed this output JSON to your `j2xParser`, the output XML is not equivalent to the original XML input. Specifically, the attributes are represented as DOM elements. Additionally, if I set `arrayMode: "strict"`, the `#text` will also be represented as a an element. 

Notably, I do get the expected output in your online tool, with all the options disabled. However, I notice that not all your options are available in this tool, and I'm not sure what the hidden options are set to. 

### Input

```xml
<e x="y">t</e>
```

### Code

```js
const fxp = require("fast-xml-parser");
const srcXml = `<e x="y">t</e>`;
const options = {
  arrayMode: "strict",
  ignoreAttributes: false,
};
const asJson = fxp.parse(srcXml, options);
const jsonToXml = new fxp.j2xParser();
const outXml = jsonToXml.parse(asJson, {});
console.info({srcXml,outXml, asJson})
```

### Output

With `arrayMode: strict`: 

```js
{
  srcXml: '<e x="y">t</e>',
  outXml: '<e><#text>t</#text><@_x>y</@_x></e>',
  asJson: '{"e":[{"#text":["t"],"@_x":["y"]}]}'
}
```
Without `arrayMode: "strict": 
```js
{
  srcXml: '<e x="y">t</e>',
  outXml: '<e>t<@_x>y</@_x></e>',
  asJson: '{"e":{"#text":"t","@_x":"y"}}'
}
```
### expected data
With `arrayMode: strict`: 

```js
{
  srcXml: '<e x="y">t</e>',
  outXml: '<e x="y">t</e>',
  asJson: '{"e":[{"#text":["t"],"@_x":["y"]}]}'
}
```
Without `arrayMode: "strict": 
```js
{
  srcXml: '<e x="y">t</e>',
  outXml: '<e x="y">t</e>',
  asJson: '{"e":{"#text":"t","@_x":"y"}}'
}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
`arrayMode` is not integrated with JSON to XML parser yet. Plan is to integrate it in v4.

**Comment by Ysgorg** [comment]
Okay, great! Is there also a plan to support `ignoreAttributes: false`?

**Comment by amitguptagwl** [comment]
please check with `isArray` and `preserveOrder` in v4

**Comment by Ysgorg** [comment]
The input now matches the output, and the data is as expected. Thank you! 

Updated code:

```javascript
const { XMLParser, XMLBuilder } = require("fast-xml-parser");
const srcXml = "<e x=\"y\">t</e>";
const options = {
  ignoreAttributes: false,
  preserveOrder: true,
  isArray: ()=>false
}
const parser = new XMLParser(options);
const builder = new XMLBuilder(options);
const asJson = parser.parse(srcXml);
const outXml = builder.build(asJson);
console.log(JSON.stringify({srcXml, asJson, outXml},null,2))
```
Output:
```json
{
  "srcXml": "<e x=\"y\">t</e>",
  "asJson": {
    "e": [
      {
        "#text": "t"
      }
    ],
    "attributes": {
      "@_x": "y"
    }
  },
  "outXml": "<e x=\"y\">t</e>"
}
```
