### ISSUE TITLE
"Currently FXP fails to parse XML with attributes has ">" in the value."

### ISSUE THREAD

**Issue by strarsis** [NaturalIntelligence/fast-xml-parser#285]
According to the README, "Currently FXP fails to parse XML with attributes has ">" in the value.".
Can tolerance to this enabled, even with a performance penalty?

**Comment by amitguptagwl** [comment]
I have already fixed the issue. Sorry I missed to update the README. let me quickly remove that.

**Comment by strarsis** [comment]
@amitguptagwl: Thanks! This is very important!
