### ISSUE TITLE
Parse PI

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#294]
as requested in #62 

@amitguptagwl thanks for the quick reply. PI's do have a dedicated purpose, normally it is a connection between XML authors and the xml-aware application [1].

My use case is that I receive an XML from someone else. This author decided to use PI's to embed metadata of the XML. One could argue that the purpose of PIs is not related to metadata and the author could've chosen to embed that metadata in a real tag, but this is where we are and technically the author is complying with the XML standard.

Further, it seems to me that a parser reading a valid xml should return to me all the information in there, including the PI, which is part of XML standard. Sadly, as XML popularity declines it seems to me there are not many robust parsers out there who do take PIs into account as it may be more of an obscure use case in 2020, I've only found hobby parser projects that do keep PI's in the JSON output.

Regarding the desired format, I think continuing with fast-xml-parser standard would be best, that is, in similarity to using the attr keyword, the PIs could be packed as an array with a relevant keyword such as instr. They should follow the same nesting rules as attr if possible.

Let me know if this makes sense or if I can provide more specific examples.

[1] https://docstore.mik.ua/orelly/xml/xmlnut/ch17_02.htm

**Comment by amitguptagwl** [comment]
done in v4.0.0-beta.6

**Comment by KillerCodeMonkey** [comment]
@amitguptagwl seems like it does not work correctly in 4.0?:

An example i have an xml string with 

`<?xml version="1.0" encoding="UTF-8"?>`

I can parse it and if i use the parsed value to build xml again it is transformed to

`<?xml version="1.0" encoding="UTF-8"/>`

but shouldn't it be back transformed to `<?... ?>` and not `<? ... />` ?

**Comment by amitguptagwl** [comment]
Input
```xml
<?xml version="1.0"?>
<?elementnames <fred>, <bert>, <harry> ?>
<h1></h1>
```

output
```xml
<?xml   version="1.0"?>
<?elementnames   <fred>, <bert>, <harry>?>
<h1>
</h1>
```

**Comment by KillerCodeMonkey** [comment]
strange.

i only see our code snippet there

```TS
  const xml = `
<?xml version="1.0" encoding="UTF-8"?>
...
`

  const builder = new XMLBuilder({
    attributeNamePrefix: '',
    attributesGroupName: 'attr',
    textNodeName: 'text',
    ignoreAttributes: false,
    format: true,
    suppressEmptyNode: true
  })

  const parseOptions = {
    attributeNamePrefix: '',
    attributesGroupName: 'attr',
    textNodeName: 'text',
    ignoreAttributes: false,
    removeNSPrefix: false,
    allowBooleanAttributes: false,
    parseTagValue: true,
    parseAttributeValue: false,
    trimValues: true,
    parseTrueNumberOnly: false,
    arrayMode: false,
    alwaysCreateTextNode: true,
    numberParseOptions: {
      hex: true,
      leadingZeros: false
    }
  }

  const jsonObject = new XMLParser(parseOptions).parse(xml)

  return builder.build(jsonObject)
```

and this results really in `<?xml .... />...`

**Comment by amitguptagwl** [comment]
tried with preserve sequence?

**Comment by KillerCodeMonkey** [comment]
you mean preserveOrder?

**Comment by KillerCodeMonkey** [comment]
this leads to: 

```<?xml   attr="[object Object]"?>```

**Comment by amitguptagwl** [comment]
it's weird. But let me check again.

**Comment by amitguptagwl** [comment]
Try v4.0.1 with following changes in your code

* if you're using `preserveOrder` then don't use `attributesGroupName`. 
* Otherwise don't use `preserveOrder`

Let me know if it fixes your issue
