### ISSUE TITLE
Is there any risk that this library is vulnerable to XXE?

### ISSUE THREAD

**Issue by plumdog** [NaturalIntelligence/fast-xml-parser#295]
See https://en.wikipedia.org/wiki/XML_external_entity_attack and https://owasp.org/www-project-top-ten/2017/A4_2017-XML_External_Entities_(XXE).html

I can't find anything in the documentation one way or another.

**Comment by amitguptagwl** [comment]
I'll have to check the document you suggested. But there is not any known vulnerability yet from the implementation or external dependency perspective.

**Comment by amitguptagwl** [comment]
Without going much in detail;

> This attack occurs when XML input containing a reference to an external entity is processed by ....

This library syntactically parse the XML to JS Object without referencing to the external entity. So I don't see the chance for that.
