### ISSUE TITLE
stopNodes parameter doesn't prevent validation from failing if ignored node contains bad html

### ISSUE THREAD

**Issue by boriswexler** [NaturalIntelligence/fast-xml-parser#296]
* [ X] Are you running the latest version?
* [ X] Have you included sample input, output, error, and expected output? 
* [ X] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
I am using the parser to parse an html document that contains a news story, and want to avoid parsing the <body.content> tag, which contains the html of the news story.
### Input

The file is too large to include
### Code
```js
const options = {
  stopNodes: ['body.content'],
}
[...]
let result = parser.parse(fileData, options, true)
```

### Output

{
  err: {
    code: 'InvalidTag',
    msg: "Closing tag 'h2' is expected inplace of 'b'.",
    line: 55
  }
}
### expected data

I would expect no error since the referenced h2 tag is inside the <body.content> tag
I would expect 
**Would you like to work on this issue?**

- [ ] Yes
- [ X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
If you can provide some sample XML then it'll be helpful

**Comment by amitguptagwl** [comment]
Please check with v4.0.0-beta.3
