### ISSUE TITLE
Handle special characters such as '&amp;'

### ISSUE THREAD

**Issue by ishong** [NaturalIntelligence/fast-xml-parser#297]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
fast-xml-parser does not handle special characters of tag values.

I can use the option, but I think the default behavior can be changed.
```js
tagValueProcessor: (tagValue) => {
            return tagValue.replace(/&lt;/g, '<').replace(/&amp;/g, '&').replace(/&gt;/g, '>');
        },
```

### Input
```xml
<abc>a &amp; b</abc>
```

### Code
```js
parser.parse('<abc>a &amp; b</abc>', { trimValues: false, parseTrueNumberOnly: true });
```

### Output
```json
{
   "abc":"a &amp; b"
}
```

### expected data
```json
{
   "abc":"a & b"
}
```

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
HTML Ampersand Code are currently not supported. This feature is in plan to add along with more features for HTML like empty tag

**Comment by ishong** [comment]
Thank you. @amitguptagwl 
Three special characters must be escaped to meet the XML specification.
Ref. https://www.w3.org/TR/xml/#syntax
The `Validating XML` function also should meet this spec.

**Comment by gwicksted** [comment]
Note regarding original implementation in the *Description* listed above: do not do `&amp;` prior to other entity processing or it will incorrectly decode `&amp;gt;` to `>` when it should be `&gt;`.  You will also want to add an attrValueProcessor to process `&quot;` and `&apos;`.

Also, depending on what you're interfacing with, you may wish to implement `&#nnnn;` and `&#xhhhh` where `nnnn` is the unicode decimal representation of a character and `hhhh` is the unicode hexidecimal representation of a character.  These are variable-length up to 4 hexidecimal characters to support all of UTF-16.  I don't believe there is an official spec for UTF-32 in XML which can have up to 8 hexidecimal characters.  That said, most XML processing libraries send these characters verbatim using a well-known encoding (typically UTF-8), a UTF-16 BOM (typically found in UTF-16 files used to indicate little or big-endian UTF-16), or via the xml encoding preprocessor declaration.

**Comment by amitguptagwl** [comment]
Please check with v4.0.0-beta.3

**Comment by FunctionDJ** [comment]
@amitguptagwl
```
> builder.build({ f: { "@a": "a & b" } })
'<f><@a>a & b</@a></f>'
```
It doesn't encode the ampersand into `&amp;` in version `4.0.0-beta.5`

**Comment by amitguptagwl** [comment]
@FunctionDJ Builder supports following entities: `>`, `<`, `'`, `"`

**Comment by FunctionDJ** [comment]
Yeah that's unfortunate. The software i'm generating an XML for can't handle unescaped ampersands. I'll see if i can use the builder options to replace the ampersand, but right now i'm simply replacing all instances with a Regex, kinda dirty.
xml2js generates escaped ampersands, but it's a lot slower.

**Comment by amitguptagwl** [comment]
The reason parser needs to escape `&` so that it can't form an entity. This is not the case with FXP. Hence. we've avoided unnecessary replacement. However, I'll include that in next version soon. Till then, you can achieve that using attribute or tag value processors, I believe.

**Comment by FunctionDJ** [comment]
@amitguptagwl Thank you very much!! The regex replace works for my current case, but using a processor is definitely a better idea.
