### ISSUE TITLE
Preserve comments and whitespaces

### ISSUE THREAD

**Issue by fkirc** [NaturalIntelligence/fast-xml-parser#299]
Dear maintainers and fast-xml community,

I am currently experimenting to adopt `fast-xml-parser` for `attranslate`, a new tool for translating websites and apps: https://github.com/fkirc/attranslate

A goal of `attranslate` is to modify existing XML-files with as little changes as possible.
Therefore, one feature that is critical for `attranslate` is the preservation of existing XML-comments and whitespaces.
However, it seems that `fast-xml-parser` discards or ignores all XML-comments during parsing?

Could you point me in a direction on how to preserve XML-comments and whitespaces?

**Comment by amitguptagwl** [comment]
Currently there is no provision. But let me understand your need in detail. 

1. Do you want to keep comments as an additional property of result object like we are setting `text` currently?
2. Can you give some examples for different scenarios with your expectations? For example, multiple continuous white spaces, new line char etc.

**Comment by fkirc** [comment]
> Currently there is no provision. But let me understand your need in detail.
> 
> 1. Do you want to keep comments as an additional property of result object like we are setting `text` currently?

I would like to keep comments in a reversible way, probably on a per-node-basis. The point is to read an XML-file, change the natural language of "values", but keep comments as is.

> 2. Can you give some examples for different scenarios with your expectations? For example, multiple continuous white spaces, new line char etc.

All of those scenarios are relevant
In all of those scenarios, I aim to preserve the original structure as much as possible.

**Comment by amitguptagwl** [comment]
A comment can appear on many places. This is just for an example to understand your need properly;

```xml
<!-- comment -->
<tag attr=""> some value <!-- comment --> <!-- <nested> leave it</nested> --> </tag>
<!-- comment -->
```

**Comment by fkirc** [comment]
For attranslate, I would say that "freestanding comments" are the most important comments.
Nevertheless, I would also like to preserve nested comments.

**Comment by amitguptagwl** [comment]
I'll have to think about the proper output object structure in this or other cases.

**Comment by WebRTCGame** [comment]
Comment parsing and placement would be great.  The xml files I'm trying to work with are ~50% comments, so currently not useable via fast-xml-parser without that being stripped out.

**Comment by Zireael** [comment]
> A comment can appear on many places. This is just for an example to understand your need properly;
> 
> ```
> 
> <tag attr=""> some value   </tag>
> 
> ```

example input:

```xml
<?xml version="1.0"?>
<any_name>
<!-- comment A -->
<tag attr="BLUE"> some value <!-- comment B --> 
<!-- <nested> leave it</nested> --> 
</tag>
<!-- comment C -->
</any_name>

```

example output:

```JSON
{
    "any_name": {
        "#text": ["\n", "\n", "\n", "\n"],
        "comment": [" comment A ", " comment C "],
        "order": ["#text[0]", "comment[0]", "#text[1]", "tag", "#text[2]", "comment[1]", "#text[3]"],
        "tag": {
            "#text": [" some value  \n \n", "\n", "\n"],
            "@_attr": "BLUE",
            "comment": [" comment B ", " <nested> leave it</nested> "],
            "order": ["#text[0]", "comment[0]", "#text[1]", "comment[1]", "#text[2]"]
        }
    }
}
```

Notes:
1) breaking change: #text will return an array of texts rather than a single string
2) new key: "comment" is an array of comments parsed from current node level
3) new key: "order": an array holding order of elements within current node. Unique keys are named as they are. Entities that can appear many times within the same node (free text, comments) are referenced  with their position within array of that element (i.e. `"comment[1]"`)
4) If there is need to preserve order of other elements (like attributes or CDATA), those could be grouped into a category that is an array (i.e. attribute: `[ { key: "attr", value: "BLUE" } ]` )

With the above changes, the structure of the original XML can be better presented and the original XML document could be perfectly rehydrated 1:1. 

![image](https://user-images.githubusercontent.com/3856578/105618297-8a0a0480-5ddd-11eb-9979-809fea311987.png)

**Comment by infacto** [comment]
Search the web for `xml:space="preserve"`. But not sure if this is a standard and not sure if this is a great idea. In SVG (also XML) it's deprecated in favor of css `white-space`. In the most of cases we don't want leading or trailing spaces. So the default XML parsing ignores the spaces (trims the value).

If you want spaces, you should use [CDATA](https://en.wikipedia.org/wiki/CDATA).

```xml
<my-tag> <![CDATA[   ]]> </my-tag>
```

In this case: 3 spaces (as dots: `<![CDATA[...]]>`)
This works with this parser. (tested read only).

**Comment by TaroXin** [comment]
I found a library that is better adapted and also supports `comments` parsing, https://github.com/oozcitak/xmlbuilder2

**Comment by bittlingmayer** [comment]
We also require this.

We generally can just pass it as an option.
```
parse(
`<tag xml:space="preserve">Line 1
Line 2</tag>`,
xmlSpace: 'preserve',
true);
```

Ideally, the `xml:space="preserve"` spec should be implemented.

```
parse(
`<tag xml:space="preserve">Line 1
Line 2</tag>`,
{},
true);
```

(Expected value in both cases: `'Line 1\nLine 2'`).

Otherwise we'll have to move away.

**Comment by amitguptagwl** [comment]
Comments support is provided in v4.0.0-beta.1
