### ISSUE TITLE
parse fail to get attribute

### ISSUE THREAD

**Issue by nicolasandrieux** [NaturalIntelligence/fast-xml-parser#3]
Hi,

when I try to parse string like `<tagname prop1="prop1" />`the parser fail to get the property

`fastXmlParser.parse('<tagname prop1="prop1" />')` return empty object  
`fastXmlParser.parse('<tagname prop1="prop1"></tagname>')` return expected object

There is any option I'm missing?
I currently use those options:
```
parserOptions = {
        attrPrefix : "__",
        textNodeName : "#text",
        ignoreNonTextNodeAttr : false,
        ignoreTextNodeAttr : false,
        ignoreNameSpace : false
    }
```

**Comment by amitguptagwl** [comment]
Thanks @nicolasandrieux to find it out. I'll check it in few hours.

**Comment by amitguptagwl** [comment]
Fixed and publish. Kindly use 2.3.1
