### ISSUE TITLE
Parse attr failed when the attr text has "="

### ISSUE THREAD

**Issue by zeng450026937** [NaturalIntelligence/fast-xml-parser#30]
const xml = `<issue entity="Mjg2MzY2OTkyNA==" state="partial" version="1"></issue>`
fastXmlParser.parse(xml, {
    attrPrefix : "@",
    attrNodeName: false,
    textNodeName : "#text",
    ignoreNonTextNodeAttr : false,
    ignoreTextNodeAttr : false,
    ignoreNameSpace : false,
    ignoreRootElement : false,
    textNodeConversion : true,
    textAttrConversion : false,
    arrayMode : false
});

**Comment by amitguptagwl** [comment]
Thanks to raise an issue. Though I have fixed it by a small change. But I'm working rewriting validator to handle this issue and to handle very long strings (in MBs) which may take some time.

**Comment by amitguptagwl** [comment]
Fixed. Please use 2.9.0 or later
