### ISSUE TITLE
Unsafe "for x in y" causes prototype extensions to be parsed

### ISSUE THREAD

**Issue by mauritslamers** [NaturalIntelligence/fast-xml-parser#301]
In the file linked below, a for-in loop exists in which is not checked whether the key that is being used is part of the object itself or the prototypal chain. This causes items of the prototypal chain to be included when parsing XML files. If for some reason Array.prototype has been altered, this for-in loop results in taking values from the array which are not indexed items.

https://github.com/NaturalIntelligence/fast-xml-parser/blob/396ab96f8bd1f9953cfeff6c6b630396dd5f045a/src/node2json.js#L31

I ran across the error using 'webdav', which uses fast-xml-parser as a dependency (see the exact problem, if relevant at https://github.com/perry-mitchell/webdav-client/issues/227).

**Comment by amitguptagwl** [comment]
I always classic style for loop. I didn't even remember why did I use `for..in` loop on some places. So the plan is to remove old `for..in` loop in next version.

**Comment by amitguptagwl** [comment]
@mauritslamers do the issue still exist? Or shall I close this issue?

**Comment by amitguptagwl** [comment]
closing this issue. please reopen is you still find its not working
