### ISSUE TITLE
Adding SwissDevJobs as a user

### ISSUE THREAD

**Issue by Vrq** [NaturalIntelligence/fast-xml-parser#302]
Hi, we also started using your parser for our XML job feeds and it works very smooth!

Feel free to add us to the user list:

- SwissDevJobs
- https://swissdevjobs.ch
- Link to the logo: [logo](https://static.swissdevjobs.ch/logo-images/swissdev-logo-name-square-small.png)

**Comment by amitguptagwl** [comment]
Thanks for using this library. I've added the entry in [USERs](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/USERs.md). 

I hope I can also get the job from your portal :)
