### ISSUE TITLE
Remove namespace keys as well with ignoreNamespace

### ISSUE THREAD

**Issue by Delagen** [NaturalIntelligence/fast-xml-parser#31]
Source
```
<a:root xmlns:a="urn:none">
	<a:b>2</a:b>
</a:root>
```
Result:
```
{
  root: {
    $:  { a: "urn:none" }, <--
    b:"2"
  }
}
```

**Comment by Delagen** [comment]
#32

**Comment by amitguptagwl** [comment]
Umm, sorry if I'm missing some point. But I never seen namespace with attribute's value. Can you please give me some reference from w3 or wikipedia? I would be interested to know more about it as I may have to update the validator and may have to handle some negative scenarios.

**Comment by Delagen** [comment]
@amitguptagwl for example http://www.xmlplease.com/xml/attributexmlns/
Namespace can be specified as simply `xmlns` attribute for element cause it default for self and children  and even can be specified for single attribute.
So I offer to remove `xmlns` attribute as well in ignoreNamespace mode

**Comment by amitguptagwl** [comment]
Currently when we ignoreNamespace

input XML
```
<xp:products xmlns:xp="http://www.xmlplease.com">
   <xp:product id="p1"/>
</xp:products>
```
Output JSON
.```
{
    "products": {
        "xp": "http://www.xmlplease.com",
        "product": {
            "id": "p1"
        }
    }
}
```
What should be output after your changes?

**Comment by Delagen** [comment]
With this the same ))

**Comment by amitguptagwl** [comment]
I appreciate your effort for the changes. But I believe this change may impact many projects who are already using this library. So until there are some users who want this change explicitly, we should avoid it.

**Comment by Delagen** [comment]
@amitguptagwl if we remove namespaces from all elements and from all attributes, what the purpose of namespace values in output? Using this namespace urls we still cannot differ namespaced elements & attributes from plain, but can make some incosistence with attributes in output, that does not make any meaning in output

**Comment by Delagen** [comment]
@amitguptagwl 
For example:
Valid XML
```xml
<root attr="value" xmlns:attr="urn:none">1</root>
```
Code:
```javascript
parser.parse(xml,{ignoreTextNodeAttr : false, ignoreNameSpace : true})
```
Current output:
```json
{"root":{"@_attr":"urn:none","#text":1}}
```
PR output:
```
{"root":{"@_attr":"value","#text":1}}
```

**Comment by amitguptagwl** [comment]
I agree with you.

**Comment by amitguptagwl** [comment]
Thanks you took care of tests and browser lib js file. I'll publish the changes soon.

**Comment by Delagen** [comment]
@amitguptagwl Thanks to you for offer this parser to everyone

**Comment by ahmed-sigmalux** [comment]
Did anything come of this?
