### ISSUE TITLE
Allow parsing of XML comments

### ISSUE THREAD

**Issue by Zireael** [NaturalIntelligence/fast-xml-parser#312]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Please allow parsing [XML comments](https://www.tutorialspoint.com/xml/xml_comments.htm).
`<!-- I am an XML comment -->`
### Input
```
<?xml version = "1.0" encoding = "UTF-8" ?>
<!--Students grades are uploaded by months-->
<class_list>
   <student>
   	<!--Student details-->
   	<!--A second comment-->
   	<name>Tanmay</name>
   	<grade>A</grade>
   </student>
</class_list>
```

### Code
https://naturalintelligence.github.io/fast-xml-parser/

### Output
```JSON
{
    "class_list": {
        "student": {
            "name": "Tanmay",
            "grade": "A"
        }
    }
}

```
### expected data
```JSON
{
    "comment": ["Students grades are uploaded by months"],
    "class_list": {
        "student": {
                "comment": ["Student details", "A second comment"],
                "name": "Tanmay",
                "grade": "A"
        }
    }
}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Can you please check #299 and suggest the output accordingly for different scenarios?

**Comment by Zireael** [comment]
> Can you please check #299 and suggest the output accordingly for different scenarios?

Sure, I added some mock input/output and my ideas how this could be achieved in that thread [https://github.com/NaturalIntelligence/fast-xml-parser/issues/299#issuecomment-766252281](https://github.com/NaturalIntelligence/fast-xml-parser/issues/299#issuecomment-766252281)

**Comment by amitguptagwl** [comment]
done
