### ISSUE TITLE
Cariage return entities are not parsed correctly

### ISSUE THREAD

**Issue by ffMathy** [NaturalIntelligence/fast-xml-parser#314]
Latest version.

If I have some XML: `<xml>foo&#xD;</xml>`, it doesn't parse the "\r" correctly.

**Comment by amitguptagwl** [comment]
@ffMathy Can you please include actual and expected result? So I can guide you better.

**Comment by amitguptagwl** [comment]
Closing as no response. Please feel free to reopen it if you still face the problem.
