### ISSUE TITLE
Processing instruction validation error

### ISSUE THREAD

**Issue by guerrap** [NaturalIntelligence/fast-xml-parser#317]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Im trying to validate an XML that uses a PI tag at a non-top level, but the validation fails. This [tool](https://onlinexmltools.com/validate-xml) correctly validates the XML, but the `fast-xml-parser` online tool doesn't. Is there a way to ignore those tags? Or this is the expected result?

### Input
```
<?xml version="1.0" encoding="utf-8"?>
<Content><?tibco-char 19?> content</Content>
```

### Code
```js
validate('<?xml version="1.0" encoding="utf-8"?><Content><?tibco-char 19?> content</Content>`);
```

### Output
```
{
    err: { code: 'InvalidChar', msg: "char 'c' is not expected.", line: 2 }
}
```

### expected data
```
true
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Let me check
