### ISSUE TITLE
How to get the XML declaration?

### ISSUE THREAD

**Issue by MarcoDeT** [NaturalIntelligence/fast-xml-parser#325]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [ ] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

Is it possible to let generate an xml declaration when converting a json into xml?

 
### Code
```js
Include the code being used for parsing
```

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
With the current development, No!

**Comment by tomchen** [comment]
I too would love to see that feature. (related: #184)

But instead, if you really want to get XML declaration now, you have to use [xml-js](https://www.npmjs.com/package/xml-js) or other lib.

**Comment by MarcoDeT** [comment]
Or you just prepend the xml declaration to the parse result of this library.

**Comment by amitguptagwl** [comment]
Please check v4.0.0-beta.6
