### ISSUE TITLE
Incorrect parsing of numbers in e-notation (scientific notation)

### ISSUE THREAD

**Issue by peko** [NaturalIntelligence/fast-xml-parser#326]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Numbers in e-notation without an decimal separator, such as `1e2`, `1e-2`, are parsed incorrectly.

As I understand [the code](https://github.com/NaturalIntelligence/fast-xml-parser/blob/51cd0dc3002b8bc7520a4d5c536bd3e7e8711b7a/src/xmlstr2xmlnode.js#L108), the decision to parse value into float is made only by the presence of an '.', which is not enough in my opinion. 

This is a rather serious problem, because of it the data is distorted by orders of magnitude.

### Input
```xml
<?xml version="1.0"?>
<n>1e2</n>
<n>1e-2</n>
<n>1.0e2</n>
<n>1.0e-2</n>
```

### Code
```js
require("fast-xml-parser").parse("<n>1e2</n><n>1e-2</n><n>1.0e2</n><n>1.0e-2</n>")
```

### Output
```json
{ "n": [1, 1, 100, 0.01 ]}
```

### expected data
```json
{ "n": [ 100, 0.01, 100, 0.01 ] }
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
I've recently published [strnum](https://github.com/NaturalIntelligence/strnum) to handle parsing part externally. Please check and let me know if it handles your expectations. I'm planning to use it in FXP in few days.

**Comment by amitguptagwl** [comment]
From FXP v3.20.0, a new property `numParseOptions` is introduced, check [configuration](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/parseValue.md) to get desire result.
