### ISSUE TITLE
parse attr fails when attribute contains newline

### ISSUE THREAD

**Issue by HaroldPutman** [NaturalIntelligence/fast-xml-parser#33]
```
<element id="7" data="foo
bar" bug="true"/>
```

The data attribute does not show up. I assume this will be fixed with parsing change mentioned in  #30. The real life use case is an SVG file with embedded bitmap image that has an attribute like:
```
<image
  xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAExCA
...
Nhfphem9d9wxe/e73/XQdddd/4Vbb71Vn1neDN+LGvh/NgDkIaZnFBUAAAAASUVORK5CYII=
"/>
```

**Comment by amitguptagwl** [comment]
Thanks to highlight the issue. The fix for #30 was for incorrect validation/check on attribute name. I believe this may be failing as the RE for attribute value is written for single line. But I'll have to check for proper fix.

**Comment by amitguptagwl** [comment]
Though the fix is ready I'm wondering if the "\n" should be replaced with single space " " or no space "". Most of the converters replace it with single space " ", but it may break in case of the second example you have given.

**Comment by HaroldPutman** [comment]
I think that a single space is the correct substitution for the newline. In the case of base64 encoding, any amount of whitespace is ignored.
In the Interim, I was able to fix this by preprocessing the XML data:
```
  data = data.replace(/="[^"]*\n([^"]\n)*"/gm, (match) => {
      return match.replace(/\n/gm,' ');
  });
```

**Comment by amitguptagwl** [comment]
Thanks. I had published the changes along with some more fixes related to XML comments
