### ISSUE TITLE
Configuration to remove WhiteSpace values

### ISSUE THREAD

**Issue by trivikr** [NaturalIntelligence/fast-xml-parser#333]
### Is your feature request related to a problem? Please describe.
Currently, there is no direct configuration option to remove values which only contain whitespaces in fast-xml-parser.

### Describe the solution you'd like
An option to remove values which only contain whitespaces, say `removeWhitespaceValues`, which removes values which only contain whitespaces. This option can be implemented in the code as follows:

```diff
diff --git a/src/xmlstr2xmlnode.js b/src/xmlstr2xmlnode.js
index b330d13..cc3a02b 100644
--- a/src/xmlstr2xmlnode.js
+++ b/src/xmlstr2xmlnode.js
@@ -75,6 +75,9 @@ function processTagValue(tagName, val, options) {
     if (options.trimValues) {
       val = val.trim();
     }
+    if (options.removeWhitespaceValues && val.trim() === "") {
+      val = "";
+    }
     val = options.tagValueProcessor(val, tagName);
     val = parseValue(val, options.parseNodeValue, options.parseTrueNumberOnly);
   }
```

### Describe alternatives you've considered
Using tagValueProcessor option to provide a function which returns empty string if it's value after calling `.trim()` is an empty string:

```js
import { parse } from "fast-xml-parser";

const xmlData = `<Body>
  <DataToTrim>   </DataToTrim>
  <DataNotToTrim> content </DataNotToTrim>
</Body>`;

console.log(JSON.stringify(parse(xmlData), null, 2));

console.log(
  JSON.stringify(
    parse(xmlData, {
      trimValues: false,
      tagValueProcessor: (val, tagName) => (val.trim() === "" ? "" : val),
    }),
    null,
    2
  )
);
```

Output:

```console
{
  "Body": {
    "DataToTrim": "",
    "DataNotToTrim": "content"
  }
}
{
  "Body": {
    "DataToTrim": "",
    "DataNotToTrim": " content "
  }
}
```

### Additional context
This came up as a requirement in AWS SDK for JavaScript (v3) in https://github.com/aws/aws-sdk-js-v3/issues/1893

**Comment by amitguptagwl** [comment]
Not sure what actually you're looking for. But option `trimValues` can be used to trim a value and set it to blank if only whitespaces are in the value. Feel free to reopen the issue if you feel this doesn't answer your question.
