### ISSUE TITLE
parseTrueNumberOnly = true does only work if the element to parse has but one leading zero

### ISSUE THREAD

**Issue by Reggae13** [NaturalIntelligence/fast-xml-parser#338]
* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When parsing xml-files with the option "parseTrueNumberOnly: true" everything works fine if the data only contains tags with but one leading zero. Whenever there are tags with more than one leading zero all leading zeros are ignored. (See the tag "xCADNummer" of the following xml-Data.)
### Input
```xml
 <ttBDE_ExportRow>
    <Firma>03</Firma>
    <Auftrag>42002867-117-1</Auftrag>
    <RueckMeldeNr>26849540</RueckMeldeNr>
    <xEtage>1L5</xEtage>
    <xRaum>05-14</xRaum>
    <xWaldnerPos>F00070601</xWaldnerPos>
    <xCADNummer>0006</xCADNummer>
    <Baugruppe>P117-1</Baugruppe>
    <BaugruppeBez>Materialanker</BaugruppeBez>
    <BaugruppeBez/>
    <BaugruppeBez/>
    <BaugruppeBez/>
    <Produktionsmenge>1.000</Produktionsmenge>
    <ArtikelGruppe>999999</ArtikelGruppe>
    <ArtikelGruppeBez>Standardgruppen</ArtikelGruppeBez>
    <Position>85</Position>
    <Artikel>81017202</Artikel>
    <ArtikelBez>Medienzelle WT PST</ArtikelBez>
    <ArtikelBez>Tischtiefe 900 Zellenhöhe1790</ArtikelBez>
    <ArtikelBez/>
    <ArtikelBez>Ersatz für 81006532  QM1262</ArtikelBez>
    <ArtikelArt>7</ArtikelArt>
    <Bedarfsmenge>1.000</Bedarfsmenge>
    <MengeKurzBez>St</MengeKurzBez>
    <MengeBez>Stück</MengeBez>
    <AktPos>340</AktPos>
    <BasisRessource>315600</BasisRessource>
    <IdentStk>233404203</IdentStk>
    <IdentAkt>91238023</IdentAkt>
    <LagerOrt/>
    <LagerPlatz/>
    <StartTermin>2021-04-20</StartTermin>
    <EndTermin>2021-04-20</EndTermin>
    <Stueckzeit>0.00</Stueckzeit>
    <BRes_AltResGr>315600</BRes_AltResGr>
  </ttBDE_ExportRow>
```
### Code
```js
const importRow = async function (rowJson, columns, importMap) {
					const rowToImport = {};
					try {
						columns.recordset.forEach(async function (item) {
							const getMapObjectVal = async function (mapObject) {
								let retVal = [];
								for (let key in mapObject) {
									retVal = [key, mapObject[key]];
								}
								return retVal;
							};
							if (Object.prototype.hasOwnProperty.call(importMap, item.COLUMN_NAME)) {
								if (importMap[item.COLUMN_NAME] === Object(importMap[item.COLUMN_NAME])) {
									const rowVal = await getMapObjectVal(importMap[item.COLUMN_NAME]);
									rowToImport[item.COLUMN_NAME] = rowJson[rowVal[0]][rowVal[1]];
								} else {
									rowToImport[item.COLUMN_NAME] = item.DATA_TYPE === 'int' ? parseInt(rowJson[importMap[item.COLUMN_NAME]]) : rowJson[importMap[item.COLUMN_NAME]];
								}
							} else {
								if (Object.prototype.hasOwnProperty.call(rowJson, item.COLUMN_NAME)) rowToImport[item.COLUMN_NAME] = rowJson[item.COLUMN_NAME];
							}
						});
						return rowToImport;
					} catch (error) {
						throw new Error(error);
					}
				};
```
### Output
the content of the tag "xCADNummer" is written without leading zeros into the database although the field-type is character.

### expected data
the content of the tag "xCADNummer" should be written with all leading zeros into the database ( it should be 0006 according to the xml-data.

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by nareshy-menlo** [comment]
I have the same issue. Looking for update.

**Comment by wayson** [comment]
I'm having the same issue. It seems I've to find something else to resolve the issue.

**Comment by MacZel** [comment]
I'm also having this issue. Didn't find any solution, had to switch to xml2js

**Comment by amitguptagwl** [comment]
I've recently published [strnum](https://github.com/NaturalIntelligence/strnum) to handle parsing part externally. Please check and let me know if it handles your expectations. I'm planning to use it in FXP in few days.

**Comment by amitguptagwl** [comment]
From FXP v3.20.0, a new property `numParseOptions` is introduced, check [configuration](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/parseValue.md) to get desire result.
