### ISSUE TITLE
Not preserving the order for nested text node

### ISSUE THREAD

**Issue by EggTronic** [NaturalIntelligence/fast-xml-parser#339]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input
\<p>before \<strong>middle1\</strong>\<strong>middle2\</strong> after\</p>

### Code
```js
  const xmlObj = xmlParser.parse(xml, {
    ignoreAttributes: false,
    arrayMode: false,
  })
```

### Output

{"p":
  {"#text":"beforeafter",
   "strong":["middle1","middle2"]
  }
}

### expected data

I would expect the order of the text to be preserved.
But the above output breaks the text order. ("before" and "after" should not be merged)

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
This feature is already in discussion #244 to be implemented in v4

**Comment by amitguptagwl** [comment]
`preserveOrder` can be used with fxp v4 to deal such situations
