### ISSUE TITLE
parse content in cdata has error

### ISSUE THREAD

**Issue by rugbbyli** [NaturalIntelligence/fast-xml-parser#34]
look this example:
```
<xml>
<a>text</a>
<b>
    text
</b>
<c>
    <![CDATA[text]]>
</c>
<d><![CDATA[text]]></d>
</xml>
```

the parse result was:
```
{
    "xml": {
        "a": "text",
        "b": "     text\n",
        "c": null,
        "d": "text"
    }
}
```

as above shown, when cdata tag was start in newline, the parse result was null.

i wonder if it was a bug or my wrong usage ? i just use the default options.

**Comment by amitguptagwl** [comment]
Thanks to report this bug.

**Possible issue**: Not considering white spaces before / after CDATA

**Comment by amitguptagwl** [comment]
Fixed. Please use the v2.9.2 or later

**Comment by rugbbyli** [comment]
Thanks, would try it later.

**Comment by rugbbyli** [comment]
Has tested, working as expectedly, thanks!
