### ISSUE TITLE
Parser does not parse carriage return `&#xD;` correctly

### ISSUE THREAD

**Issue by trivikr** [NaturalIntelligence/fast-xml-parser#342]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

Parser does not parse carriage return `&#xD;` correctly

### Code
```js
import { parse } from "fast-xml-parser";

console.log(
  parse(`
<?xml version="1.0"?>
<Body>hello&#xD;
world</Body>`)
);
```

### Output
```console
{ Body: 'hello&#xD;\nworld' }
```

### expected data
```console
{ Body: 'hello&\r\nworld' }
```

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
please check v4.0.0-beta.4
