### ISSUE TITLE
Parser does not parse carriage return `&lt;` and `&gt;` 

### ISSUE THREAD

**Issue by trivikr** [NaturalIntelligence/fast-xml-parser#343]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

Parser does not parse carriage return `&lt;` and `&gt;` correctly

### Code
```js
import { parse } from "fast-xml-parser";

console.log(
  parse(`
<?xml version="1.0"?>
<Body>Invalid email address&lt;abc123&gt;.</Body>`)
);

```

### Output
```console
{ Body: 'Invalid email address&lt;abc123&gt;.' }
```

### expected data
```console
{ Body: 'Invalid email address<abc123>.' }
```

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by trivikr** [comment]
Related: https://github.com/NaturalIntelligence/fast-xml-parser/issues/297

**Comment by amitguptagwl** [comment]
Please check with v4.0.0-beta.3
