### ISSUE TITLE
FR: Line numbers of nodes

### ISSUE THREAD

**Issue by mcpiroman** [NaturalIntelligence/fast-xml-parser#345]
I'd be helpful to have a line number recorded for each element (and potentially attribute? - not in my usacase though), e.g. for higher level validation. In my case it is perfectly fine to have that only on the traversal object, not json, just alongside `tagname` and `val`. I assume that's quite trivial given there are already line numbers returned by the validation process.

**Comment by amitguptagwl** [comment]
do you mean displaying line number in case of validation fails?

**Comment by mcpiroman** [comment]
Yees, but a a custom validation of the data, at the use side, not just a parse-time. For broader usage you could also save a full-blown span (line,column,index/start,end), but for me just the line number is fine.

**Comment by amitguptagwl** [comment]
@mcpiroman can you please confirm in which case you're not getting line number? After recent changes in the parser, you can notice column number in many cases.

**Comment by amitguptagwl** [comment]
closing the issue. Please reopen if issue still exist
