### ISSUE TITLE
example has syntax error

### ISSUE THREAD

**Issue by abiriadev** [NaturalIntelligence/fast-xml-parser#348]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output?
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### description

**this issue is not about bug or code**

I just found problematic example in [README.md file](https://github.com/NaturalIntelligence/fast-xml-parser#xml-to-json) and [npm page](https://www.npmjs.com/package/fast-xml-parser#xml-to-json)

the problematic code is below. and it was taken from the top of the [xml to json part](https://github.com/NaturalIntelligence/fast-xml-parser#xml-to-json)

```js
var jsonObj = parser.parse(xmlData [,options] );
```

I was run this code and found this error.

```sh
var jsonObj = parser.parse(xmlData [,options] );
                                    ^       

SyntaxError: Unexpected token ','
```

I believe that code means `(xmlData, [options] );` , not `(xmlData [,options] );`.

and it runs perfectly expected.

so I believe that code is just a typo, and should be fixed.

#### or if I am wrong

I couldn't found an issue template or another way to report about typo of example code,
so I just opened a blank issue.

and this is not about *'bug report or unexpected output'*.

if I must report this another way,
please tell me how and where.

and finally, this issue is confirmed to be true, then I'll send a PR.

 
### Input

sample xmlData: 

```xml
<p>Lorem ipsum Nulla accusantium vel perspiciatis perspiciatis quas.</p>
```

### Code
```js
const xmlData = '<p>Lorem ipsum Nulla accusantium vel perspiciatis perspiciatis quas.</p>'

var parser = require('fast-xml-parser')
var he = require('he')

var options = {
    attributeNamePrefix: '@_',
    attrNodeName: 'attr', //default is 'false'
    textNodeName: '#text',
    ignoreAttributes: true,
    ignoreNameSpace: false,
    allowBooleanAttributes: false,
    parseNodeValue: true,
    parseAttributeValue: false,
    trimValues: true,
    cdataTagName: '__cdata', //default is 'false'
    cdataPositionChar: '\\c',
    parseTrueNumberOnly: false,
    arrayMode: false, //"strict"
    attrValueProcessor: (val, attrName) =>
        he.decode(val, { isAttributeValue: true }), //default is a=>a
    tagValueProcessor: (val, tagName) => he.decode(val), //default is a=>a
    stopNodes: ['parse-me-as-string'],
}

var jsonObj = parser.parse(xmlData [,options] ); //! this line

console.log(JSON.stringify(jsonObj, null, 2));
```

### Output

```sh
var jsonObj = parser.parse(xmlData [,options] );
                                    ^       

SyntaxError: Unexpected token ','
```

### expected data

```json
{
  "p": "Lorem ipsum Nulla accusantium vel perspiciatis perspiciatis quas."
}
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Sorry for the confusion. But I mean with `[,options]` is that passing options to parser is optional.
