### ISSUE TITLE
Creating tag/release on GitHub each time you release a new version on NPM

### ISSUE THREAD

**Issue by j0k3r** [NaturalIntelligence/fast-xml-parser#35]
My project got some validation problem on some XML using 2.9.* version of your library.
2.8.* is working great.

Since you didn't create tag or release on GitHub I can't compare what changed on your side to understand why parsing is failing.

Could you create tag / release on GitHub each time you release a new version on NPM? At least for future release because I guess it'll be hard for previous release.

Thanks.

**Comment by amitguptagwl** [comment]
Thanks, it's a good suggestion. Even I thought about it before 2nd last release but missed because I got stuck with other work. 

I really feel sorry if I made your build red. I'll definitely create the changelogs soon. For the time being you can check the commit history, or you can tell me what is basically breaking. So I may help to figure out the issue.

**Comment by j0k3r** [comment]
I'll open a different issue about the problem :wink:

**Comment by amitguptagwl** [comment]
Yeah sure :)

**Comment by amitguptagwl** [comment]
Changelog added

**Comment by j0k3r** [comment]
You still haven't create a release or a tag on GitHub: https://github.com/NaturalIntelligence/fast-xml-parser/releases

**Comment by amitguptagwl** [comment]
I read it somewhere that git automatically tag npm repo as per version mentioned in package.json. Let me check that if it doesn't work

**Comment by amitguptagwl** [comment]
Check if this work for you git@github.com:NaturalIntelligence/fast-xml-parser.git#v2.9.0

**Comment by j0k3r** [comment]
Well you should create a tag on git and then publish it to GitHub and it'll appear here: https://github.com/NaturalIntelligence/fast-xml-parser/tags

You can choose to:
- manually create a release on GitHub each time you publish to npm: https://help.github.com/articles/creating-releases/
- manually create a tag on your git repo and then publish it to GitHub: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by amitguptagwl** [comment]
Thanks @j0k3r .  Yes it can be good practice for github users/visitors. But will do it next time.

**Comment by j0k3r** [comment]
Great, you can still create a release right now and name it 2.9.3 :wink: 
Also, you forgot the 2.9.3 information in the changelog

**Comment by amitguptagwl** [comment]
You'll not let me lazy :laughing:

**Comment by robations** [comment]
@amitguptagwl If you run `npm version x.y.z` it creates a commit that updates package.json with the new version number, and also tags that commit.

You may need to explicitly push the tags with (for example) `git push --follow-tags` (unless git changed behaviour). Also possible to [set this as the default](https://git-scm.com/docs/git-config#git-config-pushfollowTags).

The latest version I can see in npm is 3.12.5 but the last tag was 3.10.0 :)

**Comment by amitguptagwl** [comment]
Though I'm not against in releasing on github as soon as we release on npm. But I didn't find anything valuable in last few releases to make me releasing on github. Please check CHANGELOG.md for more detail. However I'll take care it in future.

**Comment by robations** [comment]
Thanks Amit, I sometimes do random checks when updating dependencies to see if there is anything I should know, I will check out CHANGELOG.md.
