### ISSUE TITLE
Failure to recognize xml attributes without whitespace (but with line breaks)

### ISSUE THREAD

**Issue by ttu-ttu** [NaturalIntelligence/fast-xml-parser#350]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

fast-xml-parser does not treat attributes separated by (only) line breaks as attributes.

### Input
```xml
<?xml version="1.0"?>
<abc
attrA="2"
>
value
</abc>
```
### Code
```js
parser.parse(`<?xml version="1.0"?>
<abc
attrA="2"
>
value
</abc>`, {
  ignoreAttributes: false,
});
```

### Output

```json
{
    "abc\nattrA=\"2\"\n": "value"
}
```

### expected data

```json
{
    "abc": {
        "#text": "value",
        "@_attrA": "2"
    }
}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
You should have a space more than a `\n` between tag name and attribute to make it work. I don't see that case here. Please confirm.

**Comment by ttu-ttu** [comment]
Yeah the point of this issue is to point out that the parser doesn't support attributes that are separated using line breaks (as in it'll treat it as part of the tag)
e.g. `<?xml version="1.0"?><abc\nattrA="2"\n>value</abc>`

Which seem to work differently from some other parsers which accepts line breaks as a way of separation (tested on [Java's XML parser](https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilder.html), and some IDE's syntax highlights like IntelliJ and Visual Studio Code)

I personally am not sure if it's part of the specification to support this format, or those parsers are just being lenient about it.

Also, the above code is a simplified XML of what users may upload to my site, so technically I would have to manually fix their XML (or reject it), if it's formatted this way

**Comment by amitguptagwl** [comment]
Thanks. @ttu-ttu . We can probably consider it as a feature request this time. and check later if this is really needed.

**Comment by amitguptagwl** [comment]
done in v4
