### ISSUE TITLE
Different variable types depends on input

### ISSUE THREAD

**Issue by w3ggy** [NaturalIntelligence/fast-xml-parser#361]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Different types of the field in JSON depends on input data. How to handle it properly? (Cast to an array with 1 or multiple items inside)
### Input
Sample of the XML file: 

```
<?xml version="1.0" encoding="UTF-8" ?> 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>	
    <Duration>
      <days>365</days>
    </Duration>
    <Duration>
      <days>365</days>
      <days>120</days>
    </Duration>
  </soap:Body>
</soap:Envelope>
```

In the online tool https://naturalintelligence.github.io/fast-xml-parser/ (and in the library of course) I receive the following JSON:

```
{
    "soap:Envelope": {
        "soap:Body": {
            "Duration": [
                {
                    "days": 365
                },
                {
                    "days": [
                        365,
                        120
                    ]
                }
            ]
        }
    }
}
```

But I don't understand why the type is changes depends on input? In the first object, I receive the result as the object and in the second object, I receive values as an array. Even if I set `arrayMode` to true, I receive the same issue (but wrapped in an additional array). I want to make this library provide an array in such a case even if there is only one item inside. Is it possible? Maybe there is some approach to how to handle it properly?

I see the only possible way is to use `any` and detect the type in runtime. But maybe I missed something?

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
@ w3ggy  `arrayMode` is not fully supported in current version. `v4` of this library handles it better. But I couldn't publish the changes yet due to incomplete tests.

**Comment by amitguptagwl** [comment]
`isArray` can be used with fxp v4 to deal such situations
