### ISSUE TITLE
[Question] Is there any way to generate XML comments using the j2xParser ?

### ISSUE THREAD

**Issue by emexal-company** [NaturalIntelligence/fast-xml-parser#372]
I would like to add a few comments to my generated XML. For example from the following JSON
```json
{
    "comment": "Cow",
    "animalId": 1,
}
```
The generated XML would be
```xml
<!-- Cow -->
<animalId>1</animalId>
```

Is there any way to perform this using the j2xParse ?

**Comment by amitguptagwl** [comment]
Never thought about it yet. It'll not be that simple too because of some edge cases. Eg repeated comment before each repeatable entry, comment before each property, ensuring comments order  etc.
