### ISSUE TITLE
textNodeName consistency

### ISSUE THREAD

**Issue by Opariti** [NaturalIntelligence/fast-xml-parser#38]
### Checklist

* [ ] Are you running the latest version?
* [ ] Include sample input XML 
* [ ] Include actual output
* [ ] Include expected output
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [ ] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

I have the following input

`<?xml version="1.0" encoding="UTF-8"?>
<x id="1" cmd="init" ses="">
  <i>A text inside 'i' tag<test id="999" name="new_user"/>
  </i>
  <j>Another inside 'j' tag</j>
  <k></k>
</x>`

Using the fast-xml-parser gives the following options:

'let options = {
        attrPrefix: "attr_",
        attrNodeName: true,
        textNodeName: "text_",
        ignoreNonTextNodeAttr: true,
        ignoreTextNodeAttr: false,
        ignoreNameSpace: false,
        ignoreRootElement: false,
        textNodeConversion: true,
        textAttrConversion: false,
        arrayMode: false
    };'

and the output is:

'{"x":{"i":{"text_":"A text inside 'i' tag","test":{"true":{"attr_id":"999","attr_name":"new_user"}}},"j":"Another inside 'j' tag","k":""}}'

My question is: while the text inside the 'i' tag is marked with 'text_', the one inside the 'j' tag is not.
I expected to have, for the 'j' tag:
"j":{"text_":"Another inside 'j' tag"}

Thanks

**Comment by amitguptagwl** [comment]
@Opariti The reason to include issue template is to understand the issue better instead of throwing random questions later. I have modified your comment to tick 2 options.

As you can see in the input XML, 'i' tag has one nested tag. It means 'i' is gonna be an object containing the nested tag as property.

```
{
    "x": {
        "i": {
            "test": ""
        },
        "j": "Another inside 'j' tag",
        "k": ""
    }
}
```

Now since it also has text value, you need some temporary property for text value.

```
{
    "x": {
        "i": {
           "text_": "A text inside 'i' tag",
            "test": ""
        },
        "j": "Another inside 'j' tag",
        "k": ""
    }
}
```

**Comment by Opariti** [comment]
Thanks, it answers my question
