### ISSUE TITLE
Generate option object configuration from https://naturalintelligence.github.io/fast-xml-parser/

### ISSUE THREAD

**Issue by kvetoslavnovak** [NaturalIntelligence/fast-xml-parser#391]
* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Would be great if https://naturalintelligence.github.io/fast-xml-parser/ could generate used Parsing options configuration as an  options =  { ... } object.
### Code
```js
Include the code being used for parsing
```

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
@kvetoslavnovak documentation can help you for different configuration. Demo doesn't have all the configuration.
