### ISSUE TITLE
no validate function

### ISSUE THREAD

**Issue by nicolasandrieux** [NaturalIntelligence/fast-xml-parser#4]
Hi,

I installed `fast-xml-parser` using `npm install fast-xml-parser` and there is no `validate` function in the object, only `convertToJson` , `getTraversalObj` and `parse` function.

I'm don't need it but just to warn you.

**Comment by amitguptagwl** [comment]
@nicolasandrieux Can you plz tell me how are you using validate function? As I'm able to use it in following way in my other project [Stubmatic](https://github.com/NaturalIntelligence/Stubmatic/blob/master/index.js);

```
var result = require('fast-xml-parser').validate(fs.readFileSync(fileName, {
				encoding: 'utf-8'
			}));
			if(result === true) console.log("Validated successfully");
```

Refer [this](https://naturalintelligence.github.io/fast-xml-parser/) for web example.

**Comment by amitguptagwl** [comment]
Closing as no answer
