### ISSUE TITLE
Decode HTML entities in text values

### ISSUE THREAD

**Issue by Delagen** [NaturalIntelligence/fast-xml-parser#40]
### Checklist

* [x] Are you running the latest version?
* [x] Include sample input XML 
* [x] Include actual output
* [x] Include expected output
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

I include PR soon

**Comment by amitguptagwl** [comment]
Published

**Comment by amitguptagwl** [comment]
I believe it should not parse HTML entities withing CDATA range.

**Comment by Delagen** [comment]
@amitguptagwl CDATA also can contain HTML entities

**Comment by amitguptagwl** [comment]
Yes. :) 
So what I expect from `<tag><![CDATA[&lt;sender&gt;John Smith&lt;/sender&gt;]]></tag>` is 

```
{
   "tag" : "&lt;sender&gt;John Smith&lt;/sender&gt;"
}
```

But what I'm getting from current parser is

```
{
   "tag" : "<sender>John Smith</sender>"
}
```

**Comment by Delagen** [comment]
> But what I'm getting from current parser is

And it's right

**Comment by amitguptagwl** [comment]
As per the [wiki](https://en.wikipedia.org/wiki/CDATA),

> Character data is character data, regardless of whether it is expressed via a CDATA section or ordinary markup. CDATA sections are useful for writing XML code as text data within an XML document.

 > if the numeric character reference `&#240;` appears in element content, it will be interpreted as the single Unicode character 00F0 (small letter eth). But if the same appears in a CDATA section, it will be parsed as six characters: ampersand, hash mark, digit 2, digit 4, digit 0, semicolon.

Above phrase in my words (understanding), 

> if `&#240;` (represents to &#240;) appears in CDATA section should not be parsed to &#240; but to `&#240;`  only.

**Comment by Delagen** [comment]
@amitguptagwl I will make some refactoring, and place PR tomorrow

**Comment by amitguptagwl** [comment]
Thanks @Delagen . In case if you are busy with some other prior work, we can just roll back the changes for the time being. And will handle them later. I'm anyhow planning to rewrite parser but it'll take at least a month :smile_cat:

**Comment by Delagen** [comment]
Thanks @amitguptagwl for work, I placed PR to not decode CDATA
But seems parser ignore sibling text when CDATA present
```
<a>
<![CDATA[asdf]]>a
</a>
```
result in:
```
{
"a":{
"#text":"asdf"
}
}
```

**Comment by amitguptagwl** [comment]
Sorry I'm holding this PR as I'm rewriting the parser So it'll become to handle this situation, large files, reduce time for separate validation etc. I'm 60% complete with the change. Will update you with the progress.

**Comment by Delagen** [comment]
Thanks for your project. I have a pleasure to contribute if project owner interested in making it code better. )

**Comment by amitguptagwl** [comment]
v3 is live to handle this issue
