### ISSUE TITLE
Option to allow boolean values with empty values 

### ISSUE THREAD

**Issue by UltraCakeBakery** [NaturalIntelligence/fast-xml-parser#402]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
The `allowBooleanAttributes` option causes all my boolean attributes to be build to: `foo="true"`. I do not want the `="true"` suffix. I just want to keep my boolean attribute a boolean attribute.

### Example Input
```xml
<fruit rotten></fruit>
```

### Code
```javascript
{ 
	preserveOrder: true,
	attributeNamePrefix: '@', 
	allowBooleanAttributes: true,
	ignoreAttributes: false
}
```

### Output
```xml
<fruit rotten="true"></fruit>
```

### expected data
```xml
<fruit rotten></fruit>
```

**Would you like to work on this issue?**
Not sure where to start. If it is an easy fix I happily do it. 

- [x] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Sorry, I couldn't understand your concern. Do you want XML builder to suppress boolean attributes. Check if [suppressBooleanAttributes](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/3.XMLBuilder.md#suppressbooleanattributes) can solve your problem.

**Comment by UltraCakeBakery** [comment]
> 

That is exactly the behavior I was lookin for! I was still using `4.0.0-beta.5`. I see you added that feature a couple hours ago in `4.0.0-beta.6`. I just updated and it works :)

I love this parser so far. I've tried others and none are as fast, stable and reliable as this one. Great work!
