### ISSUE TITLE
XMLValidator validates wrong XML code

### ISSUE THREAD

**Issue by ZsharE** [NaturalIntelligence/fast-xml-parser#405]
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Seems like this XML code is valid, but basically is not.
### Input
```xml
<parent>
  <child attri= bute="true" />
</parent>
```

### Code
```js
fxparser.XMLValidator.validate(theProvidedXMLHere);
```

### Output

TRUE, Valid XML

### expected data

Error

**Would you like to work on this issue?**

- [x] Yes
- [x] No

**Comment by amitguptagwl** [comment]
fixed in 4.0.0-beta.7

**Comment by ZsharE** [comment]
Just tested in v4.0.0-beta.8, the fix is not working.

**Comment by ZsharE** [comment]
Any update ?

**Comment by amitguptagwl** [comment]
@ZsharE please try with node js version. Browsers bundle are not generated yet. So most probably the cdn you are using is still using the old code with new version.

**Comment by ZsharE** [comment]
Yay! Works great after I bundle it with webpack.
Thanks !
