### ISSUE TITLE
`suppressEmptyUnpairedNode` ?

### ISSUE THREAD

**Issue by UltraCakeBakery** [NaturalIntelligence/fast-xml-parser#406]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

> I'm not sure if there is already a way of achieving what I want with the available options.

### Description
I'm trying to parse a HTML document. My html document contains empty `<div></div>` elements and also one unpaired `<br>`.

With XMLBuilding, the `suppressEmptyNode` option when set to `true` outputs one `<br>` which is good, but also turns all my `<div></div>`  into `<div/>`.  

I want the `<div></div>` to not turn into `<div/>` while also keeping just one `<br>`.

### Input
```html
<html>
	<body>
		<!-- empty, should stay as is -->
		<div style="background: red;"></div>

		<!-- br element, should stay unpaired-->
		<br>

		<!-- filled, should stay as is -->
		<div>Filled</div>

	</body>
</html>
```

### Code
```js
const ast = new XMLParser({
	preserveOrder: true,
	attributeNamePrefix: '',
	allowBooleanAttributes: true,
	suppressBooleanAttributes: true,
	ignoreAttributes: false,
	stopNodes: ['script', 'iframe'],
	unpairedTags: [ 'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr', 'textarea' ]
}).parse(html)

new XMLBuilder({
	preserveOrder: true,
	attributeNamePrefix: '',
	ignoreAttributes: false,
	suppressBooleanAttributes: true,
	unpairedTags: [ 'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr', 'textarea'],
	suppressEmptyNode: true
}).build(ast)
```

### Output
```html
<html><body><div style="background: red;"/><br><div>Filled</div></body></html>
```
### expected data
```html
<html><body><div style="background: red;"></div><br><div>Filled</div></body></html>
```

**Would you like to work on this issue?**
Depends on the complexity of the issue

- [X] Yes
- [X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by UltraCakeBakery** [comment]
Sorry, the additional `<head/>` element was added later programmatically. I've edited the issue so it only includes code relevant to the issue

**Comment by amitguptagwl** [comment]
Hmm, will have to add some option to differentiate them. will do and update you

**Comment by UltraCakeBakery** [comment]
> Hmm, will have to add some option to differentiate them. will do and update you

Thank you :)

**Comment by amitguptagwl** [comment]
it was a small change. Will publish it soon.
