### ISSUE TITLE
Create web bundle

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#409]
Need to fix webpack configuration so that it can work with latest webpack version.

Or 

Using some other bundler like parcel etc which can create webbundle, typescript bundle, and es6 module bundle.

**Comment by ZsharE** [comment]
You need to use **os-browserify**.
In ./src/xmlbuilder/orderedJs2Xml.js, change os with os-browserify.

```js
const {EOL} = require('os-browserify');
```
