### ISSUE TITLE
Is there a way to provide a tag name processor?

### ISSUE THREAD

**Issue by stravi** [NaturalIntelligence/fast-xml-parser#411]
* [X] I have gone through README. But nothing helped me.
* [X] I have gone through [spec](https://github.com/NaturalIntelligence/fast-xml-parser/tree/master/spec) folder. But nothing helped me.
* [X] I have asked the question on StackOverflow. But I didn't get the answer yet.

StackOverflow link: https://stackoverflow.com/questions/70446774/is-there-a-way-to-tell-fast-xml-parser-how-to-parse-xml-tags

Question: is there a way to tell fast-xml-parser that when parsing from XML to JSON I want the first tag name letter to be lower case?

**Comment by amitguptagwl** [comment]
It's not that difficult to provide tag and attribute name processors. I need to check what could be the better was a user should use them. I don't want to make the library feature creepy

**Comment by amitguptagwl** [comment]
Please refer v4.0.9
