### ISSUE TITLE
how to change the attribute tag name like this ?

### ISSUE THREAD

**Issue by lvlinkeji** [NaturalIntelligence/fast-xml-parser#417]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
is there any way to change the attribute tag name like this ?
### Code
```js
const {XMLBuilder} = require('fast-xml-parser');
// some code ...
// some code ...
```

Output

```xml
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US">
    <voice name="en-US-JennyNeural">
        <prosody rate="+30.00%">
            Welcome to XXX Cognitive Services XXX API.
        </prosody>
    </voice>
</speak>


<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:tts="https://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="en-US-AriaNeural">
        <tts:express-as style="cheerful">
            That'd be just amazing!
        </tts:express-as>
    </voice>
</speak>
```

expected data

```xml
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US">
    <voice name="en-US-JennyNeural">
        <prosody rate="+30.00%">
            Welcome to XXX Cognitive Services XXX API.
        </prosody>
    </voice>
</speak>


<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:tts="https://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="en-US-AriaNeural">
        <tts:express-as style="cheerful">
            That'd be just amazing!
        </tts:express-as>
    </voice>
</speak>
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
output and expected data are exactly same. Probably you missed something.

**Comment by amitguptagwl** [comment]
`updateTag` option is added to the parser v4.2 to change tagName. Check [solothought](https://solothought.com/tutorial/fast-xml-parser-4.2-features/) post for detail example.

Reopen the issue if still exist
