### ISSUE TITLE
`processEntities: false` option does not work as expected

### ISSUE THREAD

**Issue by frankkulak** [NaturalIntelligence/fast-xml-parser#419]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
The `processEntities: false` option appears to not be working, because the XML declaration is still showing up in my JSON. Not sure if this is a conflict with my other settings, or maybe just a misunderstanding on my part, but I figured that `processEntities: false` was supposed to disable processing these tags based of [its documentation](https://github.com/NaturalIntelligence/fast-xml-parser/blob/HEAD/docs/v4/2.XMLparseOptions.md#processentities) and [your definition of entities](https://github.com/NaturalIntelligence/fast-xml-parser/blob/7ab589190ea0b22f08b4b8ff6e9bdd68c6efef2e/docs/v4/5.Entities.md).

I was previously using v4.0.0-beta.2 and it worked perfectly fine for my use case, but upon upgrading to v4.0.1, it introduced an issue. My code was assuming that it would not receive any `?xml` tags, and now that it is, things are breaking. I came up with a temporary fix (checking if a node has the tag `?xml` and skipping it), but it would be nice to have them not be parsed at all.

### Input
See below.

### Code
```js
const { XMLParser } = require("fast-xml-parser");
const util = require("util");

const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: "",
  parseAttributeValue: false,
  parseTagValue: false,
  commentPropName: "comment",
  textNodeName: "value",
  preserveOrder: true,
  processEntities: false // <-- isn't working
});

const result = parser.parse(`<?xml version="1.0" encoding="utf-8"?>\n<I n="some_file"/>`);
console.log(util.inspect(result, false, null, true));
```

### Output
```json
[
  {
    "?xml": [ { "value": "" } ],
    ":@": { "version": "1.0", "encoding": "utf-8" }
  },
  { "I": [], ":@": { "n": "some_file" } }
]
```

### expected data
```json
[
  { "I": [], ":@": { "n": "some_file" } }
]
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
I believe you're mixing PI tags with entities. PI tags are always processed currently. Check [this](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/7.PITags.md) for your reference.

**Comment by frankkulak** [comment]
Ah ok, so it was a misunderstanding on my part, then. I assumed that PI tags were considered entities because I saw it [here](https://github.com/NaturalIntelligence/fast-xml-parser/blob/7ab589190ea0b22f08b4b8ff6e9bdd68c6efef2e/docs/v4/5.Entities.md), but I see now that that is just the top of your example file, not an example of an entity.

May I ask what has changed between 4.0.0-beta.2 and 4.0.1? Because I was not previously getting the PI tag in my result, and I would like to exclude it, if possible. If not too difficult, could an option be added to ignore PI tags?

**Comment by frankkulak** [comment]
Ok, makes sense. So I guess this issue can be a feature request instead of a bug report - would it be possible to add an option to ignore PI tags? If you want, I can close this issue and create a new one that is specifically for a feature request.

**Comment by amitguptagwl** [comment]
This is small change. But I generally wait what is the expectations of other users too before we're implementing any new feature. So I'll keep this issue open to track it

**Comment by estanglerbm** [comment]
Upgrading from v3 to v4 broke my app because of the PI (for ?xml).  Definitely would have preferred an option to disable that.
