### ISSUE TITLE
Feature request: node based results from parser

### ISSUE THREAD

**Issue by UltraCakeBakery** [NaturalIntelligence/fast-xml-parser#422]
Would it be possible to get a node based tree returned from parser instead of what we get now?

Something like:
```json
[
	{
		"tag": "html",
		"attributes": [
			{
				"name": "lang",
				"value": "en-EN"
			}
		],
		"children": [
			{
				"tag": "head",
				"children": []
			},
			{
				"tag": "body",
				"children": [
					{
						"tag": null,
						"text": "          \n\n"
					},
					{
						"tag": "div",
				                "children": []
					}
				]
			}
		]
	}
]
```

Node based tree's are easier to iterate over and manipulate. In this example I use HTML, but I'm sure the same goes for XML. 

Currently I convert the results from xml-parser to the example above, and convert it back later. This is a costly opperation, which is why I am making this request.

**Comment by amitguptagwl** [comment]
In what term, would it be easy?

**Comment by amitguptagwl** [comment]
If you need pretty output with less detail, you can always set 'preserveOrder:false'
