### ISSUE TITLE
Difference in handling <?xml ...?>

### ISSUE THREAD

**Issue by joheredi** [NaturalIntelligence/fast-xml-parser#424]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
While migrating to v4, I relized that the node <?xml ... ?> is handled differently. In v3, the parser used to ignore it. Now, the parser adds it to the parsed object

Is this expected? Is there any way to configure the parser to ignore it?

### Input
 `<?xml version="1.0" encoding="utf-8"?><Collection><Element>1</Element><Element>2</Element></Collection>`

### Code
```javascript
import { XMLParser } from "fast-xml-parser";
import { parse } from "fast-xml-parser-v3";

const str = `<?xml version="1.0" encoding="utf-8"?><Collection><Element>1</Element><Element>2</Element></Collection>`;

const v4Parser = new XMLParser();

const v3Result = parse(str);
const v4Result = v4Parser.parse(str);

console.log(v3Result);

// { Collection: { Element: [ 1, 2 ] } }

console.log(v4Result);
// { '?xml': '', Collection: { Element: [ 1, 2 ] } }
```

### Output
` { '?xml': '', Collection: { Element: [ 1, 2 ] } }`
### expected data
`{ Collection: { Element: [ 1, 2 ] } }`

**Comment by amitguptagwl** [comment]
Yes they're by default added. But I'll provide an option to ignore them from the parsed result.

**Comment by joheredi** [comment]
Thanks @amitguptagwl, is the option to ignore the root xml tag already available?

**Comment by amitguptagwl** [comment]
Please use `ignoreDeclaration: true`
