### ISSUE TITLE
BUG: Objects with only text property call tagValueProcessor twice

### ISSUE THREAD

**Issue by haddadnj** [NaturalIntelligence/fast-xml-parser#425]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
Formatting XML output for `j2xParser` has incorrect line spacing and indentation for text nodes that are represented with the `#text` property.
### Code
```json
{
  "root_node": [
    {
      "some_thing_collection": [
        {
          "thing": [
            {
              "#text": "first val & encoded char"
            }
          ]
        }
      ],
      "some_tag": [
        {
          "#text": "some value"
        }
      ]
    }
  ]
}
```

### Output

```xml
<?xml version="1.0"?>
<root_node>
  <some_thing_collection>
    <thing>first val &amp;amp; encoded char</thing>
  </some_thing_collection>
  <some_tag>some value</some_tag>
</root_node>

```

### expected data

```xml
<?xml version="1.0"?>
<root_node>
  <some_thing_collection>
    <thing>first val &amp; encoded char</thing>
  </some_thing_collection>
  <some_tag>some value</some_tag>
</root_node>

```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

**Comment by mitosagi** [comment]
The same thing is happening with version 4.0.3 of XMLBuilder. Is it only version 3 that has been fixed this time? Or has it not been released yet?

**Comment by amitguptagwl** [comment]
@mitosagi The fix was provided in v4.0.2 so it must present in later versions as well. Can you please confirm?

**Comment by mitosagi** [comment]
I must have failed to update it and now it is working correctly.
Sorry for the hassle.

**Comment by amitguptagwl** [comment]
@haddadnj Even after reverting your changes, all the tests are working fine. And I can see the correct output as well;

```xml
<a>
  <element>
    <subelement staticMessage="bar">foo &amp; bar</subelement>
  </element>
  <only_text_array>text &amp; value</only_text_array>
  <regular_array f="abc">text &amp; value</regular_array>
  <only_text_obj>another text &amp; val</only_text_obj>
</a>
```

If you feel it is not as desired then please share the code that you're using to parse/build. I'm reverting back your changes for the time being.
