### ISSUE TITLE
Is there a way to always get the value of a Text node or attribute as a string?

### ISSUE THREAD

**Issue by HiroyukiNIshimura** [NaturalIntelligence/fast-xml-parser#428]
* [*] Are you running the latest version?
* [*] Have you included sample input, output, error, and expected output? 
* [*] Have you checked if you are using correct configuration?
* [*] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
I want to treat the value of a specific attribute in XML as a string instead of a number, but when it is judged to be a number, it always becomes a number.
It is the same even if it is converted to a character string with tagValueProcessor.
Is there a way to specify it with numberParseOptions?
It's a bit unpleasant for the types of values ​​in the array to be disjointed.

### Input
<root>
    <values>
        <StringValue>123.00</StringValue>
        <StringValue>ABC</StringValue>
        <StringValue>456A</StringValue>
        <StringValue>789</StringValue>
    </values>
</root>

### Code
```js
const { XMLParser } = require("fast-xml-parser");

const xml = `
<root>
    <values>
        <StringValue>123.00</StringValue>
        <StringValue>ABC</StringValue>
        <StringValue>456A</StringValue>
        <StringValue>0789</StringValue>
    </values>
</root>
`;

const options = {
  ignoreAttributes: false,
};
const parser = new XMLParser({
  ignoreAttributes: false,
  alwaysCreateTextNode: true,
  tagValueProcessor: (tagName, value) => {
    return String(value);
  },
});
let jsonObj = parser.parse(xml);
console.log(JSON.stringify(jsonObj));

```

### Output
{"root":{"values":{"StringValue":[{"#text":123},{"#text":"ABC"},{"#text":"456A"},{"#text":789}]}}}

### expected data
{"root":{"values":{"StringValue":[{"#text":"123.00"},{"#text":"ABC"},{"#text":"456A"},{"#text":"0789"}]}}}

**Would you like to work on this issue?**

- [ ] Yes
- [*] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by HiroyukiNIshimura** [comment]
Specify String (value) with tagValueProcessor as described in Code.

Looking at the source code, parseValue is processed after tagValueProcessor ...


```js
function parseTextData(
  val,
  tagName,
  jPath,
  dontTrim,
  hasAttributes,
  isLeafNode,
  escapeEntities
) {
  if (val !== undefined) {
    if (this.options.trimValues && !dontTrim) {
      val = val.trim();
    }
    if (val.length > 0) {
      if (!escapeEntities) val = this.replaceEntitiesValue(val);
      var newval = this.options.tagValueProcessor(
        tagName,
        val,
        jPath,
        hasAttributes,
        isLeafNode
      );
      if (newval === null || newval === undefined) {
        //don't parse
        return val;
      } else if (typeof newval !== typeof val || newval !== val) {
        //overwrite
        return newval;
      } else if (this.options.trimValues) {
        return parseValue(
          val,
          this.options.parseTagValue,
          this.options.numberParseOptions
        );
      } else {
        var trimmedVal = val.trim();
        if (trimmedVal === val) {
          return parseValue(
            val,
            this.options.parseTagValue,
            this.options.numberParseOptions
          );
        } else {
          return val;
        }
      }
    }
  }
}
```

**Comment by amitguptagwl** [comment]
If you notice in above code when `newval === null || newval === undefined` then the value is not parsed.

**Comment by HiroyukiNIshimura** [comment]
？？？
var newval = this.options.tagValueProcessor(...)

newval is set by tagValueProcessor.

**Comment by amitguptagwl** [comment]
yes

**Comment by rpastro** [comment]
@HiroyukiNIshimura   If  I understood your issue correctly, all you need to do is set "parseTagValue: false".

```javascript
const parser = new XMLParser({
  ignoreAttributes: false,
  alwaysCreateTextNode: true,
  parseTagValue: false
});
```

**Comment by HiroyukiNIshimura** [comment]
thank you!
It went well!

```
const parser = new XMLParser({
  ignoreAttributes: false,
  alwaysCreateTextNode: true,
  parseTagValue: false
});
```
