### ISSUE TITLE
Support CDATA in json2xml with plain object input

### ISSUE THREAD

**Issue by dantio** [NaturalIntelligence/fast-xml-parser#429]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Revert CDATA support for `json2xml.js`
It was removed here: https://github.com/NaturalIntelligence/fast-xml-parser/commit/203f41019cce147f2df189e647beb5dcf51999fa

CDATA is now only supported in `orderedJs2Xml.js` with ` preserveOrder: true`.

### Code
```
const options = {
      cdataPropName: '__cdata',
}
const builder = new XMLBuilder(options);
const result = builder.build({
        Item: {
            __cdata: '<p></p>'
        }
});
```

### Output
```xml
<Item><Title>title</Title><Description><__cdata>&lt;div&gt;test&lt;/div&gt;</__cdata></Description></Item>
```

### expected data
```xml
<Item><Title>title</Title><Description><![CDATA[<div>test</div>]]></Description></Item>
```

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No
- [x] Maybe

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by mbs-team** [comment]
any update about this issue?

**Comment by endroid** [comment]
We would like to use the new version but we really need cdata support which appears broken.

**Comment by media-square** [comment]
Same here. building a XML with CDATA is broken.

**Comment by amitguptagwl** [comment]
supported from v4.0.7
