### ISSUE TITLE
Invalid parsing of self-closing stopNode

### ISSUE THREAD

**Issue by diegone** [NaturalIntelligence/fast-xml-parser#435]
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
Using `preserveOrder: true` on a self-closing stopNode results in the tag emitted as a text node.

### Code
```js
const XMLParser = require('fast-xml-parser').XMLParser;
const parser = new XMLParser({preserveOrder: true, stopNodes: ["*.foo"]});
console.dir(parser.parse('<root><foo name="bar"/></root>'), { depth: null });
```

### Output
```js
[
  {
    root: [ { foo: [ { '#text': '' } ] }, { '#text': 'foo name="bar"/>' } ]
  }
]
```

### Expected Output
```js
[
  {
    root: [
      { foo: [ { '#text': '' } ] }
    ]
  }
]
```

**Would you like to work on this issue?**
- [ ] Yes
- [X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by erkannt** [comment]
@dependabot squash and merge
