### ISSUE TITLE
Documentation for how to avoid parsing E164 phone numbers

### ISSUE THREAD

**Issue by josephdpurcell** [NaturalIntelligence/fast-xml-parser#438]
### Description

By default, fast-xml-parser will turn E164 numbers into invalid E164 numbers.

### Input

By default, fast-xml-parser will take a phone element like:

```xml
<phone>+55555555555</phone>
```

And, parse it into:

```xml
<phone>55555555555</phone>
```

The result is that a valid E164 number becomes invalid.

### Code

Here is a configuration that will allow E164 numbers to not be modified:

```ts
const parser = new XMLParser({
  numberParseOptions: {
    hex: false,
    leadingZeros: false,
    skipLike: /^\+[1-9]\d{1,14}$/,
  },
});
const parsedXml = parser.parse('<phone>+55555555555</phone>');

const builder = new XMLBuilder();
const newXml = builder.build(parsedXml);
```

The result of `newXml` will be:

```xml
<phone>+55555555555</phone>
```

**Comment by josephdpurcell** [comment]
Here is a similar convo: https://github.com/NaturalIntelligence/fast-xml-parser/issues/200#issuecomment-551341736

Closing this, since its documentation, not an issue. I assume the maintainer can re-open and modify this if needed.

My hope is that by documenting this, someone else will more quickly find a resolution to this type of issue.

**Comment by amitguptagwl** [comment]
I hope you have checked docs for [numberparseoptions](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#numberparseoptions). If you feel we can make it better, please raise a PR.
