### ISSUE TITLE
v4 vs v3 ArrayMode feedback

### ISSUE THREAD

**Issue by savvasmarkstatkus** [NaturalIntelligence/fast-xml-parser#448]
Hi,
In v3 arrayMode allowed the XML to be placed in arrays easily.
v4 seems to now take this into a isArray, alwaysArray path.  I can convey trying to deal with mixed XML that sometimes is a single item and sometimes is an array adds different outcomes with the JSON output (object vs array).  And then attempting to go node by node adding alwaysArray patterns attempting to root out all scenarios far more tedious than just being able to say `arrayMode = true`.

Did I misunderstand the v4 change or is there a easy way to force this to true all the time without the added step of calling every combination out in alwaysArray?

**Comment by igor-tatarinov** [comment]
I am also experiencing a similar issue. Parsing XML with an array of length 1 to JSON will return the object rather than the array. This creates issues with validation schemas which expect certain types.

**Comment by amitguptagwl** [comment]
@savvasmarkstatkus arrayMode was having limitations in v3. There were multiple cases, it was failing to cover. So the feature was present but it was never promoted. It was also conflicting with preserve order mode. So we decided to change it and leave on the user how to mark if a tag should be treated as array.

I hope you must have seen this example already.
https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#isarray

Please search for previous discussions for more detail. The easiest way in v4 can be, probably, check for `isLeafNode`

**Comment by cybercussion** [comment]
ok thanks, I'll see if I can test this out with a retrofit and bump to v4 again.

**Comment by amitguptagwl** [comment]
Please reopen if still exists
