### ISSUE TITLE
What is the command or option to validate XML file from CLI?

### ISSUE THREAD

**Issue by TheDeathConqueror** [NaturalIntelligence/fast-xml-parser#47]
### Checklist

* [x] Are you running the latest version?
* [ ] Include sample input XML 
* [ ] Include actual output
* [ ] Include expected output
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

What is the command or option to validate XML file from CLI?

**Comment by amitguptagwl** [comment]
@TheDeathConqueror I personally never need XML validator from CLI so I have never created it's CLI command yet.

**Comment by TheDeathConqueror** [comment]
Thanks I would be happy if you can add this feature. I'm downloading the XML files from other server so want to check that they are properly downloaded.

**Comment by amitguptagwl** [comment]
Will you mind to raise a PR? It just need some changes in cli.js

**Comment by TheDeathConqueror** [comment]
Yeah sure, let me do that. Thanks

**Comment by TheDeathConqueror** [comment]
There are 2 branches. Is it fine if I do changes on dev branch? I couldn't find tests for CLI so not adding them.

**Comment by amitguptagwl** [comment]
Yes that is fine. Thanks
