### ISSUE TITLE
XMLParser strips CDATA in description tag

### ISSUE THREAD

**Issue by markcellus** [NaturalIntelligence/fast-xml-parser#471]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
Hello. Per RSS feed XML specification, I've wrapped HTML with CDATA so that the description field can contain HTML for RSS readers. But XMLParser seems to strip the CDATA value. Please see code snippet below. Any help would be greatly appreciated! :hugs:  

### Code
```js
const xml = "<description><![CDATA[<p>This is a test</p>]]></description>"
const parser = new fastXmlParser.XMLParser();
console.log(parser.parse(xml));
```

### Output

```js
{description: "<p>This is a test</p>"}
```
### expected data

```
{description: "<![CDATA[<p>This is a test</p>]]>"}
```

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No
- [x] Maybe

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Please refer the [docs](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#cdatapropname)

**Comment by markcellus** [comment]
@amitguptagwl I looked at the docs and tried that option. It still doesnt work. Can you explain how that's helpful base off of the example I have?

**Comment by amitguptagwl** [comment]
```js
const xml = "<description><![CDATA[<p>This is a test</p>]]></description>"
const parser = new fastXmlParser.XMLParser({cdataPropName:     "__cdata"});
console.log(parser.parse(xml));
```
