### ISSUE TITLE
Playground does not work

### ISSUE THREAD

**Issue by kylemh** [NaturalIntelligence/fast-xml-parser#479]
<img width="1728" alt="Screen Shot 2022-07-25 at 12 20 33 AM" src="https://user-images.githubusercontent.com/9523719/180666301-573d14aa-1089-4d12-836e-f64d28dedc4b.png">

The URL listed here (https://naturalintelligence.github.io/fast-xml-parser/) does not validate or parse XML, nor convert JSON/JS into XML.

**Comment by amitguptagwl** [comment]
Please reopen if still exists
