### ISSUE TITLE
questions about: innerHtml self closing br tag

### ISSUE THREAD

**Issue by tidys** [NaturalIntelligence/fast-xml-parser#482]
### Discussed in https://github.com/NaturalIntelligence/fast-xml-parser/discussions/481
version:4.0.8
# The problem with innerHtml br
My xml data comes from innerHTML, like this:
`<font size="20">1<br>2<br>3</font>`，
`br` is not self closing
![image](https://user-images.githubusercontent.com/7894208/182777802-d69c9696-4be9-4ae6-9284-e20b99dc38ac.png)
When I try to parse this xml，this will cause the text to be parsed into the br tag
![image](https://user-images.githubusercontent.com/7894208/182778168-f6622e37-4f2b-4d82-b25f-2536f0d6240a.png)
The above array of data will be built and the result will be
`<font size="20">1<br>2</br><br>3</br></font>`
This is not the result I was expecting，
I looked at the source code, it seems that there is no good way
Here's how I've solved it so far, the xml data is first replaced globally as shown below
`replace(/<br>/g, '<br/>');`

**Comment by amitguptagwl** [comment]
Sorry. Can you please describe in English?

**Comment by tidys** [comment]
I've updated it and I feel like I can consider adding a self closing tag logic

**Comment by tidys** [comment]
in version:4.09, i found `stopNodes` can fix my problem
https://github.com/NaturalIntelligence/fast-xml-parser/blob/HEAD/docs/v4/2.XMLparseOptions.md#stopnodes
