### ISSUE TITLE
"tagValueProcessor" typescript definition and purpose

### ISSUE THREAD

**Issue by andreafspeziale** [NaturalIntelligence/fast-xml-parser#489]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 

### Description
Shouldn't the `tagValueProcessor` signature be something like this?

`tagValueProcessor: (tagName: string, tagValue: string, jPath: string, hasAttributes: boolean, isLeafNode: boolean) => unknown;`

Instead of returning a `string`?

Otherwise I'm missing the point... I would use it like that

```
tagValueProcessor: (tagName, tagValue) => {
  switch (tagName) {
    case 'created_at':
      return new Date(tagValue)
  }

  return value;
};
```

Otherwise I'm missing the point of this option.

Thank you in advance!

**Would you like to work on this issue?**

If it's all about and simple as changing the `typescript` definition, why not?

- [x] Yes
- [ ] No

**Comment by amitguptagwl** [comment]
Yes, you're right. TS definition should be updated.

**Comment by dopry** [comment]
The type of the value for the XmlBuilder [tagValueProcessor method](https://github.com/NaturalIntelligence/fast-xml-parser/blob/4735d54d4de29a2a422bf3605138144e2e5054dc/src/fxp.d.ts#L55) is not always 'string'. It should probably be `any` or `unknown` as well. It would be nice to get more context on the value being processed. That is probably a separate issue though.

**Comment by amitguptagwl** [comment]
@dopry Since it is mentioned in docs, people can refer that. Otherwise, we can add some js docs more better clarification.

**Comment by aspeziale** [comment]
@amitguptagwl Can you release this little change? So I can start using it 🤣

**Comment by andreafspeziale** [comment]
@amitguptagwl Can you release this little change? So I can start using it 🤣

**Comment by amitguptagwl** [comment]
I've tried to add for one method. Please check [fxp.d.ts](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/fxp.d.ts).

**Comment by dopry** [comment]
@amitguptagwl what do you mean by it is mentioned in the docs? I don't see anything in the docs about the type of the XmlBuilder.tagValueProcesspr method's value property's type definition being incorrect.

**Comment by amitguptagwl** [comment]
@dopry In docs it is mentioned how the parser would react on different type of values returned from this function.

**Comment by dopry** [comment]
Link?  That doesn't change the fact typescript will complain about the returned type.

**Comment by amitguptagwl** [comment]
Yes of course.
https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#tagvalueprocessor

**Comment by andreafspeziale** [comment]
Are you going to tag and publish?

**Comment by amitguptagwl** [comment]
I'll publish all the changes in next 2 days
