### ISSUE TITLE
Clarification on axes in comparison plots NPM page

### ISSUE THREAD

**Issue by johanbook** [NaturalIntelligence/fast-xml-parser#493]
There are several comparison plots with xml2js on https://www.npmjs.com/package/fast-xml-parser, however, I cannot work out what the Y axes correspond to. I assume the X axes are bytes of data. Grateful for clarification.

**Comment by amitguptagwl** [comment]
X axis is the size of the data. So if it is mentioned as 1.5k means 1.5 kb. Y axes represent it's throughput in requests per second.
