### ISSUE TITLE
Can't get CDATA section content

### ISSUE THREAD

**Issue by lgra** [NaturalIntelligence/fast-xml-parser#5]
Hi,

It seems that CDATA section are ignored when parsing XML, and produce an invalid "Invalid comment" exception when validating.

For exemple, this XML:

```
<?xml version="1.0"?>
<any_name>
    <person>
        <phone>+122233344550</phone>
        <name><![CDATA[Jack]]></name>
        <phone>+122233344551</phone>
    </person>
</any_name>
```

produces:

```
{
    "any_name": {
        "person": {
            "phone": [
                122233344550,
                122233344551
            ],
            "name": ""
        }
    }
}
```

Is there a way to make fast-xml-parser put CDATA content as the string value of the property (`name: "Jack"` in the exemple)?

**Comment by amitguptagwl** [comment]
Yes, I dint handle the CDATA yet. let me check the CDATA rules. So I can handle it effectively.

**Comment by amitguptagwl** [comment]
I have added the support for handling CDATA. But I need to run performance test before publishing my changes.

**Comment by lgra** [comment]
Great news.

**Comment by amitguptagwl** [comment]
As I'm busy with some job interviews not getting the time to run the perf tests. :-( Will do it after a week. But I have published the changes. So plz use the latest version of npm repo for CDATA support.
