### ISSUE TITLE
Missing attribute details while converting from xml to json

### ISSUE THREAD

**Issue by shubham-negi** [NaturalIntelligence/fast-xml-parser#50]
The script works well, but the attribute details is not there in the converted JSON. I've attached the dummy.xml file and there is no detail in the output for attribute and its value while converting this specific file in json.

I'm unable to upload the xml file therefore here is a snippet:
```
<catalog>
   <book id="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <price>44.95</price>
   </book>
   <book id="bk102">
      <author>Ralls, Kim</author>
      <title>Midnight Rain</title>
      <price>5.95</price>
   </book>
   <book id="bk103">
      <author>Corets, Eva</author>
      <title>Maeve Ascendant</title>
      <price>5.95</price>
   </book>
</catalog>
```
The  id="#nodeID" is missing in the conversion, it just make array for each node of <book>.

### Note: There should be converter from json to xml, so it can work back and fourth.

**Comment by amitguptagwl** [comment]
@shubham-negi for the note

> Note: There should be converter from json to xml, so it can work back and fourth.

I have just released 3.2.0. Please read the README for more detail.

**Comment by amitguptagwl** [comment]
For part 1, please let me know the configuration you are using for parsing

**Comment by shubham-negi** [comment]
```
    var xmlData = '#'; // refer xml snippet
    var result = parser.validate(xmlData);
    if(result !== true) cnosole.log(result.err);
    var jsonObj = parser.parse(xmlData);

```

**Comment by amitguptagwl** [comment]
Please refer code example under [How to User](https://github.com/NaturalIntelligence/fast-xml-parser#how-to-use). The value of `ignoreAttributes` is by default `true` which means it'll not parse attributes until you set it to false.

I hope it should help. Feel free to reopen this thread in case the issue exist.

**Comment by shubham-negi** [comment]
Please share some working example, because I tried but got the same output

`    var xmlData = '<?xml version="1.0"?><catalog><book id="bk101"><author>Gambardella, Matthew</author><title>XML Developer s Guide</title><genre>Computer</genre><price>44.95</price><publish_date>2000-10-01</publish_date><description>An in-depth look at creating applicationswith XML.</description></book><book id="bk102"><author>Ralls, Kim</author><title>Midnight Rain</title><genre>Fantasy</genre><price>5.95</price><publish_date>2000-12-16</publish_date><description>A former architect battles corporate zombies,an evil sorceress, and her own childhood to become queenof the world.</description></book><book id="bk103"><author>Corets, Eva</author><title>Maeve Ascendant</title><genre>Fantasy</genre><price>5.95</price><publish_date>2000-11-17</publish_date><description>After the collapse of a nanotechnologysociety in England, the young survivors lay thefoundation for a new society.</description></book><book id="bk104"><author>Corets, Eva</author><title>Oberon s Legacy</title><genre>Fantasy</genre><price>5.95</price><publish_date>2001-03-10</publish_date><description>In post-apocalypse England, the mysteriousagent known only as Oberon helps to create a new lifefor the inhabitants of London. Sequel to MaeveAscendant.</description></book><book id="bk105"><author>Corets, Eva</author><title>The Sundered Grail</title><genre>Fantasy</genre><price>5.95</price><publish_date>2001-09-10</publish_date><description>The two daughters of Maeve, half-sisters,battle one another for control of England. Sequel toOberon s Legacy.</description></book><book id="bk106"><author>Randall, Cynthia</author><title>Lover Birds</title><genre>Romance</genre><price>4.95</price><publish_date>2000-09-02</publish_date><description>When Carla meets Paul at an ornithologyconference, tempers fly as feathers get ruffled.</description></book><book id="bk107"><author>Thurman, Paula</author><title>Splish Splash</title><genre>Romance</genre><price>4.95</price><publish_date>2000-11-02</publish_date><description>A deep sea diver finds true love twentythousand leagues beneath the sea.</description></book><book id="bk108"><author>Knorr, Stefan</author><title>Creepy Crawlies</title><genre>Horror</genre><price>4.95</price><publish_date>2000-12-06</publish_date><description>An anthology of horror stories about roaches,centipedes, scorpions  and other insects.</description></book><book id="bk109"><author>Kress, Peter</author><title>Paradox Lost</title><genre>Science Fiction</genre><price>6.95</price><publish_date>2000-11-02</publish_date><description>After an inadvertant trip through a HeisenbergUncertainty Device, James Salway discovers the problemsof being quantum.</description></book><book id="bk110"><author>O Brien, Tim</author><title>Microsoft .NET: The Programming Bible</title><genre>Computer</genre><price>36.95</price><publish_date>2000-12-09</publish_date><description>Microsoft s .NET initiative is explored indetail in this deep programmer s reference.</description></book><book id="bk111"><author>O Brien, Tim</author><title>MSXML3: A Comprehensive Guide</title><genre>Computer</genre><price>36.95</price><publish_date>2000-12-01</publish_date><description>The Microsoft MSXML3 parser is covered indetail, with attention to XML DOM interfaces, XSLT processing,SAX and more.</description></book><book id="bk112"><author>Galos, Mike</author><title>Visual Studio 7: A Comprehensive Guide</title><genre>Computer</genre><price>49.95</price><publish_date>2001-04-16</publish_date><description>Microsoft Visual Studio 7 is explored in depth,looking at how Visual Basic, Visual C++, C#, and ASP+ areintegrated into a comprehensive developmentenvironment.</description></book></catalog>';
    var options = {ignoreAttributes : false};
    var result = parser.validate(xmlData,options);
`

**Comment by amitguptagwl** [comment]
[Here](https://github.com/NaturalIntelligence/fast-xml-parser/tree/master/spec) is the collection of tests which is full with examples that can help you. However for a quick help, 


This is the example I've taken from README which is working fine
```js
 var xmlData = '<catalog>'
        + '   <book id="bk101">'
        + '      <author>Gambardella, Matthew</author>'
        + '      <title>XML Developer\'s Guide</title>'
        + '      <price>44.95</price>'
        + '   </book>'
        + '   <book id="bk102">'
        + '      <author>Ralls, Kim</author>'
        + '      <title>Midnight Rain</title>'
        + '      <price>5.95</price>'
        + '   </book>'
        + '   <book id="bk103">'
        + '      <author>Corets, Eva</author>'
        + '      <title>Maeve Ascendant</title>'
        + '      <price>5.95</price>'
        + '   </book>'
        + '</catalog>'

            var result = parser.parse(xmlData,{
                ignoreAttributes : false,
                parseNodeValue : true,
                parseAttributeValue : true,
                decodeHTMLchar: true,
            });
        console.log(JSON.stringify(result,null,4));
```

Output

```js
{
    "catalog": {
        "book": [
            {
                "author": "Gambardella, Matthew",
                "title": "XML Developer's Guide",
                "price": 44.95,
                "@_id": "bk101"
            },
            {
                "author": "Ralls, Kim",
                "title": "Midnight Rain",
                "price": 5.95,
                "@_id": "bk102"
            },
            {
                "author": "Corets, Eva",
                "title": "Maeve Ascendant",
                "price": 5.95,
                "@_id": "bk103"
            }
        ]
    }
}
```

**Comment by amitguptagwl** [comment]
You can also try online tool to parse it to know that if there is an issue with the library or there is something with the configuration. Here is the link

https://naturalintelligence.github.io/fast-xml-parser/
