### ISSUE TITLE
unable to use the value "true" in an attribute

### ISSUE THREAD

**Issue by angrymarker** [NaturalIntelligence/fast-xml-parser#500]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [X ] Are you running the latest version?
* [ X] Have you included sample input, output, error, and expected output? 
* [X ] Have you checked if you are using correct configuration?
* [ X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
Input object:
```
{
    "iteration": {
        "@_test": "true",
    }
}
```

### Code
``
```
const { XMLBuilder } = require('fast-xml-parser');
builder = new XMLBuilder({ ignoreAttributes: false, format: true, suppressEmptyNode: true });
builder.build({
    "iteration": {
        "@_test": "true",
    }
})
```
        
```

### Output

<?xml version="1.0"?>
<iteration test></iteration>


### expected data

<?xml version="1.0"?>
<iteration test="true"></iteration>



**Would you like to work on this issue?**
<!-- choose one by changing [ ] to [x] -->
- [ ] Yes
- [ X] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by angrymarker** [comment]
this is good html, but not good xml. throwing into an xml linter or internet explorer bombs out, expecting the attribute to equal something
<HTML><HEAD></HEAD>
<BODY><TABLE width=400>
<P style="FONT: 13pt/15pt verdana">The XML page cannot be displayed 
<P style="FONT: 8pt/11pt verdana">Cannot view XML input using XSL style sheet. 
Please correct the error and then click the <A 
href="javascript:location.reload()" target=_self>Refresh</A> button, or try 
again later. 
<HR>

<P style="FONT: bold 8pt/11pt verdana">A name contained an invalid character. 
Error processing resource 
'file://x</P><PRE style="FONT-SIZE: 10pt; FONT-VARIANT: normal; FONT-WEIGHT: normal; FONT-STYLE: normal; LINE-HEIGHT: 12pt"><FONT color=blue>  &lt;Package isAddtPkg&gt;
</FONT></PRE></P></TABLE></BODY></HTML>The XML page cannot be displayed 
Cannot view XML input using XSL style sheet. Please correct the error and then click the [Refresh](javascript:location.reload()) button, or try again later. 


--------------------------------------------------------------------------------

A name contained an invalid character. Error processing resource 'file:/X

  <Package isAddtPkg>

**Comment by amitguptagwl** [comment]
Have you tried 'suppressBooleanAttributes:false' ?

**Comment by amitguptagwl** [comment]
closing as no response. Please reopen if issue still exist
