### ISSUE TITLE
Incorrect parsing entity &amp;lt;

### ISSUE THREAD

**Issue by AllanZhengYP** [NaturalIntelligence/fast-xml-parser#501]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
The predefined entity seems to be parsed twice. `&amp;lt;` is expected to be parsed to `$lt;`. However, it is parsed again to `<`
### Input
```xml
<SimpleScalarPropertiesInputOutput>
  <stringValue>&amp;lt;</stringValue>
</SimpleScalarPropertiesInputOutput>
```

### Code
```js
import { XMLParser } from "fast-xml-parser";

const encoded = `<SimpleScalarPropertiesInputOutput>
  <stringValue>&amp;lt;</stringValue>
</SimpleScalarPropertiesInputOutput>`;
const parser = new XMLParser({})
const parsed = parser.parse(encoded);

console.log(JSON.stringify(parsed, null, 2));
```

### Output
```json
{
  "SimpleScalarPropertiesInputOutput": {
    "stringValue": "<"
  }
}
```

### expected data
```json
{
  "SimpleScalarPropertiesInputOutput": {
    "stringValue": "&lt;"
  }
}
```
**Would you like to work on this issue?**

- [x] Yes
- [ ] No
If with sufficient guidance.

It seems to be caused by replacing the escaped value with entity regex in a loop:
https://github.com/NaturalIntelligence/fast-xml-parser/blob/443e8edaf94bb1e65738cd73aa32c9d5fa06a927/src/xmlparser/OrderedObjParser.js#L372-L375

**Comment by AllanZhengYP** [comment]
Hi @amitguptagwl, is there any update?

**Comment by amitguptagwl** [comment]
This feature was knowingly not implemented keeping the DTD attacks in mind. Probably we can implement it and keep it disabled by default.
