### ISSUE TITLE
Unable to find v3.x 

### ISSUE THREAD

**Issue by shubham-negi** [NaturalIntelligence/fast-xml-parser#51]

**Comment by shubham-negi** [comment]
(https://naturalintelligence.github.io/fast-xml-parser/)

After unchecking 'Ignore attributes from parsing', I'm still not getting the attribute properties and values.

**Comment by amitguptagwl** [comment]
You're on very old version. I've replied in last issue with the example. there was no change as explained on README.

If you are using this library in browser you can either refer [CDN](https://cdnjs.com/libraries/fast-xml-parser) or [lib](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/lib/parser.js) folder. The same thing is mentioned on README.

I'll really appreciate if you can read README page completely. It's not very long and will answer your most of the questions.
