### ISSUE TITLE
01 is parsed as number, but string is wanted

### ISSUE THREAD

**Issue by modestotech** [NaturalIntelligence/fast-xml-parser#513]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
I want to have a xml value `01` to be parsed as a string `01`, but it's parsed as number. I've tested the XML below in the tool where it works as intended. I suspect there's something with my parserOptions, but can't see it.

### Input
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Catalog>
    <Articles>
        <HeaderData>
            <Date />
            <CatalogName />
        </HeaderData>
        <ArticleData>
            <ArticleNumber>1234</ArticleNumber>
            <Artikkelkategori>
                <ID>01</ID>
                <Value>Samleartikkel</Value>
            </Artikkelkategori>
        </ArticleData>
    </Articles>
</Catalog>
```

### Code
```js
        const alwaysArray = ['Catalog.Articles.ArticleData.OtherEAN'];

        const parserOptions = {
            ignoreDeclaration: true,
            isArray: (name: string, jpath: string) => {
                if (alwaysArray.indexOf(jpath) !== -1) {
                    return true;
                }
                return false;
            },
            parseTrueNumberOnly: true,
        };

        const parser = new XMLParser(parserOptions);
        const parsedObject = parser.parse(downloadedFile[0]);
```

### Output
![image](https://user-images.githubusercontent.com/31730051/199518818-84f9b0a1-8036-495d-af26-867b04aa174f.png)

### expected data
I expect `ArtikkelKategori.ID` to be string `01` but it's a number. 

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by opunbuds** [comment]
+1

**Comment by amitguptagwl** [comment]
Please check the documentation. I hope you're using version v of the library

**Comment by modestotech** [comment]
Yes, Google had taken me to the documentation for v3. Worked fine for v4 with the following:

```
            numberParseOptions: {
                leadingZeros: false,
                hex: false,
            }
```
