### ISSUE TITLE
Readme: unclear performance charts

### ISSUE THREAD

**Issue by demilsson** [NaturalIntelligence/fast-xml-parser#514]
Looking at the README, it is impossible to interpret the performance results as the y-axis doesn't have labels.

I would suggest adding a label to the y-axis, or alternatively, a paragraph beneath each chart explaining how to interpret the data.

**Comment by amitguptagwl** [comment]
Can you please check and let me know if current description help you to understand the charts?

**Comment by demilsson** [comment]
Much better, thanks!

Heads up, there appears to be a small formatting issue where the "Large files" header isn't on its own line.

![Screenshot 2022-11-29 at 13 26 27](https://user-images.githubusercontent.com/6350121/204529106-5967d788-39a3-4277-81c1-18552239fa02.png)
