### ISSUE TITLE
Option to parse all values as strings

### ISSUE THREAD

**Issue by alanhett** [NaturalIntelligence/fast-xml-parser#516]
I need an option that will disable number parsing and parse all values as strings. For example, zip codes and tax ID numbers often have leading zeroes that need to be preserved as string types.

I'm thinking of a simple solution, and I'm willing to submit the PR myself, but would like to share my idea here for feedback first. The option property would be something like:

`numberParseDisable: true` (which is similar naming to the `numberParseOptions` property). If set to true, it would bypass the strnum process.

Thoughts? Any guidance on what source files I should review and/or update to build this would be helpful!

**Comment by amitguptagwl** [comment]
You're using the old version of library. Please refer the documentation for v4.

**Comment by alanhett** [comment]
Thanks, I did have the correct version, but I was confused by the options. These options preserve leading zeroes, but it does not disable number parsing entirely. I'm still willing to write the above if others are interested in such an option.
```
numberParseOptions: { leadingZeros: false }
```

**Comment by amitguptagwl** [comment]
Please check [strnum](https://github.com/NaturalIntelligence/strnum) library that we use in FXP for value parsing.

**Comment by abnaod** [comment]
This works for me
 ```javascript
numberParseOptions: {
    leadingZeros: false,
    hex: false,
    skipLike: /\d/,
  }

**Comment by weijarz** [comment]
I think `skipLike: /(?:)/` is a better option.
