### ISSUE TITLE
Builder : #text is not set as tag value when some attributes are present

### ISSUE THREAD

**Issue by benjamin-feron** [NaturalIntelligence/fast-xml-parser#521]
Hi everybody !
I've a little issue with this lib, can someone help me ?

* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? **No, I cant't reproduce issue with this tool.**

### Description
 #text is ignored when other attributes exists

### Code
```js
import { XMLBuilder } from 'fast-xml-parser'

const xmlData = {
  "tag1": {
    "#text": "aaa"
  },
  "tag2": {
    "#text": "aaa",
    "attr": "bbb"
  }
}

const xmlBuilder = new XMLBuilder({
  attributeNamePrefix: '',
  format: true,
  ignoreAttributes: false
})

const xml = xmlBuilder.build(xmlData)

console.log(xml)
```

### Output
```
<tag1 #text="aaa">aaa</tag1>
<tag2 #text="aaa" attr="bbb"></tag2>
```

### Expected data
```
<tag1 #text="aaa">aaa</tag1>
<tag2 #text="aaa" attr="bbb">aaa</tag2>
```

### Test this code

You can test this code [here](https://playcode.io/1036397)

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

Thanks !

**Comment by amitguptagwl** [comment]
Did you try to set [textNodeName](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/3.XMLBuilder.md#textnodename)?

**Comment by benjamin-feron** [comment]
Yes but it does not change anything.

Thank you

**Comment by amitguptagwl** [comment]
show me the configuration you tried with textNodeName

**Comment by amitguptagwl** [comment]
closing the issue. If it still exist, please reopen with sample code.
