### ISSUE TITLE
Version 3.0.1 - wrong attribute parsing for "" value; no #text key ('Object' instead)

### ISSUE THREAD

**Issue by Opariti** [NaturalIntelligence/fast-xml-parser#53]
## Important
If have some **questions**, please read the README or check `spec` folder for examples. Otherwise stackoverflow is the better place to discuss technical questions until or unless they are bug.

If you are raising a **bug** please fill it in following format to avoid long communication and fast resolution.

### Checklist
Please fill below checklist

* [X] Are you running the latest version? 3.0.1
* [X] Have you include sample input? 
* [X] Have you include actual output?
* [X] Have you include expected output?
* [X] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [ ] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data
<?xml version="1.0" encoding="utf-8"?>
    <l ses="">
        <role>Administrator</role>
        A test value<role>Developer
        </role>
    </l>

### Code
```
exports.xmlJsonParsing = function (xmlString) {

    // when a tag has attributes
    let options = {
        attributeNamePrefix: "",
        attrNodeName: false,
        textNodeName: "#text",
        ignoreAttributes: false,
        ignoreNameSpace: false,
        allowBooleanAttributes: true,
        parseNodeValue: true,
        parseAttributeValue: true,
        trimValues: true,
        decodeHTMLchar: true,
    };
    if (fastXmlParser.validate(xmlString) === true) {//optional
        jsonObj = fastXmlParser.parse(xmlString, options);
    }

    //Intermediate obj
    var tObj = fastXmlParser.getTraversalObj(xmlString, options);
    jsonObj = fastXmlParser.convertToJson(tObj, options);

    return jsonObj;
}
```

### Output data
{"l":{"role":["Administrator","Developer"],"ses":true,"[object Object]":"A test value"}}

### expected data
{"l":{"role":["Administrator","Developer"],"ses":"","#text":"A test value"}}

**Comment by amitguptagwl** [comment]
Can you please check with latest version i.e. 3.2.0 ? Or try online tool for a quick look. It seems fine for me 

Output from online tool when ignores attributes;

```
{
    "l": {
        "role": [
            "Administrator",
            "Developer"
        ],
        "#text": "A test value"
    }
}
```

**Comment by amitguptagwl** [comment]
I have recently raised a bug #54. It'll publish the fix in few minutes for that. So please use 3.2.1 instead.

**Comment by Opariti** [comment]
That is perfectly fixed with 3.2.1!

Thanks


PS: Good job Amit, I think this is the best XML to JSON module today, and I have been trying a couple. I also don't see other functional evolutions for this one, thus my hint (since I need it 😊...): a reverse JSON to XML module with the same data model patterns. In this way you'll create a full, homogenious, conversion tool between JSON and XML.

Best,

Ginger


________________________________
De : Amit Gupta <notifications@github.com>
Envoyé : samedi 17 février 2018 15:59
À : NaturalIntelligence/fast-xml-parser
Cc : Opariti; Author
Objet : Re: [NaturalIntelligence/fast-xml-parser] Version 3.0.1 - wrong attribute parsing for "" value; no #text key ('Object' instead) (#53)


I have recently raised a bug #54<https://github.com/NaturalIntelligence/fast-xml-parser/issues/54>. It'll publish the fix in few minutes for that. So please use 3.2.1 instead.

**Comment by amitguptagwl** [comment]
Thanks for the appreciation @Opariti . I had launched 3.2.0 with JSON to XML feature. Please have a look on README for more detail.

**Comment by Opariti** [comment]
I've just tried and it works fine!
You can add to the Readme comparison chart that, besides the processing speed and by my experience, it is the only conversion tool that does a full  reverse one.
Another comment: I didn't need to download Parse.js, it worked with just
`const Parser = require("fast-xml-parser").j2xParser;
...
`
Last comment: you may try, for JSON to XML, to output nodes without children or text value as '<tag attributes />' instead of '<tag attributes></tag>'. It is excellent as it is now but it may be helpful for larger data.
Great job!

**Comment by amitguptagwl** [comment]
> You can add to the Readme comparison chart that, besides the processing speed and by my experience, it is the only conversion tool that does a full reverse one.

I believe xml2js also does the same job. However I'm not sure if you loose any information while doing reverse conversion. 

>  I didn't need to download Parse.js, it worked with just...

You need to download parser.js only when you are using it in browser.

> Last comment: you may try, for JSON to XML, to output nodes without children or text value as `<tag attributes />` instead of `<tag attributes></tag>`. It is excellent as it is now but it may be helpful for larger data.

There is already a property for that `supressEmptyNode: true`.

> Great job!

Thanks for your appreciation

**Comment by Opariti** [comment]
I've tried xml2js and, except that I may have wrongly set options, it does some kind of tag mangling thus certainly not 100% reverse conversion.
