### ISSUE TITLE
transformTagName add node attr value as parameter

### ISSUE THREAD

**Issue by frankie-zeng** [NaturalIntelligence/fast-xml-parser#531]
### Description
I want use attribute as tag name.
* input:

`
<var name="hello" 
       type="INTEGER" value="22">
  <a name="world" value="@DEF"/>
</var>
`

* output:

`
open output:
{
     hello:{
           world:{
              **
           }
     }
}
`

**Comment by amitguptagwl** [comment]
I feel it is very specific need. I'll suggest to use ordered parsed output and write a function on top it. It'll not take much time. Otherwise, I might think about it if there are more users for this feature.

**Comment by amitguptagwl** [comment]
`updateTag` option is added to the parser v4.2 to change attributes or tagName. Check [solothought](https://solothought.com/tutorial/fast-xml-parser-4.2-features/) post for detail example.
