### ISSUE TITLE
vite package error

### ISSUE THREAD

**Issue by Hiram-Wong** [NaturalIntelligence/fast-xml-parser#532]
"fast-xml-parser": "^4.0.13",
"vite": "^4.0.4",
![image.png](https://s2.loli.net/2023/01/13/tH8Sin7AOhTy6kG.png)

**Comment by amitguptagwl** [comment]
Not sure what exactly you're doing but looks like you're trying to build js files from node js code. I would suggest to post this question on stackoverflow to get quick solution

**Comment by amitguptagwl** [comment]
closing the issue.. please reopen if help is needed
