### ISSUE TITLE
Hex value in CDATA being parsed

### ISSUE THREAD

**Issue by estanglerbm** [NaturalIntelligence/fast-xml-parser#535]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

CDATA hex value (i.e. CDATA[0x1]) is being parsed and outputted as non-hex value.

### Input

``
<A><![CDATA[0x1]]></A>
``

### Code
```js
    const options = {};  
    const test_xml:string = "<A><![CDATA[0x1]]></A>";
    const parser = new XMLParser( options );
    const result = parser.parse( test_xml );
    console.log( `showBug: ${JSON.stringify(result)}` );
```

### Output

showBug: {"A":1}

### expected data

showBug: {"A":0x1}
or
showBug: {"A":"0x1"}

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by estanglerbm** [comment]
I should say that this worked in v3.  It works in the online tool for some reason.  And the `numberParseOptions` options mentioned in #513 is a workaround, but I don't know how good that is.  Being CDATA, it shouldn't even need these options.

**Comment by amitguptagwl** [comment]
In case of CDATA, it should be ignored. Will have to check why it is being rendered.

**Comment by amitguptagwl** [comment]
Please read the document
```js
const options = {
            cdataPropName: "cdata"
        };
```

**Comment by estanglerbm** [comment]
I understand that `cdataPropName` would be a workaround (not a solution) for this test case.  But the test case is a simplified version of code that worked in v3, where CDATA is mixed with non-CDATA, and can't use `cdataPropName` because there's no way to reconstruct how the CDATA and non-CDATA are mixed together if they are separated.  Even if they are merged by the parser, CDATA shouldn't be interpreted like this.

**Comment by estanglerbm** [comment]
Well, actually, if the CDATA text is merged, then it would be interpreted like a non-CDATA text would be.  I guess my issue is really that there is hex number parsing happening at all (so that `numberParseOptions` options are needed to disable that).  I don't remember that happening in v3, by default.

**Comment by amitguptagwl** [comment]
initially when it was designed, we kept cdata property to set properly when CDATA doesn't have to be ignored. So if it is set then it's value must not be parsed. Otherwise, it should be parsed before merge to the parent tag value.
