### ISSUE TITLE
Introduction of eNotation parameter breaks existing code

### ISSUE THREAD

**Issue by marcello-morena** [NaturalIntelligence/fast-xml-parser#538]
### Description
Hi. Just want to report that with yesterday's commit ([45b01db](https://github.com/NaturalIntelligence/fast-xml-parser/commit/45b01dbf8b56af2c8ee126be8c2e21ed79ae39f2)) the new mandatory field `eNotation` was introduced in the `numberParseOptions` configuration parameter. This breaks **ALL** existing code for projects using Typescript and this particular configuration parameter, since it makes `tsc` fail. 

Moreover, there was no mention in the docs of what `eNotation` does and the change is introduced in a patch version update (while breaking changes should only appear in major version updates).

Unfortunately for us, we discovered this change in the worst possible way: a client, officially testing the code that we delivered two days ago, calling us this morning saying that the code wasn't even compiling and demanding an emergency fix (that we promptly provided).

So, we fixed this on our side, but I strongly suggest that you release a new version making `eNotation` optional.

On a final note: please don't get me wrong, we really **DO** appreciate all the hard work that you put into this project, but this was a major headache for us.

**Comment by amitguptagwl** [comment]
Thanks for your feedback @marcello-morena . We run all tests before any release. But as the library is used in different ways by different projects, it might have broken your experience. I would appreciate if you raise a PR and add your usecase in the tests so the same situation can be avoided in future.

**Comment by amitguptagwl** [comment]
done

**Comment by tbouffard** [comment]
The type is now optional in v4.0.15 thanks to this commit: 6ebcb14509d351c27ec525f0380e736e0c058f75
However, this commit now set the default value of `eNotation` to `false`, which breaks the previous behavior.
Previously, when the `eNotation` wasn't set, fxp used the default value of `strnum` which is `true`. See https://github.com/NaturalIntelligence/strnum/blob/3fcb88602a08c103bccffc8c36041c3f3d0f8317/strnum.js#L16-L22

I can provide a PR to reproduce the problem. Please let me know.
I have detected the behavior change here: https://github.com/process-analytics/bpmn-visualization-js/pull/2494#pullrequestreview-1275179961

**Comment by amitguptagwl** [comment]
Yes, you're right. I'm launching 4.1.0 soon to fix it.

**Comment by tbouffard** [comment]
Thanks @amitguptagwl for the quick feedback and the planned release.
For people using v4.0.15 and that want to keep the previous behavior, just set the `eNotation` property to `true` in the `numberParseOptions`.
