### ISSUE TITLE
Security Vulnerability report

### ISSUE THREAD

**Issue by Sudistark** [NaturalIntelligence/fast-xml-parser#543]
Hey there,
I have found a security related vulnerability .

Is there any proper channel where I could forward the details ?

**Comment by amitguptagwl** [comment]
Thanks for contacting. Can we connect at [linkedin](https://www.linkedin.com/in/amitguptagwl/).

**Comment by Sudistark** [comment]
Just sent you the connection request, let me know how should I proceed with sharing the vuln details.
And sorry for the delay didn't get any notification
