### ISSUE TITLE
Is it possible to stack attributes when formatting xml

### ISSUE THREAD

**Issue by nickminutello** [NaturalIntelligence/fast-xml-parser#545]
When an xml element has many attributes, the current `format:true` produces an exceedingly long line.

Is it possible to produce something like this:
```xml
<ze-element attribute01="something"
                      attribute02="something else"
                      attribute03="something else again"
                      attribute04="different"
                      attribute05="different again"
                      attribute06="another one"
                      attribute07="more"
                      attribute08="more still"
                      attribute09="here is another"
                      attribute10="and another"
                      attribute11="and another" />

```

Many thanks

**Comment by amitguptagwl** [comment]
Sorry, currently, there is no feature which can help you

**Comment by nickminutello** [comment]
Is it something that could be added ? (e.g. if more than n attributes, stack vertically)

**Comment by amitguptagwl** [comment]
You can use `attributeValueProcessor` to stack the values of all the attributes. But you can't skip other attributes. Probably I can think about a feature to introduce `skipAttribute` function. But it will take time. If you want to work you can raise PR. It'll be easy.

**Comment by amitguptagwl** [comment]
`updateTag` option is added to the parser v4.2 to change attributes. Check [solothought](https://solothought.com/tutorial/fast-xml-parser-4.2-features/) post for detail example.
