### ISSUE TITLE
i've got a challenge with leading zeros

### ISSUE THREAD

**Issue by thuus** [NaturalIntelligence/fast-xml-parser#547]
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Code
```js
const { XMLParser, XMLBuilder, XMLValidator } = require("fast-xml-parser");

const options = {
    parseTrueNumberOnly: true  //if true then values like "+123", or "0123" will not be parsed as number.
};

const xmlInput = '<item>08</item>';
console.log(xmlInput);  

const parser = new XMLParser(options);
let jsonData = parser.parse(xmlInput);
console.log(JSON.stringify(jsonData));

const builder = new XMLBuilder();
const xmlOutput = builder.build(jsonData,options)
console.log(xmlOutput);
```

### Output
<item>8</item>

### expected data
<item>08</item>

**Would you like to work on this issue?**

- [ ] Yes
- [x ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Please check the docs
