### ISSUE TITLE
Missing Changelog for 4.1.2

### ISSUE THREAD

**Issue by frytg** [NaturalIntelligence/fast-xml-parser#548]
NPM seems to show a newer version (`4.1.2`), which doesn't show up in the Changelog or GitHub release, is this an intentional release?

https://www.npmjs.com/package/fast-xml-parser?activeTab=versions

https://github.com/NaturalIntelligence/fast-xml-parser/blob/a874ce78df0be1b5dceadc4e5e7e549c65a7a6ce/CHANGELOG.md

https://github.com/NaturalIntelligence/fast-xml-parser/releases

**Comment by amitguptagwl** [comment]
The detail was intentionally not mentioned in CHANGELOG. Will mention that after sometime.
