### ISSUE TITLE
xmlns attribute omitted?

### ISSUE THREAD

**Issue by chenroth-wix** [NaturalIntelligence/fast-xml-parser#55]
### Checklist
Please fill below checklist

* [X] Are you running the latest version?
* [X] Have you include sample input? 
* [X] Have you include actual output?
* [X] Have you include expected output?
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [ ] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"></project>
```

### Code
online editor is enough to demonstrate bug

### Output data
```js
{
    "project": {
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xsi:schemaLocation": "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    }
}
```

### expected data
```js
{
    "project": {
        "xmlns": "http://maven.apache.org/POM/4.0.0",
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xsi:schemaLocation": "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    }
}
```

**Comment by amitguptagwl** [comment]
Thanks for the reporting this issue. xmlns is expected to be removed only when configuration is set to ignore namespace. Let me fix this issue.

**Comment by amitguptagwl** [comment]
fixed. will publish the changes soon

**Comment by amitguptagwl** [comment]
changes are published. Please use 3.2.2

**Comment by chenroth-wix** [comment]
awesome! thanks for the prompt response
