### ISSUE TITLE
Text nodes are compressed together, is that normal ?

### ISSUE THREAD

**Issue by isometriq** [NaturalIntelligence/fast-xml-parser#56]
### Checklist
Please fill below checklist

* [X] Are you running the latest version?
* [X] Have you include sample input? 
* [X] Have you include actual output?
* [X] Have you include expected output?
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [X] Did you [bookmarked](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data
```
<p>text on the left <b>text in the middle</b> text on the right</p>
```

### Code
```js
const xml = '<p>text on the left <b>text in the middle</b> text on the right</p>';

let obj = fastXmlParser.parse(xml, {
    attributeNamePrefix : '@_',
    ignoreAttributes : false,
    allowBooleanAttributes : true,
    cdataTagName: "__cdata",
    cdataPositionChar: "\\c",
});

console.log(obj);
```

### Output data
```
{ p:
   { b: 'text in the middle',
     '#text': 'text on the lefttext on the right' }
}
```

### expected data
Not sure how...
Maybe `#text` could be an array representing the original layout and also referencing tag...
```
{ p:
   { b: 'text in the middle',
     '#text': ['text on the left','<b>','text on the right'] }
}
```
This one may be too much..
```
[
  { p: [
    {'#text': 'text on the left'},
    { b: 'text in the middle'},
    {'#text': 'text on the right'}
  ]}
]
```
I'm using it to parse HTML, validate and render back in html a portion of the tree. Maybe I'm not using the right tool ?

**Comment by isometriq** [comment]
I think this is what I was searching for
https://github.com/inikulin/parse5

Feel free to close is text nodes compression is an expected behavior.

**Comment by amitguptagwl** [comment]
@isometriq Yes "text nodes compression is an expected behavior.". However I can provide an option to keep them separate if it is required by many users. So for the time being I'm closing the issue. :smile:
