### ISSUE TITLE
unpairedTags matching requires paired tag sibling to work

### ISSUE THREAD

**Issue by nibk** [NaturalIntelligence/fast-xml-parser#562]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

unpairedTags option doesn't work if not followed immediately by a paired tag, its parent consumes the next sibling.

### Input

```
<root>
  <a>
    <unpaired>
  </a>
  <b>whatever</b>
</root>
```

### Code

As per the API example:

```js
const xmlDataStr = `
<root>
	<a>
		<unpaired>
	</a>
	<b>whatever</b>
</root>
`;

const options = {
  unpairedTags: ["unpaired"]
};
const parser = new XMLParser(options);
const output = parser.parse(xmlDataStr);

```

### Output
```
{
        "root": {
                "a": {
                        "unpaired": "",
                        "b": "whatever"
                }
        }
}
```

Correct structure can be generated by changing input to:

```
<root>
  <a>
    <unpaired><pair>foo</pair>
  </a>
  <b>whatever</b>
</root>
```

which triggers correct parsing, eg:

```
{
        "root": {
                "a": {
                        "unpaired": "",
                        "pair": "foo"
                },
                "b": "whatever"
        }
}
```

### expected data

```
{
        "root": {
                "a": {
                        "unpaired": "",
                },
                "b": "whatever"
        }
}
```

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
This issue is fixed in v4.2.2, 
<small>Please visit [solothought](https://solothought.com) to read about latest features released.</small>
