### ISSUE TITLE
jPath for self-closing XML tag includes slash

### ISSUE THREAD

**Issue by m-radzikowski** [NaturalIntelligence/fast-xml-parser#564]
* [x] Are you running the latest version? - yes, 4.2.2
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 

jPath in `updateTag()` callback for self closing tag ends with `/`, which I doubt is intended.

Because of this, you need to check two different jPaths, with and without `/`, to accurately process tags that may be empty.

### Input

```xml
<doc>
	<foo/>
	<foo>bar</foo>
	<lorem>ipsum</lorem>
</doc>
```

### Code

```js
const skip = ["doc.foo"];
const parser = new XMLParser({
	updateTag: (tagName, jPath) => {
		if (skip.includes(jPath)) {
			return false;
		}
		return tagName;
	},
});
```

### Output

```json
{
  "doc": {
    "foo": "",
    "lorem": "ipsum"
  }
}
```

### expected data

```json
{
  "doc": {
    "lorem": "ipsum"
  }
}
```

### additional info

Code works if the `skip` array is changed to: `["doc.foo", "doc.foo/"]` because for the self-closing tag jPath ends with `/`.
But I think that's easy to miss and not intended to be so? If you write code wanting to skip particular path and you don't test it with both self-closing and not-self closing tag you will be surprised.

Another workaround is to do:

```js
	updateTag: (tagName, jPath) => {
		if (
			skip.includes(jPath) ||
			(jPath.endsWith("/") && skip.includes(jPath.slice(0, -1)))
		) {
			return false;
		}
		return tagName;
	},
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
I believe this problem exists with not only jPath but tagName as well. I believe it should be a small fix.

**Comment by m-radzikowski** [comment]
No, actually, the `tagName` does not contain a trailing slash from what I've checked.
