### ISSUE TITLE
Read empty attributes

### ISSUE THREAD

**Issue by Peterculazh** [NaturalIntelligence/fast-xml-parser#578]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
I have xml which have empty attribute name. How I can read every attribute include empty attribute?
### Input
```
<Tag xmlns="sql='urn:schemas-microsoft-com:xml-sql'"><Anotertag>
<MyTag test1='1' test2='2' test3='3' test4='4'  ='some value'/>
</Anotertag></Tag>
```

### Code
```js
const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '',
});
const file = fs.readFileSync(`downloads/${filename}`, 'utf-8');
const data = parser.parse(file);
```

### Output
```js
{
  Tag: {
    Anotertag: {
      MyTag: {
        test1: "1",
        test2: "2",
        test3: "3",
        test4: "4",
      },
    },
    xmlns: "sql='urn:schemas-microsoft-com:xml-sql'",
  },
}
```

### expected data
```js
{
  Tag: {
    Anotertag: {
      MyTag: {
        test1: "1",
        test2: "2",
        test3: "3",
        test4: "4",
        EMPTY_TAG1: "some value"
      },
    },
    xmlns: "sql='urn:schemas-microsoft-com:xml-sql'",
  },
}
```

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
Honestly speaking, it is a very particular case and has very less use cases.

**Comment by amitguptagwl** [comment]
closing as no response. feel free to reopen it for further discussion
