### ISSUE TITLE
Valid XML with open quotes is marked as invalid

### ISSUE THREAD

**Issue by edi9999** [NaturalIntelligence/fast-xml-parser#58]
### Checklist

* [x] Are you running the latest version? : 3.2.3
* [x] Have you include sample input? 
* [x] Have you include actual output?
* [x] Have you include expected output?
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [bookmarked](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data

When I run the following code : 

```
require('fast-xml-parser').validate(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><h1 a="fo'a"></h1>`)
```

I get : 

```
{ err:
   { code: 'InvalidAttr',
     msg: 'Attributes for h1 have open quote' } }
```

Online, with the same input data, the error doesn't appear, but I think you might be using `parse` instead of `validate` (which also works locally)

I would expect the result to be a validationsuccess (return true)

It is allowed to have the single quote character if using double quotes as the delimiters (see https://stackoverflow.com/a/866894/1993501)

**Comment by amitguptagwl** [comment]
I'm marking it  as a bug without complete analysis. Will you mind to raise a PR?

**Comment by amitguptagwl** [comment]
fixed. please refer 3.2.4
