### ISSUE TITLE
Vulnerability open for a few days: GHSA-gpv5-7x3g-ghjv

### ISSUE THREAD

**Issue by alfaproject** [NaturalIntelligence/fast-xml-parser#591]
All the details here: https://github.com/advisories/GHSA-gpv5-7x3g-ghjv

This was opened a few days ago, but it looks like it was already patched? Or is it a false positive?

Either way, a release can be done or the vulnerability discarded, but as it stands our pipelines are stopped right now unless we ignore this but I'd prefer not to ignore without getting feedback here.

**Comment by jozefsukovsky** [comment]
I would like to add, that this report breaks auditing tools, e.g. pnpm audit (which can not omit/skip GHSA reports). And the report itself is a bit confusing, as it is not clear if it really is a security issue or just a suggestion. Hence, the consequences of this GHSA are quite unbalanced.

**Comment by WikiRik** [comment]
This seems to have been fixed in https://github.com/NaturalIntelligence/fast-xml-parser/commit/9a880b887916855c3a510869fd1ee268d7fe58b1 but a new release has not been published for this yet

**Comment by Afellman** [comment]
Any update on this?

**Comment by felixsonyusuftosin** [comment]
Will this be updated anytime soon?

**Comment by martin-walsh** [comment]
@amitguptagwl your published advisory on your most recent security fix means fix is hard to adopt https://github.com/advisories/GHSA-gpv5-7x3g-ghjv

**Comment by gijspon** [comment]
Need an update for this!

**Comment by aaleksandrov** [comment]
Would be awesome to release this - aws-sdk-v3 depends on this library and brings this vulnerability

**Comment by eclousersans** [comment]
> This seems to have been fixed in [9a880b8](https://github.com/NaturalIntelligence/fast-xml-parser/commit/9a880b887916855c3a510869fd1ee268d7fe58b1) but a new release has not been published for this yet

Would like to see a quick release for this, as the issue is currently blocking many of our CI pipelines.

**Comment by fernandopioli** [comment]
Hi @amitguptagwl. Could you please help us on that?
thanks

**Comment by amitguptagwl** [comment]
Sorry all to make everyone panic. But that is not the security issue but a patch to make a condition robust. If your systems are reporting the issue then let me merge and publish it.

**Comment by amitguptagwl** [comment]
Now I've updated all the advisories with fixed version. Please check if this solve your issue.

**Comment by aaleksandrov** [comment]
@amitguptagwl , as @WikiRik pointed [here](https://github.com/NaturalIntelligence/fast-xml-parser/issues/591#issuecomment-1598637725) a fix was already merged so it's a matter of releasing a new version as far as I understand

**Comment by amitguptagwl** [comment]
@aaleksandrov I have that too few mins ago. So I hope everything is shorted now.

**Comment by 7085** [comment]
This should not have been a security advisory in the first place but a regular issue, because the actual vulnerability was already fixed in 4.2.4.

**Comment by amitguptagwl** [comment]
I'm closing this issue. But if anything left then please reopen or comment.
