### ISSUE TITLE
removeNSPrefix option doesn't work

### ISSUE THREAD

**Issue by prithwirajbose** [NaturalIntelligence/fast-xml-parser#596]
* [x] Are you running the latest version? Yes
* [x] Have you included sample input, output, error, and expected output? Yes
* [x] Have you checked if you are using correct configuration? Yes
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? No

### Description
As per [Changelog](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CHANGELOG.md), ignoreNameSpace option in V3 is change to removeNSPrefix in V4. However, this option doesn't seem to work. This is one of the critical options because it changes the output JSON tagnames completely, for an input XML which has namespaces in tag names.

### Input
```
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"> <soapenv:Header/> <soapenv:Body><Data>Hello</Data></soapenv:Body></soapenv:Envelope>
```

### Code
```
const { XMLParser } = require("fast-xml-parser");
const fastXmlParser = new XMLParser();
var xmlParserOptions = {
    attrPrefix: "",
    textNodeName: "text",
    ignoreTextNodeAttr: false,
    removeNSPrefix: true,
    textNodeConversion: false
};
var json = fastXmlParser.parse(xmlBody, xmlParserOptions);
```

### Output
```
{"?xml":"","soapenv:Envelope":{"soapenv:Header":"","soapenv:Body":{ "Data": "Hello" }}}
```

### expected data
```
{"?xml":"","Envelope":{"Header":"","Body":{ "Data": "Hello" }}}
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by prithwirajbose** [comment]
Can someone please provide an update?

**Comment by amitguptagwl** [comment]
@prithwirajbose options are supposed to be passed in constructor not the parsing method. Check https://solothought.com/tutorial/fast-xml-parser-4.2-features/ for a few example how the library is supposed to be used.

Reopen the issue if you still face the problem.
