### ISSUE TITLE
How to handle values as string

### ISSUE THREAD

**Issue by waghcwb** [NaturalIntelligence/fast-xml-parser#597]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
I want to know how to parse values as strings, because the parse is changing data in my XML

### Code

```js
async function Main() {
  let parser = new XMLParser()
  let object = parser.parse(`
    <?xml version="1.0"?>
    <any_name>
        <person>
            <phone>600.00</phone>
        </person>
    </any_name>
  `)
  console.info(object)
  // { '?xml': '', any_name: { person: { phone: 600 } } }
}
```

### Output
```js
{ '?xml': '', any_name: { person: { phone: 600 } } }
```

### expected data
```js
{ '?xml': '', any_name: { person: { phone: '600.00' } } }
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
Please check `strnum` option and library for appropriate configuration.

**Comment by cecia234** [comment]
Hi, you can set `parseTagValue: false` inside the options to avoid having `strnum` parse the value for you.

```
let options =  {
    parseTagValue: false,
}
let parser = new XMLParser(options)
let object = parser.parse(`
    <?xml version="1.0"?>
    <any_name>
        <person>
            <phone>600.00</phone>
        </person>
    </any_name>
`)
console.info(object)
// { '?xml': '', any_name: { person: { phone: '600.00' } } }
```

You can also specify a custom tag parser inside the `options` object (`tagValueProcessor` property) to handle different cases based on your needs:

```
let options =  {
    parseTagValue: false,
    tagValueProcessor: (tagName, tagValue) => {
        console.log(tagValue)
        if (typeof tagValue === 'string') {
            return "HELLO!";
        } else if (tagValue === undefined || tagValue === null) {
            return null;
        }
        return tagValue.toString();
    }
}
let parser = new XMLParser(options)
let object = parser.parse(`
    <?xml version="1.0"?>
    <any_name>
        <person>
            <phone>600.00</phone>
        </person>
    </any_name>
  `)
console.info(object)
// { '?xml': '', any_name: { person: { phone: "HELLO!" } } }
```

**Comment by amitguptagwl** [comment]
I hope the issue is not anymore, or you can start the discussion thread.
