### ISSUE TITLE
Why it has "Object" rather than some value?

### ISSUE THREAD

**Issue by Mnemosynel** [NaturalIntelligence/fast-xml-parser#599]
* [Y ] Are you running the latest version?
* [Y ] Have you included sample input, output, error, and expected output? 
* [Y ] Have you checked if you are using correct configuration?
* [N ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input

```ts
const data = `
<items>
  <item>
    <name>Item 1</name>
    <price>10.99</price>
  </item>
  <item>
    <name>Item 2</name>
    <price>19.99</price>
  </item>
</items>
`;
```

### Code
```ts
function parseOriginFragmentDetail(data: string): any {
  const options = {
    ignoreAttributes: true,
    ignoreNameSpace: true,
    parseAttributeValue: false,
    parseNodeValue: true,
    allowBooleanAttributes: true
  };

  const parser = new XMLParser(options);
  const jsonObj = parser.parse(data);

  return jsonObj;
}
let jsonData1 = parseOriginFragmentDetail(data);
console.log(jsonData1);
console.log("***************");
```

### Output

{ items: { item: [ [Object], [Object] ] } }
***************

### expected data
```ts
 {
    "items": {
        "item": [
            {
                "name": "Item 1",
                "price": 10.99
            },
            {
                "name": "Item 2",
                "price": 19.99
            }
        ]
    }
}
```

**Would you like to work on this issue?**

- [Y ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by cecia234** [comment]
Hi! I think that's how `console.log()` works when printing an array of objects, when the array itself is contained in a nested object.
For example, if you try to print a similar object with this script:

```
const aaa = {
    a:{
        b: [ { d: 1 }, { e: 3 } ]
    }
}
console.log(aaa);
```

You obtain 

`{ a: { b: [ [Object], [Object] ] } }`

If you need the object parsed as string you can use `JSON.stringify()`.
With your script it should look something like this:

```
const data = `
<items>
  <item>
    <name>Item 1</name>
    <price>10.99</price>
  </item>
  <item>
    <name>Item 2</name>
    <price>19.99</price>
  </item>
</items>
`;

function parseOriginFragmentDetail(data: string): any {
  const options = {
    ignoreAttributes: true,
    ignoreNameSpace: true,
    parseAttributeValue: false,
    parseNodeValue: true,
    allowBooleanAttributes: true
  };

  const parser = new XMLParser(options);
  const jsonObj = parser.parse(data);

  return jsonObj;
}
let jsonData1 = parseOriginFragmentDetail(data);
console.log(JSON.stringify(jsonData1));
console.log("***************");
```

You should see this in the console

```
{"items":{"item":[{"name":"Item 1","price":10.99},{"name":"Item 2","price":19.99}]}}
***************
```

**Comment by Mnemosynel** [comment]
It works! Thanks!
