### ISSUE TITLE
Two Attributes with quotes gives error

### ISSUE THREAD

**Issue by edi9999** [NaturalIntelligence/fast-xml-parser#60]
This issue is very similar to #58 but not exactly the same : 

### Checklist

* [x] Are you running the latest version? : 3.2.3
* [x] Have you include sample input? 
* [x] Have you include actual output?
* [x] Have you include expected output?
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [bookmarked](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data

When I run the following code : 

```
require('fast-xml-parser').validate(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><foo name="First'attribute"/><foo name="First'attribute"/>`)
```

I get : 

```
{ err:
   { code: 'InvalidAttr',
     msg: 'attribute /><foo has no space in starting.' } }
```

I would expect the result to be a validationsuccess (return true)

It is allowed to have the single quote character if using double quotes as the delimiters (see https://stackoverflow.com/a/866894/1993501)

**Comment by amitguptagwl** [comment]
marking as bug without complete analysis. Will you mind to raise a PR?

**Comment by amitguptagwl** [comment]
What is the different between both issues?

**Comment by edi9999** [comment]
The two issues were similar but the error messages were different in the case where you had two tags with single quotes inside attributes. 

I have just tested with the version 3.2.4, and this problem is no more showing up.

Thanks a lot for your reactivity, very much appreciated !
