### ISSUE TITLE
Issue with XML containing subdeclaration

### ISSUE THREAD

**Issue by edi9999** [NaturalIntelligence/fast-xml-parser#62]
* [x] Are you running the latest version?
* [x] Have you include sample input? 
* [x] Have you include actual output?
* [x] Have you include expected output?
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [bookmarked](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

### Input data

```js
require('fast-xml-parser').validate(`<?xml version="1.0"?><?mso-contentType?><h1></h1>`)
```

### Output data

```
{ err:
   { code: 'InvalidXml',
     msg: 'XML declaration allowed only at the start of the document.' } }
```

### expected data

true

**Comment by Delagen** [comment]
I think processing instructions not covered yet

**Comment by amitguptagwl** [comment]
Sorry for the late response. It is a festive season here. As @Delagen said, it is not covered yet. It's a very small change. I'll publish the changes on Monday.

**Comment by amitguptagwl** [comment]
Please use 3.4.0

**Comment by keponk** [comment]
@amitguptagwl i can't find a reference on how to access the processing instructions. Is it correct to say that only the validator is aware of it? I would like to access the processing instructions after validation as well, they contain valuable info.

**Comment by amitguptagwl** [comment]
Validator is checking for valid syntax of PI. And parser is ignoring them to read. Can you please tell me some use case where you feel you want keep their data and the desire format of the data. We can plan to include it into v4.

**Comment by keponk** [comment]
@amitguptagwl thanks for the quick reply. PI's do have a dedicated purpose, normally it is a connection between XML authors and the xml-aware application [1].

My use case is that I receive an XML from someone else. This author decided to use PI's to embed metadata of the XML. One could argue that the purpose of PIs is not related to metadata and the author could've chosen to embed that metadata in a real tag, but this is where we are and technically the author __is__ complying with the XML standard.

Further, it seems to me that a parser reading a valid xml should return to me all the information in there, including the PI, which is part of XML standard. Sadly, as XML popularity declines it seems to me there are not many robust parsers out there who do take PIs into account as it may be more of an obscure use case in 2020, I've only found hobby parser projects that do keep PI's in the JSON output.

Regarding the desired format, I think continuing with fast-xml-parser standard would be best, that is, in similarity to using the `attr` keyword, the PIs could be packed as an array with a relevant keyword such as `instr`. They should follow the same nesting rules as `attr` if possible.

Let me know if this makes sense or if I can provide more specific examples.

[1] https://docstore.mik.ua/orelly/xml/xmlnut/ch17_02.htm

**Comment by amitguptagwl** [comment]
I have created another issue to track it

**Comment by amitguptagwl** [comment]
Please check v4.0.0-beta.6
