### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tagName') when parsing closing tag without an opening tag at the start of XML document

### ISSUE THREAD

**Issue by lulunac27a** [NaturalIntelligence/fast-xml-parser#620]
* [x] Have you included sample input, output, error, and expected output? 
* [x] Are you running the latest version?
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
I got an error saying TypeError: Cannot read properties of undefined (reading 'tagName') when I put closing tag at the start of XML document
### Input

`</a>`
### Code
```js
new XMLParser().parse('</a>');
XMLValidator().validate('</a>');

```

### Output

`TypeError: Cannot read properties of undefined (reading 'tagName')`
### expected data

Error: closing tag found at start of XML document
**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by AirOne01** [comment]
Can confirm the bug and reproduce.

**Comment by MaelAbgrall** [comment]
So I can reproduce it on the online editor, but not in my code.

I double-checked yarn, I'm using v4.3.5
