### ISSUE TITLE
Decimal point is not preserved after parsed to json.

### ISSUE THREAD

**Issue by shikeiyan** [NaturalIntelligence/fast-xml-parser#644]
[] Are you running the latest version?
[/ ] Have you included sample input, output, error, and expected output? 
[/] Have you checked if you are using correct configuration?
[/] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

**Description**
Tried out some ways below but still not working:
1) add options leadingZeros: false
2) add options parseNodeValue: false 
3) upgrade to latest version

Current version used: 4.0.2

**Code**

> const { XMLParser, XMLBuilder } = require("fast-xml-parser");
> const options = {
>     ignoreAttributes : false,
>     preserveOrder: true,
>     trimValues: false
> };
> 
> const Parser = new XMLParser(options);
> const Builder = new XMLBuilder(options);
> 
> const XMLUtils = {
>     parse: (xmlString) => {
>         return Parser.parse(xmlString); // produce json
>     },
>     build: (json) => {
>         return Builder.build(json); // produce xml string
>     },
> }

> const xmlString = `<correctResponse><value>33.00</value></correctResponse>`;
> const xmlJson = XMLUtils.parse(xmlString);
> console.dir(xmlJson, {depth:null});
> 

**Output**
`[
  {
    correctResponse: [
      { value: [ { '#text': 33 } ] }
    ]
  }
]`

**Expected data**
`[
  {
    correctResponse: [
      { value: [ { '#text': 33.00 } ] }
    ]
  }
]`

**Comment by amitguptagwl** [comment]
Please check https://github.com/NaturalIntelligence/strnum

**Comment by shikeiyan** [comment]
Hi @amitguptagwl , I have tried to pass in options with leadingZeros: false and the decimal point is not preserved.
Refer to the attachment below, the issue is replicable in online tool as well with unchecked "parse number with leading zeros".
<img width="890" alt="xml parser" src="https://github.com/NaturalIntelligence/fast-xml-parser/assets/34058332/34dba5c8-bb0f-48a8-ab3c-e7adaf8945ba">

**Comment by amitguptagwl** [comment]
To keep a number as "33.00", it should not be parsed as number but as string only.

**Comment by shikeiyan** [comment]
Hi @amitguptagwl , may I know any workaround or any fix for this on your side?

**Comment by amitguptagwl** [comment]
:) This is not a bug. So no fix. In javascript, you can't represent a number like `33.00`. So you need to make it as a string.

![image](https://github.com/NaturalIntelligence/fast-xml-parser/assets/7692328/64505135-0a45-4eb0-ac3d-4bffc6dafb13)
