### ISSUE TITLE
XML parse looks good on Online tool, but when using API crashes

### ISSUE THREAD

**Issue by hectorgrecco** [NaturalIntelligence/fast-xml-parser#648]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
When I'm parsing a specific XML using the API, the package crashes and throws the error on the image. But, when I use the online validator, it does not. Whats happening? 

### Code
```js
const options = {
        numberParseOptions: {
          leadingZeros: true,
          hex: true,
          skipLike: /\+[0-9]{10}/,
        },
        trimValues: true,
        removeNSPrefix: true,
        processEntities: false,
        parseTagValue: true,
      };
    
      const parser = new XMLParser(options);
      return parser.parse(xmlData);
```

### Output
<img width="763" alt="image" src="https://github.com/NaturalIntelligence/fast-xml-parser/assets/10110093/2693a86a-1573-45e4-8043-ce077f8d4745">

### expected data
Don't throw an error

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
closing as no response. feel free to reopen it for further discussion
