### ISSUE TITLE
Any tag which has a format like <!D%s> where %s - any sequence of characters is perceived as <!DOCTYPE> and causes error

### ISSUE THREAD

**Issue by StombieIT** [NaturalIntelligence/fast-xml-parser#649]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
```html
<some-obj>
    <!D>
    <first-arg>123</first-arg>
    <second-arg>321</second-arg>
</some-obj>
```

### Output

```
Error: Invalid Tag instead of DOCTYPE
```

### Expected behaviour
Parser will ignore such kind of tags.

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
Sorry I couldn't understand your expectations, `!D` doesn't have any closing tag, it has invalid name then why should parser ignore it?

**Comment by amitguptagwl** [comment]
closing as no response. feel free to reopen it for more discussion
