### ISSUE TITLE
Not getting attribute value using XMLBuilder.build function

### ISSUE THREAD

**Issue by Faizan2030** [NaturalIntelligence/fast-xml-parser#651]
* [x] Are you running the latest version? Using 4.3.6
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? Not working for me, 

### Description
I need to include xml attribute, like this : ```<internal-name tokenized="true">test test &gt; 14</internal-name>```
### Code
```js
defaultXmlOptions: {
      ignoreAttributes: false,
      attributeNamePrefix: "@_",
      indentBy: "  ",
      textNodeName: "#text",
      format: true,
  },
var testJson = { component: {
      "internal-name": {
          "#text": "test test > 14",
          "@_tokenized": true
      }
  }}
```
Here is the code that converts:
```js
var parser = new XMLBuilder(CRUDService.defaultXmlOptions);
var xml = parser.build(testJson);
```
That attribute should have ="true"
### Output
```
<component>
  <internal-name tokenized>test test &gt; 14</internal-name>
</component>
```

### expected data
```
<component>
  <internal-name tokenized="true">test test &gt; 14</internal-name>
</component>
```

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

I posted the question here as well https://stackoverflow.com/questions/78354831/how-to-include-attribute-value-while-building-xml-using-fast-xml-parser

**Comment by Faizan2030** [comment]
```
defaultXmlOptions: {
      ignoreAttributes: false,
      attributeNamePrefix: "@_",
      indentBy: "  ",
      textNodeName: "#text",
      format: true,
  },
var testJson = { component: {
      "internal-name": {
          "#text": "test test > 14",
          "@_tokenized": true
      }
  }}
```

**Comment by amitguptagwl** [comment]
got your problem. `"@_tokenized": true` this is set as boolean. Can you try to set it as string?

**Comment by amitguptagwl** [comment]
closing the issue. feel free to reopen if still exist. Please also check for v5
