### ISSUE TITLE
Object doesn't support property or method 'trimStart'

### ISSUE THREAD

**Issue by asaadbaw** [NaturalIntelligence/fast-xml-parser#652]
* [ x] Are you running the latest version?
* [ x] Have you included sample input, output, error, and expected output? 
* [x ] Have you checked if you are using correct configuration?
* [ x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
I have a uwp reactnative app when I run as debug works fine but when I release the application it gives me this error:
Object doesn't support property or method 'trimStart'
### Input

xml checked online in many xml validation tools and its fine

### Code

  private parser_options = {
    ignoreAttributes: false,
    ignoreDeclaration: true,
    ignorePiTags: true,
    parseTagValue: false,
    trimValues: false,
  };

  constructor(xml_str?: string) {
    try {
      const parser = new XMLParser(this.parser_options);

      if (xml_str) {
        this.xml_object = parser.parse(xml_str) ?? {
          '?xml': { '@_version': '1.0', '@_encoding': 'UTF-8' },
        };
      } else {
        this.xml_object = {
          '?xml': { '@_version': '1.0', '@_encoding': 'UTF-8' },
        };
      }
    } catch (e) {
      console.log({
        type: 'exception',
        timestamp: new Date(),
        xml_str,
        error: e.message,
      });
    }
  }

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [x ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
Can you please share the sample XML that is causing issue? smaller is preferable.

**Comment by amitguptagwl** [comment]
Closing the issue. Please reopen if problem exist with sample XML and library version.
