### ISSUE TITLE
Parser erroneously adds `"@_/": true` attr for self-closing stop nodes 

### ISSUE THREAD

**Issue by smoores-dev** [NaturalIntelligence/fast-xml-parser#654]
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? (there doesn't seem to be a way to add stop nodes to the online tool)

### Description
 

When the `allowBooleanAttributes` flag is set on `XMLParser`, the parser will interpret the closing `/` in a self-closing stop node as a boolean attribute. This introduces further problems when attempting to build the parsed data back into a string, as it produces invalid XML. E.g.,  `<script src="script.js" />` becomes `<script src="script.js" //>` (note the double slash).

It is possible to implement a workaround by adding an `updateTag` method that removes `@_/` attributes.

### Input

```xhtml
<script src="script.js" />
```

### Code
```js
const parser = new XMLParser({
    allowBooleanAttributes: true,
    ignoreAttributes: false,
    stopNodes: ["*.pre", "*.script"],
})

parser.parse(inputString)
```

### expected data

```js
{ script: { '@_src': 'script.js', '@_/': true } }
```

**Would you like to work on this issue?**

- [X] Yes (could use some guidance, though)
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
Thanks to highlight it. We would have to put a condition in the code to avoid an attribute having the name "/" or "/>" or ">" or any other possibility. 

This check can be placed in a [buildAttributesMap function](https://github.com/NaturalIntelligence/fast-xml-parser/blob/1a384a585d7d8af68366e27d9df31d47fb547660/src/xmlparser/OrderedObjParser.js#L127) and [attribute function](https://github.com/NaturalIntelligence/fast-xml-parser/blob/1a384a585d7d8af68366e27d9df31d47fb547660/src/v5/OutputBuilders/BaseOutputBuilder.js#L6) for v5.
