### ISSUE TITLE
XMLBuilder Incorrectly Serializes String "true" as Boolean Attribute

### ISSUE THREAD

**Issue by Undefined01** [NaturalIntelligence/fast-xml-parser#656]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
 
When using XMLBuilder to serialize attributes with the string value "true", they are incorrectly serialized as Boolean attributes, regardless of the Allow Boolean Attributes option's state. This results in an output where the attribute appears without an explicit value, which differs from the expected behavior where the attribute should explicitly show "true".

### Input

```json
{
    "test": {
        "@_property1": "true",
        "@_property2": "false"
    }
}
```

### Code
```js
const fxp = require('fast-xml-parser');
const opts = {
    ignoreAttributes: false
};
const xmlObj = {
    test: {
        "@_property1": "true",
        "@_property2": "false"
    }
};
const builder = new fxp.XMLBuilder(opts);
console.log(builder.build(xmlObj));

```

### Output

```xml
<?xml version="1.0"?>
<test property1 property2="false"></test>
```

### expected data

```xml
<?xml version="1.0"?>
<test property1="true" property2="false"></test>
```

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
Please read https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/3.XMLBuilder.md

**Comment by Undefined01** [comment]
Setting `suppressBooleanAttributes` to `false` solves this problem.

I think it is kind of unintuitive. It's odd that `{"@_Property": "true"}` gets treated as a boolean attribute and suppressed, yet `{"@_Property": false}` and `{"@_Property": "false"}` are not affected in the same way. Besides, I would expect they will not be regarded as boolean attributes and suppressed after setting `allowBooleanAttributes` to false.

**Comment by wodepig** [comment]
> 设置为 可解决此问题。`suppressBooleanAttributes``false`
> 
> 我认为这有点不直观。奇怪的是，它被视为 boolean 属性并被抑制，但 并且没有以相同的方式受到影响。此外，我希望它们不会被视为布尔属性并在设置为 false 后被抑制。`{"@_Property": "true"}``{"@_Property": false}``{"@_Property": "false"}``allowBooleanAttributes`

is worked ,thanks
