### ISSUE TITLE
Configuration to explicitly disable number parsing for specific xml tag values

### ISSUE THREAD

**Issue by kule1015** [NaturalIntelligence/fast-xml-parser#661]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description

Hi there,

when parsing an XML tag that can have tag values of "A6" or "6.0", the intention is that the specific XML tag values are always handled as strings. An attempt was made to utilise the parser option "tagValueProcessor". During debugging, it was observed that within the function *OrderedObjParser.parseTextData*, the function *OrderedObjParser.parseValue* is called on the result of the callback of *tagValueProcessor*. The function *OrderedObjParser.parseValue* will parse the value "6.0" as the integer "6". However, all tag values of "*evil*" should be parsed as strings.

Did I miss anything or is this intended behavior? Thanks in advance for taking the time!

### Input

```xml
<evil>6.0</evil>

<evil>A6</evil>
```

### Code
```js
import { XMLParser } from "fast-xml-parser";

const XML_PARSER_OPTIONS = {
  tagValueProcessor: (tagName: string, tagValue: string, jPath: string, hasAttributes: boolean, isLeafNode: boolean) => {
    if (tagName === "evil") {
      return String(tagValue)
    }
    return tagValue;
  },
};

const xmlParser = new XMLParser(XML_PARSER_OPTIONS);

const xml = "<evil>6.0</evil>"

const xml2 = "<evil>A6</evil>"

const parsedXml = xmlParser.parse(xml);
console.log(JSON.stringify(parsedXml))

const parsedXml2 = xmlParser.parse(xml2);
console.log(JSON.stringify(parsedXml2))
```

### Output

```json
{"evil":6}
{"evil":"A6"}
```

### expected data

```json
{"evil":"6.0"}
{"evil":"A6"}
```

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
In your case, you want o set the original value without parsing. As per docs, "If tagValueProcessor returns undefined or null then original value would be set without parsing."

Please check docs for more ways of achieving it. Please also give a try to v5. Let me know if you still need any help.

**Comment by kule1015** [comment]
Ah my mistake. Thanks a lot!
