### ISSUE TITLE
Foriegn characters are translated to what seems to be a Unicide Hex

### ISSUE THREAD

**Issue by RUlens** [NaturalIntelligence/fast-xml-parser#663]
* [ ] Are you running the latest version? No, I'm running 4.4.0
* [x] Have you included sample input, output, error, and expected output?  Yes
* [x] Have you checked if you are using correct configuration? Yes I think so
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? Yes and I don't have the issue there

### Description
I use the parser to convert public XML's to JSON but it seems that foreign character like for example ó are converted when imported to &#xF3;
### Input

I included an example URL I fetch from https://www.immodelux.com/feed/kyero/ver/kantoren-samenwerking

### Code
export async function getXMLAndParseToJSON() {
    return fetch("https://www.immodelux.com/feed/kyero/ver/kantoren-samenwerking/", {
            'method': 'get',
            headers: { 'Content-Type': 'application/XML' }
        })
        .then((httpResponse) => {
            return httpResponse.text()
                .then((response) => {
                    xml = String(response)
                    xml = parser.parse(xml)
                    return xml.root.property
                })
        })

}

### Output
Part of JSON 

{
  "id": 423667,
  "date": "2023-12-07 11:29:40",
  "ref": "A000008",
  "price": 399900,
  "currency": "EUR",
  "price_freq": "sale",
  "new_build": 1,
  "type": "Bungalow",
  "town": "Finestrat",
  "province": "Alicante",
  "location_detail": "Balc&#xF3;n de finestrat",
  "beds": 3,
  "baths": 2,
  "pool": 1,
  "surface_area": {
    "built": 256
  },
  "url": {
    "es": "http://www.immodelux.com/es/propiedad/finestrat-moderno-chalet-adosado-de-nueva-construccion-con-piscina-privada-a000008/",
    "en": "http://www.immodelux.com/en/property/finestrat-modern-semi-detached-newly-built-villa-with-private-pool-a000008/",
    "de": "http://www.immodelux.com/de/eigentum/finestrat-moderne-neu-gebaute-doppelhaushalfte-mit-privatem-pool-a000008/",
    "fr": "http://www.immodelux.com/fr/propriete/finestrat-villa-moderne-jumelee-de-construction-recente-avec-piscine-privee-a000008/",
    "nl": "http://www.immodelux.com/eigenschap/finestrat-moderne-nieuwbouw-bungalow-a000008/"
  },
  "video_url": "",
  "desc": {
    "es": "Este exclusivo complejo de nueva construcci&#xF3;n tiene vistas a Benidorm.. En este complejo encontrar&#xE1; exclusivas casas adosadas y bungalows.. . Todas las propiedades tienen piscina privada. Las casas de la planta superior tienen un sol&#xE1;rium.. . Esta propiedad se encuentra en la planta baja y tiene 3 dormitorios y 3 ba&#xF1;os, gran sal&#xF3;n y comedor, cocina abierta con grandes ventanales, gran jard&#xED;n con piscina privada y plaza de aparcamiento.",
    "en": "This exclusive new-build complex overlooks Benidorm.. In this complex you will find exclusive semi-detached houses and bungalows.. . All properties have a private pool. The houses on the top floor have a solarium.. . This property is on the ground floor and has 3 bedrooms and 3 bathrooms, large living and dining room, open kitchen with large windows, large garden with private pool and parking space.",
    "de": "Dieser exklusive Neubaukomplex liegt mit Blick auf Benidorm.. In dieser Anlage finden Sie exklusive Doppelhaush&#xE4;lften und Bungalows.. . Alle Immobilien haben einen privaten Pool. Die H&#xE4;user im obersten Stockwerk haben eine Sonnenterrasse.. . Dieses Anwesen befindet sich im Erdgeschoss und verf&#xFC;gt &#xFC;ber 3 Schlafzimmer und 3 B&#xE4;der, gro&#xDF;es Wohn- und Esszimmer, offene K&#xFC;che mit gro&#xDF;en Fenstern, gro&#xDF;er Garten mit privatem Pool und Parkplatz.",
    "fr": "Ce complexe exclusif, de construction r&#xE9;cente, surplombe Benidorm.. Dans ce complexe, vous trouverez des maisons jumel&#xE9;es et des bungalows exclusifs.. . Toutes les propri&#xE9;t&#xE9;s disposent d'une piscine priv&#xE9;e. Les maisons du dernier &#xE9;tage disposent d'un solarium.. . Cette propri&#xE9;t&#xE9; est au rez-de-chauss&#xE9;e et comprend 3 chambres et 3 salles de bains, un grand salon et une salle &#xE0; manger, une cuisine ouverte avec de grandes fen&#xEA;tres, un grand jardin avec une piscine priv&#xE9;e et un espace de stationnement.",
    "nl": "Dit exclusief nieuwbouw complex heeft uitzicht op Benidorm.&#xA0;In dit complex vind u exclusieve geschakelde woningen en bungalows.&#xD;\n&#xD;\nAlle woningen hebben een priv&#xE9; zwembad.&#xD;&#xD;\nDe woningen op de bovenste verdieping hebben een solarium.&#xD;&#xD;\nDeze woning&#xA0;heeft 3&#xA0;slaapkamers en 2 badkamers, grote woon- en eetkamer, open keuken met grote ramen, solarium en parkeerplaats.&#xD;\n&#xD;\nVoorziene opleverdatum is april 2025"
  },
  "features": {
    "feature": [
      "air conditioning yes",
      "heating yes",
      "terrace",
      "garden",
      "orientation: Sur"
    ]
  },
  "images": {
    "image": [
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44444d8b66-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444b89b36-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444bf2546-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444b2c738-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444455f762-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444657e19-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44446be957-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444472e167-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444789507-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44448005ab-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444868b40-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44448cb3b5-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444493da30-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44449b8478-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444a3e18d-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444aa61bd-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444c66c2d-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444ccdcaa-source.jpg"
      }
    ]
  }
}

### expected data
{
  "id": 423667,
  "date": "2023-12-07 11:29:40",
  "ref": "A000008",
  "price": 399900,
  "currency": "EUR",
  "price_freq": "sale",
  "new_build": 1,
  "type": "Bungalow",
  "town": "Finestrat",
  "province": "Alicante",
  "location_detail": "Balcón de finestrat",
  "beds": 3,
  "baths": 2,
  "pool": 1,
  "surface_area": {
    "built": 256
  },
  "url": {
    "es": "http://www.immodelux.com/es/propiedad/finestrat-moderno-chalet-adosado-de-nueva-construccion-con-piscina-privada-a000008/",
    "en": "http://www.immodelux.com/en/property/finestrat-modern-semi-detached-newly-built-villa-with-private-pool-a000008/",
    "de": "http://www.immodelux.com/de/eigentum/finestrat-moderne-neu-gebaute-doppelhaushalfte-mit-privatem-pool-a000008/",
    "fr": "http://www.immodelux.com/fr/propriete/finestrat-villa-moderne-jumelee-de-construction-recente-avec-piscine-privee-a000008/",
    "nl": "http://www.immodelux.com/eigenschap/finestrat-moderne-nieuwbouw-bungalow-a000008/"
  },
  "video_url": "",
  "desc": {
    "es": "Este exclusivo complejo de nueva construcci&#xF3;n tiene vistas a Benidorm.. En este complejo encontrar&#xE1; exclusivas casas adosadas y bungalows.. . Todas las propiedades tienen piscina privada. Las casas de la planta superior tienen un sol&#xE1;rium.. . Esta propiedad se encuentra en la planta baja y tiene 3 dormitorios y 3 ba&#xF1;os, gran sal&#xF3;n y comedor, cocina abierta con grandes ventanales, gran jard&#xED;n con piscina privada y plaza de aparcamiento.",
    "en": "This exclusive new-build complex overlooks Benidorm.. In this complex you will find exclusive semi-detached houses and bungalows.. . All properties have a private pool. The houses on the top floor have a solarium.. . This property is on the ground floor and has 3 bedrooms and 3 bathrooms, large living and dining room, open kitchen with large windows, large garden with private pool and parking space.",
    "de": "Dieser exklusive Neubaukomplex liegt mit Blick auf Benidorm.. In dieser Anlage finden Sie exklusive Doppelhaush&#xE4;lften und Bungalows.. . Alle Immobilien haben einen privaten Pool. Die H&#xE4;user im obersten Stockwerk haben eine Sonnenterrasse.. . Dieses Anwesen befindet sich im Erdgeschoss und verf&#xFC;gt &#xFC;ber 3 Schlafzimmer und 3 B&#xE4;der, gro&#xDF;es Wohn- und Esszimmer, offene K&#xFC;che mit gro&#xDF;en Fenstern, gro&#xDF;er Garten mit privatem Pool und Parkplatz.",
    "fr": "Ce complexe exclusif, de construction r&#xE9;cente, surplombe Benidorm.. Dans ce complexe, vous trouverez des maisons jumel&#xE9;es et des bungalows exclusifs.. . Toutes les propri&#xE9;t&#xE9;s disposent d'une piscine priv&#xE9;e. Les maisons du dernier &#xE9;tage disposent d'un solarium.. . Cette propri&#xE9;t&#xE9; est au rez-de-chauss&#xE9;e et comprend 3 chambres et 3 salles de bains, un grand salon et une salle &#xE0; manger, une cuisine ouverte avec de grandes fen&#xEA;tres, un grand jardin avec une piscine priv&#xE9;e et un espace de stationnement.",
    "nl": "Dit exclusief nieuwbouw complex heeft uitzicht op Benidorm.&#xA0;In dit complex vind u exclusieve geschakelde woningen en bungalows.&#xD;\n&#xD;\nAlle woningen hebben een priv&#xE9; zwembad.&#xD;&#xD;\nDe woningen op de bovenste verdieping hebben een solarium.&#xD;&#xD;\nDeze woning&#xA0;heeft 3&#xA0;slaapkamers en 2 badkamers, grote woon- en eetkamer, open keuken met grote ramen, solarium en parkeerplaats.&#xD;\n&#xD;\nVoorziene opleverdatum is april 2025"
  },
  "features": {
    "feature": [
      "air conditioning yes",
      "heating yes",
      "terrace",
      "garden",
      "orientation: Sur"
    ]
  },
  "images": {
    "image": [
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44444d8b66-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444b89b36-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444bf2546-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444b2c738-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444455f762-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444657e19-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44446be957-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444472e167-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444789507-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44448005ab-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444868b40-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44448cb3b5-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b444493da30-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b44449b8478-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444a3e18d-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444aa61bd-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444c66c2d-source.jpg"
      },
      {
        "url": "https://www.immodelux.com/objetos/temp/source/immodelux/immodelux-propiedades_63b4444ccdcaa-source.jpg"
      }
    ]
  }
}

**Would you like to work on this issue?**

- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
It was quite difficult to follow. Can you please short the input XML and highlight the issue?

**Comment by amitguptagwl** [comment]
closing as no response. feel free to reopen it for further discussion
