### ISSUE TITLE
attribute value with "true" string is not able to buid again with XMLBuilder

### ISSUE THREAD

**Issue by stylejuya** [NaturalIntelligence/fast-xml-parser#664]
* [x ] Are you running the latest version?
* [x ] Have you included sample input, output, error, and expected output? 
* [ x] Have you checked if you are using correct configuration?
* [ x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
in the attribute if there is a value with "true" string, It is not able to build back.
### Input
 `<married firstTime="Yes" test="true">Yes</married>`

### Code
```js
Include the code being used for parsing
```

### Output

    <married firstTime="Yes" test>Yes</married>
### expected data

    <married firstTime="Yes" test="true">Yes</married>
**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
Have you checked the documents?

**Comment by stylejuya** [comment]
Could you highlight the doc? I did not see any related to this .

**Comment by amitguptagwl** [comment]
There are many properties that can help you in different ways. Please read about all the properties. It's not a long document.

**Comment by stylejuya** [comment]
What kind of answer is this? When the value is “true” it does not build
back and when the value is “false” it build back. This behavior is already
the library does not work  seamlessly.  I know you don’t get paid for the
open source . However, I have never seen this level of kind response. Thank
you and Have a good day

2024년 7월 13일 (토) 04:47, Amit K Gupta ***@***.***>님이 작성:

**Comment by amitguptagwl** [comment]
If you check the history. Most of the questions I receive because people don't read documentation. Anyways, what properties have you tried yet? Have you tried `suppressBooleanAttributes`?
