### ISSUE TITLE
How to put the text in the front of a tag when parse a xml?

### ISSUE THREAD

**Issue by wxfred** [NaturalIntelligence/fast-xml-parser#669]
Input
```
const xml = `
<a>
  some text here
  <c attr="xxx"></c>
  <b attr="xxx"></b>
</a>
`
```

Output by
```
const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '',
  textNodeName : 'text',
})
const xmlObj = parser.parse(xml)
console.log(xmlObj)
```

```
// Output 1
{
 a : {
    c: { attr: 'xxx' },
    b: { attr: 'xxx' },
    text: 'some text here',
  }
}
```

Desired output
```
// Output 2
{
 a : {
    text: 'some text here',
    c: { attr: 'xxx' },
    b: { attr: 'xxx' },
  }
}
```

If i rebuild the output,
```
const builder = new XMLBuilder({
  gnoreAttributes: false,
  attributeNamePrefix: '',
  textNodeName : 'text',
  format: true,
  indentBy: '    ',
})
console.log(builder.build(xmlObj))
```
the rebuild result of Output 1 is
```
<a>
    <c attr="xxx"></c>
    <b attr="xxx"></b>
 some text here</a>
```
the rebuild result of Output 2 is below, and the order of tag's text is the same as the **Input**, this is what i want
```
<a>
some text here    <c attr="xxx"></c>
    <b attr="xxx"></b>
</a>
```

**Comment by amitguptagwl** [comment]
do you mean the  indentation of tag's text is not as per expectation?

**Comment by wxfred** [comment]
@amitguptagwl Sorry, I make a mistake. The builder can build tag's text in right order, what i want is changing the parse order of tag's text. I have changed the title and description of this topic, pls have a look.

**Comment by amitguptagwl** [comment]
This should solve your issue: https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#preserveorder

**Comment by wxfred** [comment]
@amitguptagwl **When preserveOrder: true , you get some long ugly result.**
The result is ugly, it is not convenient to add something or modify something.

**Comment by amitguptagwl** [comment]
@wxfred In JS, you can ensure the sequence of properties. This is not the issue with this library. Hence, that;s the only solution.
