### ISSUE TITLE
Text is change the Sub Character and its showing like this   á´¸á¶¦áµáµ 

### ISSUE THREAD

**Issue by BilalHadid** [NaturalIntelligence/fast-xml-parser#676]
* 4.5.0
*  {"desc": "Snap-to-snap 60-minute presentation of a Big Ten Football game.", "title": "B1G Football in 60  á´¸á¶¦áµáµ"}
* yes

* Yes I tried all the options

### Description
if the text with sub character then it should be display we don't want to change it. Text should should not be change
### Input

    <programme start="20240905130000 +0000" stop="20240905140000 +0000" channel="ABCWABC.us">
        <title>Live with Kelly and Mark  ᴺᵉʷ</title>
        <desc>S03E03 Carrie Coon (&quot;His Three Daughters&quot;); Daniel Dae Kim (Broadway&apos;s &quot;Yellow Face&quot;); Tamron Hall leads Kelly and Mark in a cooking demo with Lish Steiling.</desc>
    </programme>
    
    
### Code
const parser = new XMLParser();
    // The parse function is synchronous but we can still make this function async
    const result = parser.parse(chunk);

### Output

{"desc": "Snap-to-snap 60-minute presentation of a Big Ten Football game.", "title": "B1G Football in 60  á´¸á¶¦áµáµ"}
### expected data
{"desc": "Snap-to-snap 60-minute presentation of a Big Ten Football game.", "title": "B1G Football in 60  ᴸᶦᵛᵉ"}

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates. Visit [SoloThought](https://solothought.com) to know about recent features.

**Comment by amitguptagwl** [comment]
FXP doesn't convert the text by it's own. It might be due to character encoding. Did you try to debug the issue with tagValueProcessor where you should receive raw value

**Comment by BilalHadid** [comment]
@amitguptagwl Yes I tried to debug and console it its showing the same data and I tried to use he or base 64 but Its not working :(

**Comment by amitguptagwl** [comment]
when you log it without FXP, do you get the same text you pass or the cnverted one?
