### ISSUE TITLE
Unable to use version 5 for XMLParser

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [NaturalIntelligence/fast-xml-parser#682]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Have you checked the [docs](https://github.com/NaturalIntelligence/fast-xml-parser/tree/master/docs) for helpful APIs and examples?

### Description
I've been testing this to replace xml2json since it doesn't seem to be maintained. I've been able to get this working for my data, however I need unpaired to parse as an empty object like my previous parser did. This was supposed to be done with v5. However, following the documentation v5 just errors out as not being found. Changing things to src/v5/... results in the same.

### Input
followed the documentation for v5. Importing XMLParser from 'fast-xml-parser' works, but I don't get the output I'm looking for.

### Code
```js
import {XMLParser} from "fast-xml-parser/v5/XMLParser";
//or
import {XMLParser} from "fast-xml-parser/src/v5/XMLParser";
```

### Output
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'F:\Local Documents\Documents\VisualStudioCodeProjects\FGU-Extension-LocalClient\node_modules\fast-xml-parser\v5\XMLParser'

Or

Could not find a declaration file for module 'fast-xml-parser/src/v5/XMLParser'. 'f:/Local Documents/Documents/VisualStudioCodeProjects/FGU-Extension-LocalClient/node_modules/fast-xml-parser/src/v5/XMLParser.js' implicitly has an 'any' type.
  If the 'fast-xml-parser' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'fast-xml-parser/src/v5/XMLParser';`

### expected data
I'd expect to be able to use v5 to test the object parsing.

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment]
Thanks to highlight Following is working for me. I've updated the same in the docs

```
const XMLParser = require("fast-xml-parser/src/v5/XMLParser");

describe("XMLParser", function() {
  it("should import v5", function() {
    const parser = new XMLParser();
  });
});
```
