### ISSUE TITLE
Feature Request: TypeScript type definitions

### ISSUE THREAD

**Issue by bb** [NaturalIntelligence/fast-xml-parser#69]
Hi there,
it would be great if fast-xml-parser had typescript support.

Would you be willing to include types directly here? The advantage would be that users wouldn't need manually install types.

Another option would be externally, e.g. similar like xml2js: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/xml2js.
Users would then need to install the types package manually as described here: https://www.npmjs.com/package/@types/xml2js
Another disadvantage is that the types might become out of sync with the code more easily.

What way would you prefer, if any?

**Comment by amitguptagwl** [comment]
I've less knowledge of how TypeScript type definitions actually works at this moment. However I was also thinking to include them.

In my opinion type definition should be bundled with the project so the user need not to install any extra dependency and for easy maintenance as well.
