### ISSUE TITLE
Not work in firefox ver45

### ISSUE THREAD

**Issue by zeng450026937** [NaturalIntelligence/fast-xml-parser#72]
Should not use ‘let' or ’const‘ as they might not be supported.

**Comment by amitguptagwl** [comment]
which version are you trying?

**Comment by zeng450026937** [comment]
i'm using version 3.3.6.
the only one for/in loop in j2x.js, is writed like
```js
for (const v in cdata) {}
```
it might not work properly in older version of browser.

**Comment by amitguptagwl** [comment]
> Please always fill the issue template while raising an issue. It avoids long communication and helps to understand and resolve problem fast.

I've checked the bundle file. And I can't find any occurrence of *const*. Can you please tell me the following

* Have you tried to run the demo in the browser where you are facing the issue?
* Are you using the browser library from cdn or from git repository?

**Comment by zeng450026937** [comment]
I'm using yarn for my pkg manager.
I use the version(3.3.6) in my project, and it is failed to run in firefox45.
```js
for (const v in cdata) {
// some code
}
```
above code was found in the j2x.js file in main branch, which is what I'm using.

---

while below code you see, which may be found in the dev branch, and 'var' is used instead. 
```js
for (var v in cdata) {
// some code
}
```

**Comment by amitguptagwl** [comment]
What I can understand from your comment, you are using FXP in your node package. Then you're building browser bundle. If yes then you should use browser bundler which can transform ES6 syntax to ES5. If no then you should use js file from [lib](https://github.com/NaturalIntelligence/fast-xml-parser/tree/master/lib) of FXP github repository, or from [cdn](https://cdnjs.com/libraries/fast-xml-parser).

You should try running [demo](https://naturalintelligence.github.io/fast-xml-parser/) first in browser which use js file from lib folder of FXP github repo.  (as I asked in previous comment)

The code I referred is from master branch of FXP.

**Comment by zeng450026937** [comment]
If that, change the main file in package.json to lib folder will be good for all user. if someone uses it to build for browser, usually node modules will not be processed.
