### ISSUE TITLE
XML to JSON parsing problem when end tag name contains space before the '>'

### ISSUE THREAD

**Issue by sguimont** [NaturalIntelligence/fast-xml-parser#77]
We received from our customers not so perfect XML and sometime we received XML documents with end tag name with space.  This space cause some strange JSON object output.

The name2 tag in the output  must be link directly to person tag not within the name1 tag.

### Input
```xml
<?xml version="1.0"?>
<any_name>
    <person>
        <name1>Jack 1</name1 >
        <name2>Jack 2</name2>
    </person>
</any_name>
```
                        
### Code
I used the online test page at https://naturalintelligence.github.io/fast-xml-parser/.  I got the same issue when running with the code.  I try many options in the test page and none has effect on the output generated.

### Output
```js
{
    "any_name": {
        "person": {
            "name1": {
                "#text": "Jack 1",
                "name2": "Jack 2"
            }
        }
    }
}
```

### expected data
```js
{
    "any_name": {
        "person": {
            "name1": "Jack 1",
            "name2": "Jack 2"
        }
    }
}
```

**Comment by amitguptagwl** [comment]
I'm working on a feature of [अनुमार्गक (Anumargak)](https://github.com/NaturalIntelligence/anumargak). I'll complete that today hopefully then will work on this issue. Meanwhile, if you are interested to raise a PR, this is the [line](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/x2j.js#L45) which may fix the issue.

**Comment by sguimont** [comment]
Thanks for your quick response and fix.
