### ISSUE TITLE
Add feature of JSON to XML to online tool 

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#79]
> This issue is raised for developers who are just starting with open source development. So please refrain yourself if you're experienced.
 
Please check README or [spec](https://github.com/NaturalIntelligence/fast-xml-parser/tree/master/spec) folder for examples.

[Online demo tool](https://naturalintelligence.github.io/fast-xml-parser/) demonstrate what XML parser can do. However it is currently just parsing XML to JSON and validating XML only. As a part of this change, we have to parse JSON to XML;

You may discuss here about design changes.

Check [how to](https://github.com/Roshanjossey/first-contributions).

**Comment by geekiam23** [comment]
I'd like to give it a shot.

**Comment by amitguptagwl** [comment]
@geekiam23 any update on this issue? Is it fine if any other contributor can pick this issue?

**Comment by geekiam23** [comment]
@amitguptagwl Yeah, I couldn't figure it out. Please let someone else give it a shot.

**Comment by amitguptagwl** [comment]
This issue can be picked by any contributor now. Demo UI has been simplified. So now it is just the matter of 10 mins change.

**Comment by sakshivij** [comment]
Hey! I would like to work on this issue.

**Comment by amitguptagwl** [comment]
Yes, please go on.

**Comment by amitguptagwl** [comment]
@sakshivij have you got the chance to work on?

**Comment by sakshivij** [comment]
Yes! I am working on it. I just need this weekend. If I'm not able to resolve the issue, I'll let you know by Sunday.

**Comment by amitguptagwl** [comment]
No problem, take your time. It's not urgent. I just wanted to check if you have stuck in some issues and need help

**Comment by sakshivij** [comment]
A little bit of hint would be great!

**Comment by amitguptagwl** [comment]
Umm.. what are you actually trying?

1. Open the index.html
2. Open the section which is showing options and buttons to parse XML to JSON
3. Paste and create another section. Change the IDs. Modify the options as per the example snippet given on [README.md](https://github.com/NaturalIntelligence/fast-xml-parser#json--js-object-to-xml)
4. Add javascript code to read options and call JSON to XML parser. It is present on index.html only.

**Comment by sakshivij** [comment]
Yes! I have done the same thing. But the code gives error. 
![image](https://user-images.githubusercontent.com/20201675/42135251-0769a274-7d66-11e8-92b3-ada697a65e99.png)

**Comment by sakshivij** [comment]
I don't know but somehow the browser is not able to reference Parser. The code works fine on console.

**Comment by sakshivij** [comment]
Unfortunately error persists!!

**Comment by amitguptagwl** [comment]
Are you seeing the errors here as well?

https://naturalintelligence.github.io/fast-xml-parser/

I've checked it on firefox and chrome on Ubuntu and it seems working fine.

Ah! I think I got it. You must be seeing this error after your changes. You should have used variable name in small letters "parser" not "Parser

**Comment by lfplazas10** [comment]
Is this task still undone? If so, I would like to tackle it.

**Comment by amitguptagwl** [comment]
@lfplazas10 Yes please go on.

**Comment by jmarkham828** [comment]
I see this issue has not been closed, are you still working on it? If so, I'd love to be able to try to help.

**Comment by amitguptagwl** [comment]
@jmarkham828 This issue was created for new contributors. But it looks like they're facing some problems. So yes you can give a try. If you need any help, let me know.

**Comment by amitguptagwl** [comment]
@jmarkham828 where did you reach?
