### ISSUE TITLE
Leaves out Key/Value pair when value contains single quotes

### ISSUE THREAD

**Issue by brad1121** [NaturalIntelligence/fast-xml-parser#8]
Not sure if this is intended or not, but take the following
`<Event time="00:05:00" customAttr="5" ID="568" Name="'Some Name' some more alpha numeric string ">`

When this is parsed the Name attribute is skipped.

How can I either write a custom validation on key/values, or set an option to allow this? Or is this a bug?

I will add, it parses correctly in xml2js

**Comment by amitguptagwl** [comment]
Can you plz share the complete XML?

**Comment by brad1121** [comment]
I can't. It's a feed which changes daily that is not publicly available. This is an **out of the ordinary** occurrence. It has been running fine for the last 5 days... I can give a altered sample of the complete schema.

This is a one off where the Name field had a nested '' in it where it typically shouldn't.

```
<root>
<Meet date="2017-05-03" type="A" name="Meeting A">
   <Event time="00:05:00" ID="574" Name="Some Event Name">
         <User ID="1">Bob</User>
    </Event>
</Meet>
</root>
```
There can be thousands of Meet's in root, There are between 8-13 events per Meet. and any number of Users per event. But they all follow the same layout.

**Comment by amitguptagwl** [comment]
@brad1121 single quote in value is allowed if the complete value is enclosed in double quote and vise versa. If the parser is ignoring only single attribute but parsing all other attributes then it seems a bug otherwise it is configuration issue.

Can you plz send me what is the parsed response? 

I don't have any machine for next 2 weeks at least. So I'll not be much active to fix the issue, if any. Sorry for inconvenience.

**Comment by brad1121** [comment]
All other nodes without the nested single quotes worked as expected.

Parsed Event response as follows.

```
{
"time": "00:05:00",
"ID": 574,
"User" : [ ... ]
}
```

Setup as follows 

```
fastXmlParser.parse( XML,
                       {
                        attrPrefix : "",
                        textNodeName : '_',
                        ignoreNonTextNodeAttr : false,
                        ignoreTextNodeAttr : false,
                        ignoreNameSpace : false
});
```

**Comment by amitguptagwl** [comment]
Thanks for your response. I hopefully buy a machine and internet this
weekend. So I'll solve your issues soon.

**Comment by amitguptagwl** [comment]
Fixed. Plz refer version 2.4.4

Thanks for the patience.
