### ISSUE TITLE
Replace Zombie js

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#81]
We're currently using zombie js to test if demo application is running as expected. There are some vulnerabilities reported by snyk, and github in deep dependencies. It has no impact on this current library. But we are planning to get rid of these warning messages by replacing it with some alternatives.

*The priority of this issue is low as there is no impact on application or test.*

**What to do?**

Replace zombie with alternate dependency in `spec/demoapp_spec.js`

**Comment by amitguptagwl** [comment]
You're welcome. You'll have to find an alternate library first which can be used without any complex configuration. This library is being used in only test. So this PR should not impact actual code.

**Comment by EmPiFree** [comment]
Is there a fast way to test it out?

**Comment by amitguptagwl** [comment]
Tests are written with the help jasmine test framework. You can clone the current project in your local using `git clone`, then install all the dependencies using `npm init`, and then run the tests using `npm run test`.

**Comment by amitguptagwl** [comment]
@EmPiFree any update on this? I'm feeling to close this issue due to the false positive security alarms.

**Comment by amitguptagwl** [comment]
Thanks for the update @EmPiFree
