### ISSUE TITLE
Doesn't support cyrillic characters

### ISSUE THREAD

**Issue by serggonin** [NaturalIntelligence/fast-xml-parser#87]
### Checklist

* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
1) create file index.js and put js code there
2) type next commands in terminal:
npm init
npm i fast-xml-parser
node index.js

### Code
```js
const parser = require("fast-xml-parser");
function xmlToJson () {
  try {
    const xmlData = `<КорневаяЗапись><Тэг>Значение</Тэг><Тэг2><Код>5</Код></Тэг2></КорневаяЗапись>`;
    console.log({json: parser.parse(xmlData)});
  } catch (e) {
    console.log(e);
  }
}
xmlToJson();

```

### Output
Output data just was empty

### expected data
{ 'КорневаяЗапись': { 'Тэг': 'Значение', 'Тэг2': { 'Код': 5 } } }

**Would you like to work on this issue?**

- [x] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
As the FXP is based on [regex](https://github.com/NaturalIntelligence/fast-xml-parser/blob/3f44718972dbd76d99ba479d22100df6d540a188/src/x2j.js#L45), it uses `\w` to know the tag or attribute name. I believe this is the reason it fails and don't support non-english char.

Thanks to raise the issue and handling it.

I believe to solve the problem in generic way, we can provide a language option in parsing which can  change the definition on `\w`. I would like to hear your approach.

**Comment by serggonin** [comment]
I think this is a great idea to add a language option. I changed it in my fork and it works fine for me. Also this way allow to use multilanguage xml data, beccause there is possibility to set many languages at one moment.
