### ISSUE TITLE
validate function does not work properly

### ISSUE THREAD

**Issue by mucahiddayan** [NaturalIntelligence/fast-xml-parser#93]
### Checklist

* [x] Are you running the latest version?
* [ ] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
xsltFromMozilla can be found here: https://developer.mozilla.org/en-US/docs/Web/XSLT/XSLT_JS_interface_in_Gecko/Basic_Example

### Code
```js
import validate from 'fast-xml-parser';
if(validate(xsltFromMozilla) !== true){
     //do something
};

```

### Output
// returns {
   err:{
        msg: 'Invalid char A'
    }
}

### expected data
true
**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
I tried it with online tool. and the validation was successful.

**Comment by amitguptagwl** [comment]
Feel free to reopen it if you still face the issue.

**Comment by amitguptagwl** [comment]
> Online editor is fixed to display error message

text in a tag is causing the issue. ( "Authors:   ")
