### ISSUE TITLE
Online tool says "Valid XML" no matter what you paste into the box

### ISSUE THREAD

**Issue by mbaer3000** [NaturalIntelligence/fast-xml-parser#94]
### Input
Observed behavior: Paste anything into https://naturalintelligence.github.io/fast-xml-parser/ and the box to the right says it's "Valid XML"
Desired behavior:  Paste non-XML into the left box and have the right box say it's invalid XML

**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
Oh!! Let me check

**Comment by amitguptagwl** [comment]
This might be the issue with online demo only. So removing the bug label until it is confirmed. Will check it tomorrow morning.
