### ISSUE TITLE
Break JS Browser bundle into small libraries

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/fast-xml-parser#97]
The size of `lib/parser.js` for browsers is 37 kb (normal), 15 kb (minified), 4.7kb (gzipped). If the output bundled library is divided in following then the users can select particular library they want to use.

* XML to JSObject
* JSON to XML
* JS Object to XML
* XML Validator

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by Delagen** [comment]
I think need to recover some bundling code from my earlier PR

**Comment by amitguptagwl** [comment]
There were many helpful changes in your PR. We may integrate some of them one by one.

> I may not be available for any change, review and other for next 1 week.

**Comment by Delagen** [comment]
Need some export refactoring to support it

**Comment by amitguptagwl** [comment]
Yes. And I believe FXP is mostly used as npm package, we'll have to check if this refactoring will impact existing users.
